/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Mar 03 2026 12:10:49 GMT+0530 (India Standard Time)
	Description : Create Service Interface for connectivityOption
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantCreateConnectOptionInterface = app.getTenantWSInterface('BCSSteam', 'connectivityoption/create');

if (typeof TenantCreateConnectOptionInterface === 'undefined')
	TenantCreateConnectOptionInterface = {};


module.exports = {
	onLoad: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};


		if (TenantCreateConnectOptionInterface && TenantCreateConnectOptionInterface.onLoad) {
			rObj = TenantCreateConnectOptionInterface.onLoad(params);
		}
		return rObj;
	},

	beforeData: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};

		if (params && params.data){
			try{
				params.data = JSON.parse(params.data);
			}catch(e){
				params.data = params.data;
			}

			var getAllSfmConnectOptionRespObj = dsclientUtil.execute({}, "BCSSteam", "BCSSteam_connectivity_option", "getAll");

			if(getAllSfmConnectOptionRespObj.code == 200 && getAllSfmConnectOptionRespObj.data){
				for(var idx = 0; idx < getAllSfmConnectOptionRespObj.data.length; idx++){
					if(normalizeValue(params.data.sfm_connectivity_option) == normalizeValue(getAllSfmConnectOptionRespObj.data[idx].sfm_connectivity_option)){
						rObj.override = true;
						rObj.resp = {
							"code" : 400,
							"msg" : Strings.DUPLICATE_FOUND,
							"err_code" : 409 		//duplicate vendor
						};
					}
				}
			}else{
				rObj.override = true;
				rObj.resp = {
					"code" : 400,
					"msg" : Strings.CREATE_ERROR
				}
			}
		}

		params.data = JSON.stringify(params.data);



		if (TenantCreateConnectOptionInterface && TenantCreateConnectOptionInterface.beforeData) {
			rObj = TenantCreateConnectOptionInterface.beforeData(params);
		}
		return rObj;
	},

	beforeExecute: function(queryParams) {
		//custom code here

		if (TenantCreateConnectOptionInterface && TenantCreateConnectOptionInterface.beforeExecute) {
			queryParams = TenantCreateConnectOptionInterface.beforeExecute(queryParams);
		}
		return queryParams;
	},


	afterData: function(createConnectOptionData) {


		if (TenantCreateConnectOptionInterface && TenantCreateConnectOptionInterface.afterData) {
			createConnectOptionData = TenantCreateConnectOptionInterface.afterData(createConnectOptionData);
		}
		return createConnectOptionData;
	},

	onError: function(errorObj) {


		if (TenantCreateConnectOptionInterface && TenantCreateConnectOptionInterface.onError) {
			errorObj = TenantCreateConnectOptionInterface.onError(errorObj);
		}
		return errorObj;
	}
};

function normalizeValue(value) {
	if (!value) {
		return "";
	}

	return value.toString().toLowerCase().replace(/\s+/g, "");
}