/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 05 2026 15:49:46 GMT+0530 (India Standard Time)
	Description : Get Service Interface for sfm
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetSfmInterface = app.getTenantWSInterface('BCSSteam', 'sfm/get');

if (typeof TenantGetSfmInterface === 'undefined')
  TenantGetSfmInterface = {};

module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetSfmInterface && TenantGetSfmInterface.onLoad) {
      rObj = TenantGetSfmInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetSfmInterface && TenantGetSfmInterface.beforeData) {
      rObj = TenantGetSfmInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams) {
    //custom code here

    if (TenantGetSfmInterface && TenantGetSfmInterface.beforeExecute) {
      queryParams = TenantGetSfmInterface.beforeExecute(queryParams);
    }
    return queryParams;
  },


  afterData: function(getSfmData) {


    if (TenantGetSfmInterface && TenantGetSfmInterface.afterData) {
      getSfmData = TenantGetSfmInterface.afterData(getSfmData);
    }
    return getSfmData;
  },

  onError: function(errorObj) {


    if (TenantGetSfmInterface && TenantGetSfmInterface.onError) {
      errorObj = TenantGetSfmInterface.onError(errorObj);
    }
    return errorObj;
  }
};