/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 26 2026 19:53:27 GMT+0530 (India Standard Time)
	Description : Get Service Interface for unit 
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetUnitInterface = app.getTenantWSInterface('BCSFuel', 'master/getunit');

if (typeof TenantGetUnitInterface === 'undefined')
  TenantGetUnitInterface = {};


module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };

    if (TenantGetUnitInterface && TenantGetUnitInterface.onLoad) {
      rObj = TenantGetUnitInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetUnitInterface && TenantGetUnitInterface.beforeData) {
      rObj = TenantGetUnitInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams, qType) {
    //custom code here

    if (TenantGetUnitInterface && TenantGetUnitInterface.beforeExecute) {
      queryParams = TenantGetUnitInterface.beforeExecute(queryParams, qType);
    }
    return queryParams;
  },

  afterData: function(getUnitData) {


    if (TenantGetUnitInterface && TenantGetUnitInterface.afterData) {
      getUnitData = TenantGetUnitInterface.afterData(getUnitData);
    }
    return getUnitData;
  },

  onError: function(errorObj) {

    if (TenantGetUnitInterface && TenantGetUnitInterface.onError) {
      errorObj = TenantGetUnitInterface.onError(errorObj);
    }
    return errorObj;
  }
};