/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 26 2026 20:01:36 GMT+0530 (India Standard Time)
	Description : CombineMaster Save Service for yard
	WARNING : DO NOT MODIFY THIS FILE
*/

//External library
var dsclientUtil = require('dsclient');
var uuid = require('uuid');


//Internal library
var Strings = require("../common/strings.js");
var appcommon = require("../common/common.js");

var saveYardInterface = require("saveyardinterface.js");

try {

  //Setting cache as null
  $g.response.headers["Cache-Control"] = "max-age=0";
  $g.response.headers["Cache-Control"] = "no-store";


  //Success response object
  var respObj = {
    code: 200,
    msg: Strings.UPDATE_YARD_SUCCESS
  };


  //Checking whether the request is in query or body
  var params = appcommon.processParams($g.request);
  var paramStr = JSON.stringify(params);

  //check for Language setup 
  if (params && params.l) {
    var filePath = "/common/lang/";
    appcommon.initLanguage(params.l, filePath);
  }


  var MASTER_TABLE = "bcsfuel_yard";


  // Call 'onLoad' method from the Interface with params as the argument
  var onLoadRes = null;
  if (saveYardInterface && saveYardInterface.onLoad)
    onLoadRes = saveYardInterface.onLoad(params);

  // Check if 'onLoad' override is true
  if (onLoadRes && onLoadRes.override === true) {
    if (onLoadRes.resp) {
      if (onLoadRes.resp.code) {
        respObj = onLoadRes.resp;
      } else {
        respObj.code = 500;
        respObj.msg = Strings.SERVER_ERROR;
        if (saveYardInterface && saveYardInterface.onError)
          respObj = saveYardInterface.onError(respObj);
        console.error("Unexpected server error when retrieving the yard - " + paramStr);
      }
    }
  } else {

    // Calling 'beforeData' method from Interface and passing params as argument
    var beforeDataRes = null;
    if (saveYardInterface && saveYardInterface.beforeData)
      beforeDataRes = saveYardInterface.beforeData(params);

    // Check if 'override' is true
    if (beforeDataRes && beforeDataRes.override === true) {
      //Sending request to ds client
      if (beforeDataRes.resp) {
        if (beforeDataRes.resp.code) {
          respObj = beforeDataRes.resp;
        } else {
          respObj.code = 500;
          respObj.msg = Strings.SERVER_ERROR;
          if (saveYardInterface && saveYardInterface.onError)
            respObj = saveYardInterface.onError(respObj);
        }
      }
    } else {
      if (beforeDataRes && beforeDataRes.params)
        params = beforeDataRes.params;

      //Only if params is there
      if (params && params.data) {

        var queryParams = {
          "cols": ["master_name", "master_data", "edited_by", "edited_on"],
          "filter": [{
            "col": "master_name",
            "op": "=",
            "val": MASTER_TABLE
          }]
        };



        if (saveYardInterface && saveYardInterface.beforeExecute)
          queryParams = saveYardInterface.beforeExecute(queryParams, "query");

        masterRespObj = dsclientUtil.execute(queryParams, "BCSFuel", "bcsfuel_combined_master", "query");
        if (masterRespObj) {
          var newData = JSON.parse(params.data);
          var dataArr = JSON.parse(newData.master_data);
          for (var d = 0; d < dataArr.length; d++) {
            var dataObj = dataArr[d];
            if (!dataObj.id)
              dataObj.id = uuid.get();

            dataArr[d] = dataObj;
          }


          var masterObj = (masterRespObj.data.length > 0) ? masterRespObj.data[0] : null; //There will always be only one entry in combined Master for a specific master table


          if (masterObj) { //master already has data, new data should be appended
            masterObj.master_data = JSON.stringify(dataArr);
            masterObj.edited_by = newData.edited_by;
            masterObj.edited_on = newData.edited_on;

            var masterDataStr = JSON.stringify(masterObj);

            if (saveYardInterface && saveYardInterface.beforeExecute)
              masterDataStr = saveYardInterface.beforeExecute(masterDataStr, "update");

            //Sending request to ds client
            respObj = dsclientUtil.execute({
              data: masterDataStr
            }, "BCSFuel", "bcsfuel_combined_master", "update");

          } else { //master has no data, new data should be created
            masterObj = {
              "master_name": MASTER_TABLE,
              "master_data": JSON.stringify(dataArr),
              "edited_by": newData.edited_by,
              "edited_on": newData.edited_on
            };

            var masterDataStr = JSON.stringify(masterObj);

            if (saveYardInterface && saveYardInterface.beforeExecute)
              masterDataStr = saveYardInterface.beforeExecute(masterDataStr, "insert");

            //Sending request to ds client
            respObj = dsclientUtil.execute({
              data: masterDataStr
            }, "BCSFuel", "bcsfuel_combined_master", "insert");
          }
        }
      } else {
        respObj.code = 400;
        respObj.msg = Strings.UPDATE_YARD_ERROR;
        if (saveYardInterface && saveYardInterface.onError)
          respObj = saveYardInterface.onError(respObj);
      }
    }



    switch (respObj.code) {
      case 200:
        if (saveYardInterface && saveYardInterface.afterData)
          respObj.data = saveYardInterface.afterData(respObj.data);
        respObj.msg = Strings.UPDATE_YARD_SUCCESS;
        break;
      case 400:
        respObj.msg = Strings.UPDATE_YARD_ERROR;
        if (saveYardInterface && saveYardInterface.onError)
          respObj = saveYardInterface.onError(respObj);
        console.error("Unable to save the 'yard' - " + paramStr);
        break;
      case 403:
        respObj.msg = Strings.ACCESS_DENIED;
        if (saveYardInterface && saveYardInterface.onError)
          respObj = saveYardInterface.onError(respObj);
        console.error("User access denied when saving the 'yard' - " + paramStr);
        break;
      case 500:
        respObj.msg = Strings.SERVER_ERROR;
        if (saveYardInterface && saveYardInterface.onError)
          respObj = saveYardInterface.onError(respObj);
        console.error("Unexpected server error when saving the 'yard' - " + paramStr);
        break;
    }


  }


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = respObj.code;
  $g.response.body = JSON.stringify(respObj);

} catch (e) {

  //Error response object
  var errorRespObj = {
    status: 500,
    message: Strings.SERVER_ERROR + " - " + e.message,
    stack: e.stack
  };
  if (saveYardInterface && saveYardInterface.onError)
    errorRespObj = saveYardInterface.onError(errorRespObj);
  console.error("Unexpected server error when saving the yard - " + paramStr + "-" + errorRespObj.message);


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = errorRespObj.status;
  $g.response.body = JSON.stringify(errorRespObj);

}