/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 26 2026 20:01:36 GMT+0530 (India Standard Time)
	Description : CombineMaster Save Service Interface for yard
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantSaveYardInterface = app.getTenantWSInterface('BCSFuel', 'master/saveyard');

if (typeof TenantSaveYardInterface === 'undefined')
	TenantSaveYardInterface = {};

module.exports = {
	onLoad: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};


		if (TenantSaveYardInterface && TenantSaveYardInterface.onLoad) {
			rObj = TenantSaveYardInterface.onLoad(params);
		}

		return rObj;
	},

	beforeData: function (params) {

		var rObj = {
			"override": false,
			"params": params
		};

		var refFlag = false;
		var deletedDup = false;

		// Only one reference source as per requirement
		var conflictSources = {
			loss: false
		};

		var yardDataArr;
		var deletedObjectsArr = [];
		var deletedWithRefArr = [];

		var paramData = JSON.parse(params.data);
		var paramArr = JSON.parse(paramData.master_data);

		var MASTER_TABLE = "bcsfuel_yard";

		// Fetch existing Fuel Yards
		var queryParams = {
			"cols": [
				"master_name",
				"master_data",
				"edited_by",
				"edited_on"
			],
			"filter": [
				{
					"col": "master_name",
					"op": "=",
					"val": MASTER_TABLE
				}
			]
		};

		var masterRespObj = dsclientUtil.execute(queryParams, "BCSFuel", "bcsfuel_combined_master", "query");


		if (masterRespObj && masterRespObj.code === 200 && masterRespObj.data && masterRespObj.data.length > 0) {

			yardDataArr = JSON.parse(masterRespObj.data[0].master_data);
			// Identify Deleted Items
			for (var i = 0; i < yardDataArr.length; i++) {
				var found = false;
				var existingObj = yardDataArr[i];

				for (var j = 0; j < paramArr.length; j++) {
					if (existingObj.id === paramArr[j].id) {
						found = true;
						break;
					}
				}

				if (!found) {
					deletedObjectsArr.push(existingObj);
				}
			}

			if (deletedObjectsArr.length > 0) {

				// Soft Duplicate Handling (delete + add same yard code)
				var deleteCheckObj = {
					"idArr":[],
					"deletDupId":[]
				};

				for (var p = 0; p < paramArr.length; p++) {
					for (var d = 0; d < deletedObjectsArr.length; d++) {
						if (paramArr[p].id == null && normalize(paramArr[p].yard_code) === normalize(deletedObjectsArr[d].yard_code)) {
							paramArr[p].id = deletedObjectsArr[d].id;
							//testing
							deleteCheckObj.idArr.push(paramArr[p].id);
							deleteCheckObj.deletDupId.push(deletedObjectsArr[d].id);
							
							
							deletedObjectsArr.splice(d, 1);
							deletedDup = true;
							break;
						}
					}
				}

				// Prepare List of IDs to Check

				if (deletedObjectsArr.length > 0) {

					var deletedIdsOnly = [];
					for (var x = 0; x < deletedObjectsArr.length; x++) {
						deletedIdsOnly.push(deletedObjectsArr[x].id);
					}

					var formattedIds = _formatArrForInQuery(deletedIdsOnly);

					var lossQuery = {
						"cols": ["fuel_yard_id"],
						"filter": [
							{
								"col": "fuel_yard_id",
								"op": "IN",
								"val": formattedIds
							}
						]
					};

					var lossResp = dsclientUtil.execute(lossQuery,"BCSFuel","bcsfuel_loss","query");

					if (lossResp && lossResp.code === 200 && lossResp.data.length > 0) {
						for (var l = 0; l < lossResp.data.length; l++) {
							_addToDeletedRef(
								lossResp.data[l].fuel_yard_id,
								deletedObjectsArr,
								deletedWithRefArr
							);
						}
						refFlag = true;
						conflictSources.loss = true;
					}
				}

				if (deletedWithRefArr.length > 0 || deletedDup === true) {

					var finalDataToSave = paramArr.concat(deletedWithRefArr);

					var masterUpdateObj = {
						"master_name": MASTER_TABLE,
						"master_data": JSON.stringify(finalDataToSave),
						"edited_by": paramData.edited_by,
						"edited_on": paramData.edited_on,
						"_sid": masterRespObj.data[0]._sid
					};

					var respObj = dsclientUtil.execute({ data: JSON.stringify(masterUpdateObj) },"BCSFuel","bcsfuel_combined_master","update");

					if (respObj && respObj.code === 200) {
						rObj.override = true;
						rObj.resp = {
							"code": 400,
							"msg": Strings.FOREGIN_REFERENCE_FOUND || "Cannot delete: Data is in use.",
							"err_code": 422,
							"data": JSON.parse(respObj.data.master_data),
							"deletedWithRefArr": deletedWithRefArr,
							"refFlag": refFlag,
							"deletedDup": deletedDup,
							"conflictSources": conflictSources,
							"deleteCheckObj": deleteCheckObj
							
						};
					} else {
						rObj.override = true;
						rObj.resp = { "code": 400, 
									 "msg": "Error Saving Data",
									 "err_code": 400,
									 "respObj": respObj
									 
									};
					}
				}
			}
		}

		if (TenantSaveYardInterface && TenantSaveYardInterface.beforeData) {
			rObj = TenantSaveYardInterface.beforeData(params);
		}

		return rObj;
	},


	beforeExecute: function(queryParams, qType) {
		//custom code here

		if (TenantSaveYardInterface && TenantSaveYardInterface.beforeExecute) {
			queryParams = TenantSaveYardInterface.beforeExecute(queryParams, qType);
		}
		return queryParams;
	},

	afterData: function(saveYardData) {


		if (TenantSaveYardInterface && TenantSaveYardInterface.afterData) {
			saveYardData = TenantSaveYardInterface.afterData(saveYardData);
		}
		return saveYardData;
	},

	onError: function(errorObj) {

		if (TenantSaveYardInterface && TenantSaveYardInterface.onError) {
			errorObj = TenantSaveYardInterface.onError(errorObj);
		}
		return errorObj;
	}
};

function _formatArrForInQuery(arr) {
	var result = [];
	for (var i = 0; i < arr.length; i++) {
		result.push("'" + arr[i] + "'");
	}
	return "(" + result.join(", ") + ")";
}

function normalize(val) {
	if (typeof val !== "string") return "";
	return val.toLowerCase().replace(/\s+/g, "");
}

// Helper to prevent adding duplicates to the referenced array
function _addToDeletedRef(id, sourceArr, targetArr) {
	// Check if already in target
	for(var t=0; t<targetArr.length; t++) {
		if(targetArr[t].id == id) return;
	}
	// Find in source and add
	for(var s=0; s<sourceArr.length; s++) {
		if(sourceArr[s].id == id) {
			targetArr.push(sourceArr[s]);
			break;
		}
	}
}
