/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 26 2026 19:59:23 GMT+0530 (India Standard Time)
	Description : CombineMaster Save Service Interface for unit
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantSaveUnitInterface = app.getTenantWSInterface('BCSFuel', 'master/saveunit');

if (typeof TenantSaveUnitInterface === 'undefined')
	TenantSaveUnitInterface = {};

module.exports = {
	onLoad: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};


		if (TenantSaveUnitInterface && TenantSaveUnitInterface.onLoad) {
			rObj = TenantSaveUnitInterface.onLoad(params);
		}

		return rObj;
	},

	beforeData: function (params) {
		var rObj = { "override": false,
					"params": params };

		var refFlag = false;
		var deletedDup = false;

		// Flags to tell the UI exactly where the conflict is
		var conflictSources = {
			code: false, 
			vendor: false,
			utilization: false,
			purchase: false,
			consumption: false,
			loss: false
		};

		var unitDataArr;
		var deletedObjectsArr = [];
		var deletedWithRefArr = [];

		var paramData = JSON.parse(params.data);
		var paramArr = JSON.parse(paramData.master_data);

		var MASTER_TABLE = "bcsfuel_unit";

		// Fetch existing Units
		var queryParams = {
			"cols": [
				"master_name",
				"master_data",
				"edited_by",
				"edited_on"
			],
			"filter": [
				{
					"col": "master_name",
					"op": "=",
					"val": MASTER_TABLE
				}
			]
		};

		var masterRespObj = dsclientUtil.execute(queryParams, "BCSFuel", "bcsfuel_combined_master", "query");

		if (masterRespObj && masterRespObj.code === 200 && masterRespObj.data && masterRespObj.data.length > 0) {

			unitDataArr = JSON.parse(masterRespObj.data[0].master_data);

			// Identify Deleted Items
			for (var unitIdx = 0; unitIdx < unitDataArr.length; unitIdx++) {
				var found = false;
				var singleObj = unitDataArr[unitIdx];
				for (var paramIdx = 0; paramIdx < paramArr.length; paramIdx++) {
					if (singleObj.id === paramArr[paramIdx].id) {
						found = true; break;
					}
				}
				if (!found) deletedObjectsArr.push(singleObj);
			}

			if (deletedObjectsArr.length > 0) {

				// Handle Soft Duplicates (Delete + Add Same Name)
				for (var paramIdx = 0; paramIdx < paramArr.length; paramIdx++) {
					for (var deletedIdx = 0; deletedIdx < deletedObjectsArr.length; deletedIdx++) {
						if (paramArr[paramIdx].id == null && normalize(paramArr[paramIdx].unit) === normalize(deletedObjectsArr[deletedIdx].unit)) {
							paramArr[paramIdx].id = deletedObjectsArr[deletedIdx].id;
							deletedObjectsArr.splice(deletedIdx, 1);
							deletedDup = true;
							break;
						}
					}
				}

				// Prepare List of IDs to Check
				var deletedIdsOnly = [];
				for (var i = 0; i < deletedObjectsArr.length; i++) {
					deletedIdsOnly.push(deletedObjectsArr[i].id);
				}

				// Only proceed if there are still items to check
				if(deletedIdsOnly.length > 0) {

					var formattedIds = _formatArrForInQuery(deletedIdsOnly);

					// Check Fuel Codes (bcsfuel_code)
					var codeQuery = {
						"cols": ["master_name","master_data"],
						"filter": [
							{  
								"col": "master_name",
								"op": "=",
								"val": "bcsfuel_code" 
							}
						] 
					};
					var codeResp = dsclientUtil.execute(codeQuery, "BCSFuel", "bcsfuel_combined_master", "query");
					if (codeResp && codeResp.code === 200 && codeResp.data.length > 0) {
						var cData = JSON.parse(codeResp.data[0].master_data);
						for (var c = 0; c < cData.length; c++) {
							// Check if fuel_unit_id exists in the Code object
							if (deletedIdsOnly.indexOf(cData[c].unit) > -1) {
								_addToDeletedRef(cData[c].unit, deletedObjectsArr, deletedWithRefArr);
								refFlag = true;
								conflictSources.code = true;
							}
						}
					}


					


					// Check Vendors (bcsfuel_vendor)
					var vendorQuery = {
						"cols": ["master_name","master_data"],
						"filter": [
							{  
								"col": "master_name",
								"op": "=",
								"val": "bcsfuel_vendor"
							}
						] 
					};
					var vendorResp = dsclientUtil.execute(vendorQuery, "BCSFuel", "bcsfuel_combined_master", "query");
					if (vendorResp && vendorResp.code === 200 && vendorResp.data.length > 0) {
						var vData = JSON.parse(vendorResp.data[0].master_data);
						for (var v = 0; v < vData.length; v++) {
							if (deletedIdsOnly.indexOf(vData[v].fuel_unit_id) > -1) {
								_addToDeletedRef(vData[v].fuel_unit_id, deletedObjectsArr, deletedWithRefArr);
								refFlag = true;
								conflictSources.vendor = true;
							}
						}
					}

					//Check Utilization Points (bcsfuel_utilizationPoint)
					var utilQuery = {
						"cols": ["master_name","master_data"],
						"filter": [
							{ "col": "master_name",
							 "op": "=", 
							 "val": "bcsfuel_utilizationPoint"
							}
						] 
					};
					var utilResp = dsclientUtil.execute(utilQuery, "BCSFuel", "bcsfuel_combined_master", "query");
					if (utilResp && utilResp.code === 200 && utilResp.data.length > 0) {
						var uData = JSON.parse(utilResp.data[0].master_data);
						for (var u = 0; u < uData.length; u++) {
							if (deletedIdsOnly.indexOf(uData[u].fuel_unit_id) > -1) {
								_addToDeletedRef(uData[u].fuel_unit_id, deletedObjectsArr, deletedWithRefArr);
								refFlag = true;
								conflictSources.utilization = true;
							}
						}
					}

					//TRANSACTION DATA CHECKS

					var checkRefQuery = {
						"cols": ["fuel_unit_id"], 
						"filter": [
							{ 
								"col": "fuel_unit_id", 
								"op": "IN", 
								"val": formattedIds 
							}
						]
					};

					// Purchase Data
					var purchaseResp = dsclientUtil.execute(checkRefQuery, "BCSFuel", "bcsfuel_purchase", "query");
					if (purchaseResp && purchaseResp.code === 200 && purchaseResp.data.length > 0) {
						for(var p=0; p<purchaseResp.data.length; p++) {
							_addToDeletedRef(purchaseResp.data[p].fuel_unit_id, deletedObjectsArr, deletedWithRefArr);
						}
						refFlag = true;
						conflictSources.purchase = true;
					}

					// Consumption Data
					var consumptionResp = dsclientUtil.execute(checkRefQuery, "BCSFuel", "bcsfuel_consumption", "query");
					if (consumptionResp && consumptionResp.code === 200 && consumptionResp.data.length > 0) {
						for(var c=0; c<consumptionResp.data.length; c++) {
							_addToDeletedRef(consumptionResp.data[c].fuel_unit_id, deletedObjectsArr, deletedWithRefArr);
						}
						refFlag = true;
						conflictSources.consumption = true;
					}

					// Loss Data
					var lossResp = dsclientUtil.execute(checkRefQuery, "BCSFuel", "bcsfuel_loss", "query");
					if (lossResp && lossResp.code === 200 && lossResp.data.length > 0) {
						for(var l=0; l<lossResp.data.length; l++) {
							_addToDeletedRef(lossResp.data[l].fuel_unit_id, deletedObjectsArr, deletedWithRefArr);
						}
						refFlag = true;
						conflictSources.loss = true;
					}
				}

				// Final Block Logic
				if (deletedWithRefArr.length > 0 || deletedDup === true) {

					var finalDataToSave = paramArr.concat(deletedWithRefArr);

					var masterUpdateObj = {
						"master_name": MASTER_TABLE,
						"master_data": JSON.stringify(finalDataToSave),
						"edited_by": paramData.edited_by,
						"edited_on": paramData.edited_on,
						"_sid": masterRespObj.data[0]._sid
					};

					var respObj = dsclientUtil.execute({ data: JSON.stringify(masterUpdateObj) }, "BCSFuel", "bcsfuel_combined_master","update");

					if (respObj && respObj.code === 200) {
						rObj.override = true;
						rObj.resp = {
							"code": 400,
							"msg": Strings.FOREGIN_REFERENCE_FOUND || "Cannot delete: Data is in use.",
							"err_code": 422,
							"data": JSON.parse(respObj.data.master_data),
							"deletedWithRefArr": deletedWithRefArr,
							"refFlag": refFlag,
							"deletedDup": deletedDup,
							"conflictSources": conflictSources 
						};
					} else {
						rObj.override = true;
						rObj.resp = { "code": 400, 
									 "msg": "Error Saving Data",
									 "err_code": 400,
									 "respObj": respObj
									};
					}
				}
			}
		}

		if (TenantSaveUnitInterface && TenantSaveUnitInterface.beforeData) {
			rObj = TenantSaveUnitInterface.beforeData(params);
		}

		return rObj;
	},

	beforeExecute: function(queryParams, qType) {
		//custom code here

		if (TenantSaveUnitInterface && TenantSaveUnitInterface.beforeExecute) {
			queryParams = TenantSaveUnitInterface.beforeExecute(queryParams, qType);
		}
		return queryParams;
	},

	afterData: function(saveUnitData) {


		if (TenantSaveUnitInterface && TenantSaveUnitInterface.afterData) {
			saveUnitData = TenantSaveUnitInterface.afterData(saveUnitData);
		}
		return saveUnitData;
	},

	onError: function(errorObj) {

		if (TenantSaveUnitInterface && TenantSaveUnitInterface.onError) {
			errorObj = TenantSaveUnitInterface.onError(errorObj);
		}
		return errorObj;
	}
};

function _formatArrForInQuery(arr) {
	var result = [];
	for (var i = 0; i < arr.length; i++) {
		result.push("'" + arr[i] + "'");
	}
	return "(" + result.join(", ") + ")";
}

function normalize(val) {
	if (typeof val !== "string") return "";
	return val.toLowerCase().replace(/\s+/g, "");
}

// Helper to prevent adding duplicates to the referenced array
function _addToDeletedRef(id, sourceArr, targetArr) {
	// Check if already in target
	for(var t=0; t<targetArr.length; t++) {
		if(targetArr[t].id == id) return;
	}
	// Find in source and add
	for(var s=0; s<sourceArr.length; s++) {
		if(sourceArr[s].id == id) {
			targetArr.push(sourceArr[s]);
			break;
		}
	}
}