/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 05 2026 15:47:17 GMT+0530 (India Standard Time)
	Description : Get All Service Interface for sfm
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetAllSfmInterface = app.getTenantWSInterface('BCSSteam', 'sfm/getall');

if (typeof TenantGetAllSfmInterface === 'undefined')
  TenantGetAllSfmInterface = {};

module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };

    if (TenantGetAllSfmInterface && TenantGetAllSfmInterface.onLoad) {
      rObj = TenantGetAllSfmInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetAllSfmInterface && TenantGetAllSfmInterface.beforeData) {
      rObj = TenantGetAllSfmInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams) {
    //custom code here

    if (TenantGetAllSfmInterface && TenantGetAllSfmInterface.beforeExecute) {
      queryParams = TenantGetAllSfmInterface.beforeExecute(queryParams);
    }
    return queryParams;
  },

  afterData: function(getAllSfmData) {

    if (TenantGetAllSfmInterface && TenantGetAllSfmInterface.afterData) {
      getAllSfmData = TenantGetAllSfmInterface.afterData(getAllSfmData);
    }
    return getAllSfmData;
  },

  onError: function(errorObj) {

    if (TenantGetAllSfmInterface && TenantGetAllSfmInterface.onError) {
      errorObj = TenantGetAllSfmInterface.onError(errorObj);
    }
    return errorObj;
  }
};