/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Jan 06 2026 10:00:29 GMT+0530 (India Standard Time)
	Description : Create Service Interface for utility
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantCreateUtilityInterface = app.getTenantWSInterface('BCSSteam', 'utility/create');

if (typeof TenantCreateUtilityInterface === 'undefined')
	TenantCreateUtilityInterface = {};


module.exports = {
	onLoad: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};


		if (TenantCreateUtilityInterface && TenantCreateUtilityInterface.onLoad) {
			rObj = TenantCreateUtilityInterface.onLoad(params);
		}
		return rObj;
	},

	beforeData: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};


		if (params && params.data){
			try{
				params.data = JSON.parse(params.data);
			}catch(e){
				params.data = params.data;
			}

			var getAllUtilityRespObj = dsclientUtil.execute({}, "BCSSteam", "BCSSteam_utility", "getAll");

			if(getAllUtilityRespObj.code == 200 && getAllUtilityRespObj.data){
				for(var idx = 0; idx < getAllUtilityRespObj.data.length; idx++){
					if(params.data.sfm_code_id == getAllUtilityRespObj.data[idx].sfm_code_id &&
					   this._isSameMonth(params.data.record_date, getAllUtilityRespObj.data[idx].record_date)){

						rObj.override = true;
						rObj.resp = {
							"code" : 400,
							"msg" : Strings.DUPLICATE_FOUND,
							"err_code" : 409 		//duplicate vendor
						};
						break;
					}
				}
			}else{
				rObj.override = true;
				rObj.resp = {
					"code" : 400,
					"msg" : Strings.CREATE_BCSSTEAM_UTILITY_ERROR
				}
			}
		}

		params.data = JSON.stringify(params.data);

		if (TenantCreateUtilityInterface && TenantCreateUtilityInterface.beforeData) {
			rObj = TenantCreateUtilityInterface.beforeData(params);
		}
		return rObj;
	},

	beforeExecute: function(queryParams) {
		//custom code here

		if (TenantCreateUtilityInterface && TenantCreateUtilityInterface.beforeExecute) {
			queryParams = TenantCreateUtilityInterface.beforeExecute(queryParams);
		}
		return queryParams;
	},


	afterData: function(createUtilityData) {


		if (TenantCreateUtilityInterface && TenantCreateUtilityInterface.afterData) {
			createUtilityData = TenantCreateUtilityInterface.afterData(createUtilityData);
		}
		return createUtilityData;
	},

	onError: function(errorObj) {


		if (TenantCreateUtilityInterface && TenantCreateUtilityInterface.onError) {
			errorObj = TenantCreateUtilityInterface.onError(errorObj);
		}
		return errorObj;
	},

	_isSameMonth: function (creatingDate, existingDate) {
		var date1 = new Date(Number(creatingDate));
		var date2 = new Date(Number(existingDate));

		return (
			date1.getFullYear() === date2.getFullYear() &&
			date1.getMonth() === date2.getMonth()
		);
	}





};