/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Jan 06 2026 15:52:33 GMT+0530 (India Standard Time)
	Description : Get All Service for utility
	WARNING : DO NOT MODIFY THIS FILE
*/

//External library
var dsclientUtil = require('dsclient');


//Internal library
var Strings = require("../common/strings.js");
var appcommon = require("../common/common.js");
var getAllUtilityInterface = require("getallinterface.js");

try {

  //Setting cache as null
  $g.response.headers["Cache-Control"] = "max-age=0";
  $g.response.headers["Cache-Control"] = "no-store";


  //Success response object
  var respObj = {
    code: 200,
    msg: Strings.READ_BCSSTEAM_UTILITY_GETALLUTILITY_SUCCESS
  };


  //Checking whether the request is in query or body
  var params = appcommon.processParams($g.request);
  var paramStr = JSON.stringify(params);

  //check for Language setup 
  if (params && params.l) {
    var filePath = "/common/lang/";
    appcommon.initLanguage(params.l, filePath);
  }


  // Call 'onLoad' method from the Interface with params as the argument
  var onLoadRes = null;
  if (getAllUtilityInterface)
    onLoadRes = getAllUtilityInterface.onLoad(params);

  // Check if 'onLoad' override is true
  if (onLoadRes && onLoadRes.override === true) {
    if (onLoadRes.resp) {
      if (onLoadRes.resp.code) {
        respObj = onLoadRes.resp;
      } else {
        respObj.code = 500;
        respObj.msg = Strings.SERVER_ERROR;
        if (getAllUtilityInterface)
          respObj = getAllUtilityInterface.onError(respObj);
        console.error("Unexpected server error when retrieving the utility - " + paramStr);
      }
    }
  } else {

    // Calling 'beforeData' method from Interface and passing params as argument
    var beforeDataRes = null;
    if (getAllUtilityInterface)
      beforeDataRes = getAllUtilityInterface.beforeData(params);

    // Check if 'override' is true
    if (beforeDataRes && beforeDataRes.override === true) {
      //Sending request to ds client
      if (beforeDataRes.resp) {
        if (beforeDataRes.resp.code) {
          respObj = beforeDataRes.resp;
        } else {
          respObj.code = 500;
          respObj.msg = Strings.SERVER_ERROR;
          if (getAllUtilityInterface)
            respObj = getAllUtilityInterface.onError(respObj);
        }
      }
    } else {
      if (beforeDataRes && beforeDataRes.params)
        params = beforeDataRes.params;


      if (getAllUtilityInterface) {
        params = getAllUtilityInterface.beforeExecute(params);
      }

      var countRespObj = null;

      var getAllUtilityQueryParams = {};


      //Setting offset and limit after count query
      if (params.offset)
        getAllUtilityQueryParams.offset = params.offset;

      if (params.limit)
        getAllUtilityQueryParams.limit = params.limit;

      if (params.offset || params.limit)
        countRespObj = dsclientUtil.execute(getAllUtilityQueryParams, "BCSSteam", "BCSSteam_utility", "count");

      //Sending request to ds client
      respObj = dsclientUtil.execute(params, "BCSSteam", "BCSSteam_utility", "getAll");

      if (countRespObj)
        respObj.count = ((countRespObj.code == 200) && (countRespObj.data) && (countRespObj.data.count)) ? countRespObj.data.count : -1;
    }


    switch (respObj.code) {
      case 200:
        if (getAllUtilityInterface)
          respObj.data = getAllUtilityInterface.afterData(respObj.data);
        respObj.msg = Strings.READ_BCSSTEAM_UTILITIES_GETALLUTILITY_SUCCESS;
        break;
      case 400:
        respObj.msg = Strings.READ_BCSSTEAM_UTILITIES_GETALLUTILITY_ERROR;
        if (getAllUtilityInterface)
          respObj = getAllUtilityInterface.onError(respObj);
        console.error("Unable to retrieve the utility - " + paramStr);
        break;
      case 403:
        respObj.msg = Strings.ACCESS_DENIED;
        if (getAllUtilityInterface)
          respObj = getAllUtilityInterface.onError(respObj);
        console.error("User access denied when retrieving the utility - " + paramStr);
        break;
      case 500:
        respObj.msg = Strings.SERVER_ERROR;
        if (getAllUtilityInterface)
          respObj = getAllUtilityInterface.onError(respObj);
        console.error("Unexpected server error when retrieving the utility - " + paramStr);
        break;
    }

  }


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = respObj.code;
  $g.response.body = JSON.stringify(respObj);

} catch (e) {

  //Error response object
  var errorRespObj = {
    status: 500,
    message: Strings.SERVER_ERROR + " - " + e.message,
    stack: e.stack
  };
  if (getAllUtilityInterface)
    errorRespObj = getAllUtilityInterface.onError(errorRespObj);
  console.error("Unexpected server error when retrieving the utility - " + paramStr + "-" + errorRespObj.message);


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = errorRespObj.status;
  $g.response.body = JSON.stringify(errorRespObj);

}