/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Jan 27 2026 15:23:06 GMT+0530 (India Standard Time)
	Description : Query Service Interface for loss
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetLossByFilterInterface = app.getTenantWSInterface('BCSFuel', 'loss/getbyfilter');

if (typeof TenantGetLossByFilterInterface === 'undefined')
  TenantGetLossByFilterInterface = {};


module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };

    if (TenantGetLossByFilterInterface && TenantGetLossByFilterInterface.onLoad) {
      rObj = TenantGetLossByFilterInterface.onLoad(params);
    }

    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetLossByFilterInterface && TenantGetLossByFilterInterface.beforeData) {
      rObj = TenantGetLossByFilterInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams) {
    //custom code here

    if (TenantGetLossByFilterInterface && TenantGetLossByFilterInterface.beforeExecute) {
      queryParams = TenantGetLossByFilterInterface.beforeExecute(queryParams);
    }
    return queryParams;
  },


  afterData: function(getLossByFilterData) {


    if (TenantGetLossByFilterInterface && TenantGetLossByFilterInterface.afterData) {
      getLossByFilterData = TenantGetLossByFilterInterface.afterData(getLossByFilterData);
    }
    return getLossByFilterData;
  },

  onError: function(errorObj) {

    if (TenantGetLossByFilterInterface && TenantGetLossByFilterInterface.onError) {
      errorObj = TenantGetLossByFilterInterface.onError(errorObj);
    }
    return errorObj;
  }
};