/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Jan 27 2026 15:18:57 GMT+0530 (India Standard Time)
	Description : Update Service Interface for loss
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantUpdateLossDataInterface = app.getTenantWSInterface('BCSFuel', 'loss/update');

if (typeof TenantUpdateLossDataInterface === 'undefined')
	TenantUpdateLossDataInterface = {};

module.exports = {
	onLoad: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};

		if (TenantUpdateLossDataInterface && TenantUpdateLossDataInterface.onLoad) {
			rObj = TenantUpdateLossDataInterface.onLoad(params);
		}

		return rObj;
	},

	beforeData: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};

		if (params && params.data){
			try{
				params.data = JSON.parse(params.data);
			}catch(e){
				params.data = params.data;
			}

			var getAllLossRespObj = dsclientUtil.execute({}, "BCSFuel", "bcsfuel_loss", "getAll");

			if(getAllLossRespObj.code == 200 && getAllLossRespObj.data){
				for(var idx = 0; idx < getAllLossRespObj.data.length; idx++){
					if(params.data.fuel_code_id == getAllLossRespObj.data[idx].fuel_code_id  &&
					   (params.data._sid != getAllLossRespObj.data[idx]._sid) &&
					   this._isSameMonth(params.data.record_date, getAllLossRespObj.data[idx].record_date)){

						rObj.override = true;
						rObj.resp = {
							"code" : 400,
							"msg" : Strings.DUPLICATE_FOUND,
							"err_code" : 409 		//duplicate purchase
						};
						break;
					}
				}
			}else{
				rObj.override = true;
				rObj.resp = {
					"code" : 400,
					"msg" : Strings.CREATE_BCSFUEL_LOSS_ERROR
				}
			}
		}

		params.data = JSON.stringify(params.data);

		if (TenantUpdateLossDataInterface && TenantUpdateLossDataInterface.beforeData) {
			rObj = TenantUpdateLossDataInterface.beforeData(params);
		}

		return rObj;
	},

	beforeExecute: function(queryParams) {
		//custom code here

		if (TenantUpdateLossDataInterface && TenantUpdateLossDataInterface.beforeExecute) {
			queryParams = TenantUpdateLossDataInterface.beforeExecute(queryParams);
		}
		return queryParams;
	},

	afterData: function(updateLossDataData) {


		if (TenantUpdateLossDataInterface && TenantUpdateLossDataInterface.afterData) {
			updateLossDataData = TenantUpdateLossDataInterface.afterData(updateLossDataData);
		}
		return updateLossDataData;
	},

	onError: function(errorObj) {

		if (TenantUpdateLossDataInterface && TenantUpdateLossDataInterface.onError) {
			errorObj = TenantUpdateLossDataInterface.onError(errorObj);
		}
		return errorObj;
	},
	_isSameMonth: function (creatingDate, existingDate) {
		var date1 = new Date(Number(creatingDate));
		var date2 = new Date(Number(existingDate));

		return (
			date1.getFullYear() === date2.getFullYear() &&
			date1.getMonth() === date2.getMonth()
		);
	}
};