/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Jan 27 2026 13:20:01 GMT+0530 (India Standard Time)
	Description : Create Service Interface for purchase
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantCreatePurchaseDataInterface = app.getTenantWSInterface('BCSFuel', 'purchase/create');

if (typeof TenantCreatePurchaseDataInterface === 'undefined')
	TenantCreatePurchaseDataInterface = {};


module.exports = {
	onLoad: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};


		if (TenantCreatePurchaseDataInterface && TenantCreatePurchaseDataInterface.onLoad) {
			rObj = TenantCreatePurchaseDataInterface.onLoad(params);
		}
		return rObj;
	},

	beforeData: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};

		if (params && params.data){
			try{
				params.data = JSON.parse(params.data);
			}catch(e){
				params.data = params.data;
			}

			var getAllpurchaseRespObj = dsclientUtil.execute({}, "BCSFuel", "bcsfuel_purchase", "getAll");

			if(getAllpurchaseRespObj.code == 200 && getAllpurchaseRespObj.data){
				for(var idx = 0; idx < getAllpurchaseRespObj.data.length; idx++){
					if(params.data.fuel_code_id == getAllpurchaseRespObj.data[idx].fuel_code_id  &&
					   this._isSameMonth(params.data.purchase_date, getAllpurchaseRespObj.data[idx].purchase_date)){

						rObj.override = true;
						rObj.resp = {
							"code" : 400,
							"msg" : Strings.DUPLICATE_FOUND,
							"err_code" : 409 		//duplicate purchase
						};
						break;
					}
				}
			}else{
				rObj.override = true;
				rObj.resp = {
					"code" : 400,
					"msg" : Strings.CREATE_BCSFUEL_PURCHASE_ERROR
				}
			}
		}

		params.data = JSON.stringify(params.data);


		if (TenantCreatePurchaseDataInterface && TenantCreatePurchaseDataInterface.beforeData) {
			rObj = TenantCreatePurchaseDataInterface.beforeData(params);
		}
		return rObj;
	},

	beforeExecute: function(queryParams) {
		//custom code here

		if (TenantCreatePurchaseDataInterface && TenantCreatePurchaseDataInterface.beforeExecute) {
			queryParams = TenantCreatePurchaseDataInterface.beforeExecute(queryParams);
		}
		return queryParams;
	},


	afterData: function(createPurchaseDataData) {


		if (TenantCreatePurchaseDataInterface && TenantCreatePurchaseDataInterface.afterData) {
			createPurchaseDataData = TenantCreatePurchaseDataInterface.afterData(createPurchaseDataData);
		}
		return createPurchaseDataData;
	},

	onError: function(errorObj) {


		if (TenantCreatePurchaseDataInterface && TenantCreatePurchaseDataInterface.onError) {
			errorObj = TenantCreatePurchaseDataInterface.onError(errorObj);
		}
		return errorObj;
	},

	_isSameMonth: function (creatingDate, existingDate) {
		var date1 = new Date(Number(creatingDate));
		var date2 = new Date(Number(existingDate));

		return (
			date1.getFullYear() === date2.getFullYear() &&
			date1.getMonth() === date2.getMonth()
		);
	}
};