/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 12 2026 13:28:10 GMT+0530 (India Standard Time)
	Description : Interface Logic for BCSSteam List Details.
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS.
	Custom code can be writter here.
	Use customDtOpns object to maniuplate data table.
*/

if (typeof TenantSteamFlowMeterInterface === 'undefined')
	TenantSteamFlowMeterInterface = {};

var SteamFlowMeterInterface = {
	onLoad: function() {
		//Custom code goes here
		document.querySelector("title").innerHTML = "BCS Steam";
		document.querySelector("span").innerHTML = "BCS Steam";
		document.querySelector("#steamFlowMeterSfm_descriptionForTour label").innerHTML = "Description*";



		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onLoad)
			return TenantSteamFlowMeterInterface.onLoad();

		return true;
	},

	onBeforeLoad: function(dataSources) {

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onBeforeLoad)
			return TenantSteamFlowMeterInterface.onBeforeLoad();

		return dataSources;
	},

	onAfterLoad: function(dataSources) {
		clCommon.hide(vendor_idAddBtn);
		clCommon.hide(working_principle_idAddBtn);
		clCommon.hide(size_idAddBtn);
		clCommon.hide(input_power_idAddBtn);
		clCommon.hide(output_signal_idAddBtn);
		clCommon.hide(filterSteamFlowMeterBtn);
		clCommon.hide(document.getElementById("nav-action-tab"));


		if (formView.classList.contains("hide")) {
			if (clCommon.isMobile()) {
				clCommon.show(document.getElementById("nav-action-tab"));
				clCommon.show(filterActionsSteamFlowMeterBtn);
			}
		}



		if(dataSources.getAllBusinessPartner){
			for(var idx = 0; idx < dataSources.getAllBusinessPartner.length; idx++){
				try{
					dataSources.getAllBusinessPartner[idx].name = scrypto.decrypt(dataSources.getAllBusinessPartner[idx].name);
				}catch(e){
					dataSources.getAllBusinessPartner[idx].name = dataSources.getAllBusinessPartner[idx].name;
				}
			}
		}

		var vendors = dataSources.getAllVendorsWithoutLimit;
		var partners = dataSources.getAllBusinessPartner;

		for (var venIdx = 0; venIdx < vendors.length; venIdx++) {
			var vendor = vendors[venIdx];

			if (vendor.business_partner_id) {
				for (var patIdx = 0; patIdx < partners.length; patIdx++) {

					if (partners[patIdx]._sid === vendor.business_partner_id) {
						var name = partners[patIdx].name;

						if (vendor.isactive === false) {
							name += " - Inactive";
						}

						vendor.name = name;
						break;
					}
				}
			}
		}


		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onAfterLoad)
			return TenantSteamFlowMeterInterface.onAfterLoad(dataSources);

		return dataSources;
	},

	onBeforeData: function(params, dataSources) {

		//Custom code goes here



		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onBeforeData)
			return TenantSteamFlowMeterInterface.onBeforeData(params, dataSources);

		return true;
	},

	onAfterData: function(isSuccessful, dataArr, dataSources) {
		//custom code goes here

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onAfterData)
			return TenantSteamFlowMeterInterface.onAfterData(isSuccessful, dataArr, dataSources);

		return dataArr;
	},

	renderData: function(value, type, dtObj, meta) {
		//custom code goes here
		var rVal;
		switch(meta.col){
			case 1 :
				rVal = this._getVendorName(value);
				break;

			case 2 :
				if(value == true){
					rVal = Strings.YES_STRING;
				}else{
					rVal = Strings.NO_STRING;
				}
				break;

			case 3 :
				if(value == true){
					rVal = Strings.YES_STRING;
				}else{
					rVal = Strings.NO_STRING;
				}
				break;

			case 4:
				rVal = Strings.FALSE_STRING;

				if(dtObj.isactive){
					rVal = Strings.TRUE_STRING;
				}
				break;
		} 

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.renderData)
			return TenantSteamFlowMeterInterface.renderData(value, type, dtObj, meta);

		return rVal;
	},

	onBeforeCreate: function(dataObj, dataSources) {
		//custom code here

		if (dataObj && dataObj.sfm_code) {
			var value = dataObj.sfm_code;

			if (value.length > 20) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE,Strings.INVALID_SFM_CODE_LENGTH,dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfm_description) {
			var desc = dataObj.sfm_description;

			if (desc.length > 50) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_SFM_DESCRIPTION_LENGTH, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.vendor_id) {
			for(var idx = 0; idx < dataSources.getAllVendorsWithoutLimit.length; idx++){
				if(dataObj.vendor_id == dataSources.getAllVendorsWithoutLimit[idx]._sid && (dataSources.getAllVendorsWithoutLimit[idx].isactive == false || dataSources.getAllVendorsWithoutLimit[idx].isactive == null)){
					s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INACTIVE_VENDOR, dlgOptions);
					return false;
				}
			}
		}

		if (dataObj && dataObj.model_no) {
			var model = dataObj.model_no;

			if (model.length > 20) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_MODEL_NO_LENGTH, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.serial_no) {
			var serial = dataObj.serial_no;

			if (serial.length > 20) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_SERIAL_NO_LENGTH, dlgOptions);
				return false;
			}
		}


		if (dataObj && dataObj.year_of_manufacturing) {
			const year = dataObj.year_of_manufacturing;

			if (!/^\d{4}$/.test(year)) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_YEAR_OF_MANUFACTURING,dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.flow_rate_min) {
			const value = dataObj.flow_rate_min.toString();
			const flowRateRegex = /^\d{1,4}(\.\d{1,3})?$/;

			if (!flowRateRegex.test(value)) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE,Strings.INVALID_FLOW_RATE_MIN,dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.flow_rate_max) {
			const value = dataObj.flow_rate_max.toString();
			const flowRateRegex = /^\d{1,4}(\.\d{1,3})?$/;

			if (!flowRateRegex.test(value)) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE,Strings.INVALID_FLOW_RATE_MAX,dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.connected_tnpcb === true) {
			if(!dataObj.tnpcb_ref || dataObj.tnpcb_ref == ""){
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.TNPCB_REF_REQUIRED, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.connected_cpcb === true) {
			if(!dataObj.cpcb_ref || dataObj.cpcb_ref == ""){
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.CPCB_REF_REQUIRED, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.tnpcb_ref) {
			var value = dataObj.tnpcb_ref;

			if (value.length > 10) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_TNPCB_REF_LENGTH, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.cpcb_ref) {
			var value = dataObj.cpcb_ref;

			if (value.length > 10) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_CPCB_REF_LENGTH, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.remarks) {
			var value = dataObj.remarks;

			if (value.length > 100) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_REMARKS_LENGTH, dlgOptions);
				return false;
			}
		}



		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onBeforeCreate)
			return TenantSteamFlowMeterInterface.onBeforeCreate(dataObj, dataSources);

		return dataObj;
	},

	onAfterCreate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here
		if(dataObj.err_code && dataObj.err_code === 409){
			clCommon.hideLoader("createProgress");
			clCommon.enable(createSteamFlowMeterBtn);
			s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.DUPLICATE_SFM_ID, dlgOptions);

			return false;
		}


		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onAfterCreate)
			return TenantSteamFlowMeterInterface.onAfterCreate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeUpdate: function(dataObj, dataSources) {
		//custom code here

		if (dataObj && dataObj.sfm_code) {
			var value = dataObj.sfm_code;

			if (value.length > 20) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE,Strings.INVALID_SFM_CODE_LENGTH,dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfm_description) {
			var desc = dataObj.sfm_description;

			if (desc.length > 50) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_SFM_DESCRIPTION_LENGTH, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.vendor_id) {
			for(var idx = 0; idx < dataSources.getAllVendorsWithoutLimit.length; idx++){
				if(dataObj.vendor_id == dataSources.getAllVendorsWithoutLimit[idx]._sid && (dataSources.getAllVendorsWithoutLimit[idx].isactive == false || dataSources.getAllVendorsWithoutLimit[idx].isactive == null)){
					s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INACTIVE_VENDOR, dlgOptions);
					return false;
				}
			}
		}

		if (dataObj && dataObj.model_no) {
			var model = dataObj.model_no;

			if (model.length > 20) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_MODEL_NO_LENGTH, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.serial_no) {
			var serial = dataObj.serial_no;

			if (serial.length > 20) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_SERIAL_NO_LENGTH, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.year_of_manufacturing) {
			const year = dataObj.year_of_manufacturing;

			if (!/^\d{4}$/.test(year)) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_YEAR_OF_MANUFACTURING,dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.connected_tnpcb === true) {
			if(!dataObj.tnpcb_ref || dataObj.tnpcb_ref == ""){
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.TNPCB_REF_REQUIRED, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.connected_cpcb === true) {
			if(!dataObj.cpcb_ref || dataObj.cpcb_ref == ""){
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.CPCB_REF_REQUIRED, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.tnpcb_ref) {
			var value = dataObj.tnpcb_ref;

			if (value.length > 10) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_TNPCB_REF_LENGTH, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.cpcb_ref) {
			var value = dataObj.cpcb_ref;

			if (value.length > 10) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_CPCB_REF_LENGTH, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.remarks) {
			var value = dataObj.remarks;

			if (value.length > 100) {
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.INVALID_REMARKS_LENGTH, dlgOptions);
				return false;
			}
		}


		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onBeforeUpdate)
			return TenantSteamFlowMeterInterface.onBeforeUpdate(dataObj, dataSources);

		return dataObj;
	},

	onAfterUpdate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here

		if(dataObj.err_code && dataObj.err_code === 409){
			clCommon.hideLoader("updateProgress");
			clCommon.enable(editSteamFlowMeterBtn);
			s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.DUPLICATE_SFM_ID, dlgOptions);

			return false;
		}

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onAfterUpdate)
			return TenantSteamFlowMeterInterface.onAfterUpdate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeDelete: function(dataObj, dataSources) {
		//custom code here


		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onBeforeDelete)
			return TenantSteamFlowMeterInterface.onBeforeDelete(dataObj, dataSources);

		return dataObj;
	},

	onAfterDelete: function(isSuccessful, resultObj, dataSources) {
		//Custom code here
		if(resultObj.data && resultObj.data.err_code === 422){
			clCommon.hideLoader("removeProgress");
			s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.FOREIGN_REFERENCE_EXIST_ON_UTILITY, dlgOptions);

			return false;
		}


		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onAfterDelete)
			return TenantSteamFlowMeterInterface.onAfterDelete(isSuccessful, resultObj, dataSources);

		return resultObj;
	},

	onChangeFilter: function(changedFilter) {
		//Custom code here

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onChangeFilter)
			return TenantSteamFlowMeterInterface.onChangeFilter(changedFilter);

		return true;
	},

	onSearchChangeFilter: function(searchedFilter) {

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onSearchChangeFilter)
			return TenantSteamFlowMeterInterface.onSearchChangeFilter(searchedFilter);

		return true;
	},

	onRowItemClick: function(rowData) {
		//Custom code here
		if (clCommon.isMobile()) {
			clCommon.hide(filterActionsSteamFlowMeterBtn);
		} 

		if (rowData.connected_tnpcb === false) {
			steamFlowMeterTnpcb_ref.value = '';
			clCommon.hide(document.getElementById("steamFlowMeterTnpcb_refForTour"));
		}else{
			clCommon.show(document.getElementById("steamFlowMeterTnpcb_refForTour"));
		}

		if (rowData.connected_cpcb === false) {
			steamFlowMeterCpcb_ref.value = '';
			clCommon.hide(document.getElementById("steamFlowMeterCpcb_refForTour"));
		}else{
			clCommon.show(document.getElementById("steamFlowMeterCpcb_refForTour"));
		}


		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onRowItemClick)
			return TenantSteamFlowMeterInterface.onRowItemClick(rowData);

		return rowData;
	},

	onDisplayForm: function(rowData) {
		//Custom code here

		if(rowData.vendor_id == ""){
			steamFlowMeterVendor_id.value = ""
		}

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onDisplayForm)
			return TenantSteamFlowMeterInterface.onDisplayForm(rowData);

		return rowData;
	},

	onClearForm: function(defaultObj, dataSources) {
		//Custom code here
		defaultObj.isactive = true;

		if (defaultObj.connected_tnpcb === false) {
			steamFlowMeterTnpcb_ref.value = '';
			clCommon.hide(document.getElementById("steamFlowMeterTnpcb_refForTour"));
		}else{
			clCommon.show(document.getElementById("steamFlowMeterTnpcb_refForTour"));
		}

		if (defaultObj.connected_cpcb === false) {
			steamFlowMeterCpcb_ref.value = '';
			clCommon.hide(document.getElementById("steamFlowMeterCpcb_refForTour"));
		}else{
			clCommon.show(document.getElementById("steamFlowMeterCpcb_refForTour"));
		}


		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onClearForm)
			return TenantSteamFlowMeterInterface.onClearForm(defaultObj, dataSources);

		return defaultObj;
	},

	onFieldFocus: function(focusedField, dataSources) {

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onFieldFocus)
			return TenantSteamFlowMeterInterface.onFieldFocus(focusedField, dataSources);

	},


	onFieldChange: function(changedField, dataSources) {

		if(changedField.id == "steamFlowMeterVendor_id" && rowData && rowData.vendor_id){
			/*for(var idx = 0; idx < dataSources.getAllVendorsWithoutLimit.length; idx++){
				if(rowData.vendor_id == dataSources.getAllVendorsWithoutLimit[idx]._sid){
					steamFlowMeterVendor_id.value = dataSources.getAllVendorsWithoutLimit[idx].name;
					break;
				}
			}*/
			steamFlowMeterVendor_id.value = changedField.value;
		}

		if (changedField.id === "steamFlowMeterYear_of_manufacturing") {
			let tempValue = steamFlowMeterYear_of_manufacturing.value;

			if (tempValue) {
				tempValue = tempValue.replace(/,/g, '').split('.')[0].replace(/[^0-9]/g, '');

				steamFlowMeterYear_of_manufacturing.value = tempValue;
			}
		}

		if (changedField.id === "steamFlowMeterConnected_tnpcb") {
			if(steamFlowMeterConnected_tnpcb.checked == false){
				steamFlowMeterTnpcb_ref.value = '';
				clCommon.hide(document.getElementById("steamFlowMeterTnpcb_refForTour"));
			}else{
				clCommon.show(document.getElementById("steamFlowMeterTnpcb_refForTour"));
			}

		}
		if(changedField.id === "steamFlowMeterConnected_cpcb"){
			if (steamFlowMeterConnected_cpcb.checked === false) {
				steamFlowMeterCpcb_ref.value = '';
				clCommon.hide(document.getElementById("steamFlowMeterCpcb_refForTour"));
			}else{
				clCommon.show(document.getElementById("steamFlowMeterCpcb_refForTour"));
			}
		}




		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onFieldChange)
			return TenantSteamFlowMeterInterface.onFieldChange(changedField, dataSources);

	},

	onToolBarBtnClick: function(changedField, dataSources) {

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onToolBarBtnClick)
			return TenantSteamFlowMeterInterface.onToolBarBtnClick(changedField, dataSources);

	},

	onLookupAddBtnClick: function(attribute, changedField, dataSources) {

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onLookupAddBtnClick)
			return TenantSteamFlowMeterInterface.onLookupAddBtnClick(attribute, changedField, dataSources);

	},

	onLookUpData: function(attribute, dataSources) {

		switch (attribute) {
			case "vendor_id":
				var vendorArr = [];
				var vendor_idFlg = false;
				var pushState = (typeof e !== 'undefined' && e !== false);

				var objective = {
					"_sid": steamFlowMeterVendor_id.getAttribute("Vendor_id")
				};

				var vendors = dataSources.getAllVendorsWithoutLimit;
				var partners = dataSources.getAllBusinessPartner;

				for (var venIdx = 0; venIdx < vendors.length; venIdx++) {
					var vendor = vendors[venIdx];

					if (vendor.business_partner_id) {
						var foundPartner = false;

						for (var patIdx = 0; patIdx < partners.length; patIdx++) {
							if (partners[patIdx]._sid === vendor.business_partner_id) {
								var name = vendor.name;
								if (vendor.isactive === false && !name.endsWith(" - Inactive")) {
									name += " - Inactive";
									vendor.name = name;
								}

								foundPartner = true;
								break;
							}
						}

						if (foundPartner) {
							var checked = "";
							if (objective._sid && objective._sid == vendor._sid) {
								checked = "checked";
								vendor_idFlg = true;
							} else if (rowData && rowData.vendor_id == vendor._sid && !vendor_idFlg) {
								checked = "checked";
							}

							vendorArr.push({
								"vendor_idName": '<label for="' + vendor._sid + '">' + vendor.name + '</label>',
								"radio": '<input type="radio" name="vendor_idName" vendor_idId="' + vendor._sid + '" vendor_idName="' + JSON.stringify(vendor).replaceAll('"', '$' + 'DQUOTE' + '$') + '" ' + checked + '>'
							});



						}
					}
				}

				vendor_idTable.clear().draw();
				vendor_idTable.rows.add(vendorArr).draw();

				if (clCommon.isMobile() && pushState) {
					window.history.pushState('vendor_idForm', null, '#vendor_idsForm');
					clCommon.hide(contentView);
				}

				return false;
		}

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onLookUpData)
			return TenantSteamFlowMeterInterface.onLookUpData(attribute, dataSources);

		return true;
	},

	onChangeOfActionSelect: function(changedAction, dataSources) {

		switch (changedAction.value) {}

		if (TenantSteamFlowMeterInterface && TenantSteamFlowMeterInterface.onChangeOfActionSelect)
			return TenantSteamFlowMeterInterface.onChangeOfActionSelect(changedAction, dataSources);

		return true;
	},
	_getVendorName: function(value){
		for(var vendorIdx = 0; vendorIdx < dataSources.getAllVendorsWithoutLimit.length; vendorIdx++){
			var vendorObj = dataSources.getAllVendorsWithoutLimit[vendorIdx];
			if(value == vendorObj._sid){
				value = vendorObj.name;
				rVal = value
				break;
			}else{
				rVal = Strings.NA_STRING;

			}
		}
		return rVal;
	}

};