/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Jan 06 2026 15:06:49 GMT+0530 (India Standard Time)
	Description : Interface Logic for BCSSteam List Details.
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS.
	Custom code can be writter here.
	Use customDtOpns object to maniuplate data table.
*/

if (typeof TenantVendorInterface === 'undefined')
	TenantVendorInterface = {};

var VendorInterface = {
	onLoad: function() {
		//Custom code goes here
		document.querySelector("title").innerHTML = "BCS Steam";
		document.querySelector("span").innerHTML = "BCS Steam";



		if (TenantVendorInterface && TenantVendorInterface.onLoad)
			return TenantVendorInterface.onLoad();

		return true;
	},

	onBeforeLoad: function(dataSources) {


		if (TenantVendorInterface && TenantVendorInterface.onBeforeLoad)
			return TenantVendorInterface.onBeforeLoad();

		return dataSources;
	},

	onAfterLoad: function(dataSources) {
		clCommon.hide(business_partner_idAddBtn);


		if (TenantVendorInterface && TenantVendorInterface.onAfterLoad)
			return TenantVendorInterface.onAfterLoad(dataSources);

		return dataSources;
	},

	onBeforeData: function(params, dataSources) {



		//Custom code goes here
		clCommon.hide(filterVendorBtn);


		if (TenantVendorInterface && TenantVendorInterface.onBeforeData)
			return TenantVendorInterface.onBeforeData(params, dataSources);

		return true;
	},

	onAfterData: function(isSuccessful, dataArr, dataSources) {
		//custom code goes here

		if (TenantVendorInterface && TenantVendorInterface.onAfterData)
			return TenantVendorInterface.onAfterData(isSuccessful, dataArr, dataSources);

		return dataArr;
	},

	renderData: function(value, type, dtObj, meta) {
		//custom code goes here
		var rVal;
		// Create a fast-lookup object where the key is the budget ID (_sid)

		switch(meta.col){
			case 0:
				rVal = this._getVendorName(value);
				break;

			case 1:
				rVal = Strings.FALSE_STRING;

				if(dtObj.isactive){
					rVal = Strings.TRUE_STRING;
				}
				break;
		}

		if (TenantVendorInterface && TenantVendorInterface.renderData)
			return TenantVendorInterface.renderData(value, type, dtObj, meta);

		return rVal;
	},

	onBeforeCreate: function(dataObj, dataSources) {
		//custom code here


		if (TenantVendorInterface && TenantVendorInterface.onBeforeCreate)
			return TenantVendorInterface.onBeforeCreate(dataObj, dataSources);

		return dataObj;
	},

	onAfterCreate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here
		if(dataObj.err_code === 409){
			clCommon.hideLoader("createProgress");
			clCommon.enable(createVendorBtn);
			s_info(Strings.VENDOR_ERROR_TITLE, Strings.DUPLICATE_VENDOR, dlgOptions);

			return false;
		}


		if (TenantVendorInterface && TenantVendorInterface.onAfterCreate)
			return TenantVendorInterface.onAfterCreate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeUpdate: function(dataObj, dataSources) {
		//custom code here


		if (TenantVendorInterface && TenantVendorInterface.onBeforeUpdate)
			return TenantVendorInterface.onBeforeUpdate(dataObj, dataSources);

		return dataObj;
	},

	onAfterUpdate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here
		if(dataObj.err_code === 409){
			clCommon.hideLoader("updateProgress");
			clCommon.enable(editVendorBtn);
			s_info(Strings.VENDOR_ERROR_TITLE, Strings.DUPLICATE_VENDOR, dlgOptions);

			return false;
		}

		if (TenantVendorInterface && TenantVendorInterface.onAfterUpdate)
			return TenantVendorInterface.onAfterUpdate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeDelete: function(dataObj, dataSources) {
		//custom code here


		if (TenantVendorInterface && TenantVendorInterface.onBeforeDelete)
			return TenantVendorInterface.onBeforeDelete(dataObj, dataSources);

		return dataObj;
	},

	onAfterDelete: function(isSuccessful, resultObj, dataSources) {
		//Custom code here
		if(resultObj.data && resultObj.data.err_code === 422){
			clCommon.hideLoader("removeProgress");
			s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.FOREIGN_REFERENCE_EXIST_ON_SFM, dlgOptions);

			return false;
		}


		if (TenantVendorInterface && TenantVendorInterface.onAfterDelete)
			return TenantVendorInterface.onAfterDelete(isSuccessful, resultObj, dataSources);

		return resultObj;
	},

	onChangeFilter: function(changedFilter) {
		//Custom code here

		if (TenantVendorInterface && TenantVendorInterface.onChangeFilter)
			return TenantVendorInterface.onChangeFilter(changedFilter);

		return true;
	},

	onSearchChangeFilter: function(searchedFilter) {

		if (TenantVendorInterface && TenantVendorInterface.onSearchChangeFilter)
			return TenantVendorInterface.onSearchChangeFilter(searchedFilter);

		return true;
	},

	onRowItemClick: function(rowData) {
		//Custom code here
		if(rowData.business_partner_id){
			for(var idx = 0; idx < dataSources.getAllBusinessPartner.length; idx++){
				if(rowData.business_partner_id == dataSources.getAllBusinessPartner[idx]._sid){
					rowData.business_partner_name = dataSources.getAllBusinessPartner[idx].name;
				}
			}
		}

		if (TenantVendorInterface && TenantVendorInterface.onRowItemClick)
			return TenantVendorInterface.onRowItemClick(rowData);

		return rowData;
	},

	onDisplayForm: function(rowData) {
		//Custom code here


		if (TenantVendorInterface && TenantVendorInterface.onDisplayForm)
			return TenantVendorInterface.onDisplayForm(rowData);

		return rowData;
	},

	onClearForm: function(defaultObj, dataSources) {
		//Custom code here
		//vendorIsactive.checked = true;
		defaultObj.isactive = true;

		if (TenantVendorInterface && TenantVendorInterface.onClearForm)
			return TenantVendorInterface.onClearForm(defaultObj, dataSources);

		return defaultObj;
	},

	onFieldFocus: function(focusedField, dataSources) {

		if (TenantVendorInterface && TenantVendorInterface.onFieldFocus)
			return TenantVendorInterface.onFieldFocus(focusedField, dataSources);

	},


	onFieldChange: function(changedField, dataSources) {

		if (TenantVendorInterface && TenantVendorInterface.onFieldChange)
			return TenantVendorInterface.onFieldChange(changedField, dataSources);

	},

	onToolBarBtnClick: function(changedField, dataSources) {

		if (TenantVendorInterface && TenantVendorInterface.onToolBarBtnClick)
			return TenantVendorInterface.onToolBarBtnClick(changedField, dataSources);

	},

	onLookupAddBtnClick: function(attribute, changedField, dataSources) {

		if (TenantVendorInterface && TenantVendorInterface.onLookupAddBtnClick)
			return TenantVendorInterface.onLookupAddBtnClick(attribute, changedField, dataSources);

	},

	onLookUpData: function(attribute, dataSources) {

		if (TenantVendorInterface && TenantVendorInterface.onLookUpData)
			return TenantVendorInterface.onLookUpData(attribute, dataSources);

		return true;

	},

	onChangeOfActionSelect: function(changedAction, dataSources) {

		switch (changedAction.value) {}

		if (TenantVendorInterface && TenantVendorInterface.onChangeOfActionSelect)
			return TenantVendorInterface.onChangeOfActionSelect(changedAction, dataSources);

		return true;
	},
	_getVendorName : function(value){
		for(var customerIdx = 0; customerIdx < dataSources.getAllBusinessPartner.length; customerIdx++){
			var customerObj = dataSources.getAllBusinessPartner[customerIdx];
			if(value == customerObj._sid){
				value = customerObj.name;
				rVal = value
				break;
			}else{
				rVal = Strings.NA_STRING;

			}
		}
		return rVal;
	},

};