/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Wed Jan 07 2026 15:06:46 GMT+0530 (India Standard Time)
	Description : Combine Master Ui Interface for workingPrinciple
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

if (typeof TenantWorkingPrincipleInterface === 'undefined')
	TenantWorkingPrincipleInterface = {};

var WorkingPrincipleInterface = {
	loaded : false,
	onLoad: function() {

		document.querySelector("title").innerHTML = "BCS Steam";
		document.querySelector("span").innerHTML = "BCS Steam";

		if (TenantWorkingPrincipleInterface && TenantWorkingPrincipleInterface.onLoad)
			return TenantWorkingPrincipleInterface.onLoad();

	},

	onBeforeLoad: function() {
		//Custom code goes here


		if (TenantWorkingPrincipleInterface && TenantWorkingPrincipleInterface.onBeforeLoad)
			return TenantWorkingPrincipleInterface.onBeforeLoad();
		return true;
	},

	onAfterLoad: function(isSuccessful, dataArr) {
		//custom code goes here
		WorkingPrincipleInterface.loaded = true;


		if (TenantWorkingPrincipleInterface && TenantWorkingPrincipleInterface.onAfterLoad)
			return TenantWorkingPrincipleInterface.onAfterLoad(isSuccessful, dataArr);
		return dataArr;
	},

	onBeforeData: function(svcName, params) {
		//custom code goes here

		if (TenantWorkingPrincipleInterface && TenantWorkingPrincipleInterface.onBeforeData)
			return TenantWorkingPrincipleInterface.onBeforeData(svcName, params);
		return params;
	},

	onAfterData: function(svcName, dataSources) {
		//custom code goes here

		if (TenantWorkingPrincipleInterface && TenantWorkingPrincipleInterface.onAfterData)
			return TenantWorkingPrincipleInterface.onAfterData(svcName, dataSources);
		return dataSources;
	},

	onBeforeSave: function(dataObj) {
		//custom code here

		// check duplicate working principle
		if (dataObj.master_data.length !== 0) {

			const sheetData = editorSheet.getData();
			let invalidDescRows = [];
			let invalidWpRows = [];


			for (let row = 0; row < sheetData.length; row++) {

				const workingPrinciple = sheetData[row][1];		
				const description = sheetData[row][2];       


				// remove description if id or value is not available
				const col0Empty = !sheetData[row][0] || sheetData[row][0].trim() === "";
				const col1Empty = !sheetData[row][1] || sheetData[row][1].trim() === "";

				if (col0Empty && col1Empty) {
					editorSheet.setValueFromCoords(2, row, "");
				}

				if (description && description.length > 50) {
					invalidDescRows.push(row + 1); 
				}

				if (workingPrinciple && workingPrinciple.length > 30) {
					invalidWpRows.push(row + 1);
				}
			}

			var duplicates = common_util.checkDuplicate(sheetData, editorSheet);
			duplicates = duplicates.duplicates;

			if (duplicates.size > 0) {

				let alertText = '<p>' + Strings.DUPLICATE_WORKING_PRINCIPLE_ERROR_1 + '</p>';
				alertText += '<ol class="wp_prompt_error">';

				duplicates.forEach((rows, wp) => {
					alertText += '<li>' + 	"'"+wp+"'" + ' ' + Strings.DUPLICATE_WORKING_PRINCIPLE_ERROR_2 + ' ' + rows.join(", ") + '</li>';
				});

				alertText += '</ol>';

				s_info( Strings.VALIDATION_ERROR_TITLE, alertText, dlgOptions );
				return false;
			}

			if (invalidDescRows.length > 0) {
				let alertText = '<p>' + Strings.WORKING_PRINCIPLE_DESC_VALIDATION_ERR;
				alertText += ' at rows ' + invalidDescRows.join(', ');
				alertText += '</p>';

				s_info(Strings.VALIDATION_ERROR_TITLE, alertText, dlgOptions);
				return false;
			}


			if (invalidWpRows.length > 0) {
				let alertText = '<p>' + Strings.WORKING_PRINCIPLE_VALIDATION_ERR;
				alertText += ' at rows ' + invalidWpRows.join(', ');
				alertText += '</p>';

				s_info(Strings.VALIDATION_ERROR_TITLE, alertText, dlgOptions);
				return false;
			}
		}


		if (TenantWorkingPrincipleInterface && TenantWorkingPrincipleInterface.onBeforeSave)
			return TenantWorkingPrincipleInterface.onBeforeSave(dataObj);
		return dataObj;
	},

	onAfterSave: function(isSuccessful, dataObj) {
		//Custom code here
		if(dataObj.err_code === 422){

			if(dataObj.refFlag === true){
				let alertText = '<p>' + Strings.FOREIGN_REFERENCE_EXIST_ON_WP + '</p>';
				alertText += '<ol class="wp_prompt_error">';
				dataObj.deletedWithRefArr.forEach(item => {
					alertText += '<li>' + "'" + item.working_principle + "'" + '</li>';
				});
				alertText += '</ol>';
				s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, alertText, dlgOptions);
			}

			if(dataObj.deletedDup === true && dataObj.refFlag === false ){
				  s_toast(Strings.SAVE_WORKINGPRINCIPLE_TOAST_SUCCESS);
				//s_info(Strings.STEAMFLOWMETER_ERROR_TITLE, Strings.DELETED_DUPLICATE_WP_SAME_NAME , dlgOptions);
			}

			clearSheet();

			for (var i = 0; i < dataObj.data.length; i++) {
				var delObj = dataObj.data[i];
				var rowId = i + 1;
				editorSheet.setValue('A' + rowId, delObj.id, true);
				editorSheet.setValue('B' + rowId, delObj.working_principle, true);
				editorSheet.setValue('C' + rowId, delObj.description, true);
			}
			return false;
		}

		document.querySelectorAll('.jexcel td[title]').forEach(cell => {
			cell.removeAttribute('title');
		});

		if (TenantWorkingPrincipleInterface && TenantWorkingPrincipleInterface.onAfterSave)
			return TenantWorkingPrincipleInterface.onAfterSave(isSuccessful, dataObj);
		return dataObj;
	},

	onSheetChanged: function(instance, cell, col, row, value) {
		if(WorkingPrincipleInterface.loaded ){
			const sheetData = editorSheet.getData();
			const cellId = Number(row) + 1
			const targetWpCell = instance.jspreadsheet.getCell(`B${String(cellId)}`);
			const targetDescriptionCell = instance.jspreadsheet.getCell(`C${String(cellId)}`);

			//validation
			if(value && value.length > 30 && (col === 1 || col === "1")){
				//s_info( Strings.VALIDATION_ERROR_TITLE,  Strings.WORKING_PRINCIPLE_VALIDATION_ERR, dlgOptions );
				WorkingPrincipleInterface._addErrColor(cell);
				cell.setAttribute("title", Strings.WORKING_PRINCIPLE_VALIDATION_ERR);
				return false;
			}

			if(value && value.length > 50 && (col === 2 || col === "2")){
				//s_info( Strings.VALIDATION_ERROR_TITLE,  Strings.WORKING_PRINCIPLE_DESC_VALIDATION_ERR, dlgOptions );
				WorkingPrincipleInterface._addErrColor(cell);
				cell.setAttribute("title", Strings.WORKING_PRINCIPLE_DESC_VALIDATION_ERR);
				return false;
			}

			if (targetDescriptionCell) {

				const wpValue = sheetData[row][1];
				const descValue = sheetData[row][2] || "";

				const descTooLong = descValue.length > 50;
				const descWithoutWp = descValue && (!wpValue || wpValue.trim() === "");

				if (descTooLong) {
					WorkingPrincipleInterface._addErrColor(targetDescriptionCell);
					targetDescriptionCell.setAttribute("title",Strings.WORKING_PRINCIPLE_DESC_VALIDATION_ERR);
				}
				else if (descWithoutWp) {
					WorkingPrincipleInterface._addErrColor(targetDescriptionCell);
					targetDescriptionCell.setAttribute("title","Description with no working principle");
				}
				else {
					WorkingPrincipleInterface._removeErrColor(targetDescriptionCell);
					targetDescriptionCell.removeAttribute("title");
				}
			}


			var duplicateResults = common_util.checkDuplicate(sheetData, editorSheet);
			var duplicates = duplicateResults.duplicates;

			//remove color non duplicate WP

			if (duplicates.size === 0) {
				for (let idx = 1; idx <= sheetData.length; idx++) {
					const wpValue = sheetData[idx - 1][1];
					const wpCell = instance.jspreadsheet.getCell(`B${idx}`);

					if (wpCell) {
						if (!wpValue || wpValue.length <= 30) {
							WorkingPrincipleInterface._removeErrColor(wpCell);
							wpCell.removeAttribute("title");
						}
					}
				}
			}

			//add color for duplicate WP
			if (duplicates && duplicates.size > 0) {
				duplicates.forEach((rows, value) => {
					rows.forEach((row) => {
						const wpCell = instance.jspreadsheet.getCell(`B${row}`);
						if (wpCell) {
							WorkingPrincipleInterface._addErrColor(wpCell);
							wpCell.setAttribute("title","This data is already Exist");
						}
					});
				});
			}

		}

		if (TenantWorkingPrincipleInterface && TenantWorkingPrincipleInterface.onSheetChanged)
			return TenantWorkingPrincipleInterface.onSheetChanged(instance, cell, col, row, value);
		return true;
	},

	_addErrColor: function(cell){
		cell.classList.add("error_value");
	},

	_removeErrColor: function(cell){
		cell.classList.remove("error_value");
	},
};