/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Fri Feb 20 2026 16:10:41 GMT+0530 (India Standard Time)
	Description : Client Logic for BCSFuel ListDetails.
	Warning : DON"T TOUCH THE BASE CODE 
*/


var currAppName = 'BCSFuel';
var isCustom = false;
var msCheck = 0;
var loadCheck = 0;
var contentView, formView, formClose;
var lossTable;


var lossFuel_code_idZoom;
var lossFuel_unit_idZoom;
var lossFuel_yard_idZoom;
var createLossBtn, addLossBtn, cancelBtns, duplicateLossBtn, deleteLossBtn, editLossBtn, importLossBtn, aiAssistantLossBtn;
var cancelCreateBtn, cancelUpdateBtn;
var selectedRow;
var userObj;
var scrypto;
var params;
var rowData;
var backBtn;
var tourMsgs = [];
var primaryArr = [];
var chunkSize = 30;
var currentIndex = 0;
var offset = 0;
var limit = 100;
var limCookieSet = null;
var offCookieSet = null;
var loadMore, loadAll;
var actionsSelect;


var language = "EN";
var dlgOptions = {
  "STR_OK": "OK",
  "STR_CANCEL": "Cancel",
  "STR_YES": "Yes",
  "STR_NO": "No"
};

var filterLossBtn, filterActionsLossBtn;
var selectFilters;
var searchOptsTables = [];
var filterContent;

var numberFormat, currencyFormat, onlyNumRegExp, localeCode = null,
  currency = null;
var localeObj = {};
onlyNumRegExp = new RegExp(/^[0-9]*.?[0-9]*$/);

var actionsSelectOptionsArr = []
var lossFuel_code_id, lossFuel_unit_id, lossFuel_yard_id, lossFuel_loss_qty, lossFuel_loss_percentage, lossFuel_loss_value, lossFuel_loss_gst_value, lossFuel_loss_total_value, lossUnit_price, lossRemarks;
var codeArr;
var fuel_code_idPnl, fuel_code_idAddBtn, fuel_code_idMobBackBtn, assignFuel_code_idBtn, cancelFuel_code_idBtn, searchFuel_code_idBox, fuel_code_idTable;
var selectedFuel_code_idId;
var unitArr;
var fuel_unit_idPnl, fuel_unit_idAddBtn, fuel_unit_idMobBackBtn, assignFuel_unit_idBtn, cancelFuel_unit_idBtn, searchFuel_unit_idBox, fuel_unit_idTable;
var selectedFuel_unit_idId;
var yardArr;
var fuel_yard_idPnl, fuel_yard_idAddBtn, fuel_yard_idMobBackBtn, assignFuel_yard_idBtn, cancelFuel_yard_idBtn, searchFuel_yard_idBox, fuel_yard_idTable;
var selectedFuel_yard_idId;

var dataSources = {};
var customDtOpns = {};
$(document).ready(onApplicationReady);


function onApplicationReady() {
  var qStr = window.location.search;

  if (qStr) {
    params = clCommon.getParams(qStr.substring(1, qStr.length));
  }

  setMenu(document.getElementById('sideMenu'), 'bcsfuel_loss');


  clCommon.showLoader('svcProgress');
  var url = "/sauth/getuser";
  clCommon.getSvc(true, url, onUser, onUserError);
}


function initControls() {
  contentView = document.getElementById('contentView');
  formView = document.getElementById('lossDetailsPanel');
  formClose = document.getElementById('formClose');
  if (clCommon.isMobile()) {
    clCommon.hide(formClose);
    hideForm();
  } else {
    var formContent = document.querySelector('.form-content-holder');
    formContent.classList.add('expand');
  }

  cancelCreateBtn = document.getElementById('cancelCreateBtn');
  cancelUpdateBtn = document.getElementById('cancelUpdateBtn');

  filterContent = document.getElementById("filterContent");
  selectFilters = document.getElementById("selectFilters");

  // Set initial state of Cancel buttons based on Cookie
  var isFullCookie = clCommon.getCookie("bcsfuel_full_view");
  if (isFullCookie === "true") {
    clCommon.show(cancelCreateBtn);
    clCommon.show(cancelUpdateBtn);
  } else {
    clCommon.hide(cancelCreateBtn);
    clCommon.hide(cancelUpdateBtn);
  }

  lossFuel_code_id = document.getElementById('lossFuel_code_id');
  lossFuel_unit_id = document.getElementById('lossFuel_unit_id');
  lossFuel_yard_id = document.getElementById('lossFuel_yard_id');
  lossFuel_loss_qty = document.getElementById('lossFuel_loss_qty');
  lossFuel_loss_percentage = document.getElementById('lossFuel_loss_percentage');
  lossFuel_loss_value = document.getElementById('lossFuel_loss_value');
  lossFuel_loss_gst_value = document.getElementById('lossFuel_loss_gst_value');
  lossFuel_loss_total_value = document.getElementById('lossFuel_loss_total_value');
  lossUnit_price = document.getElementById('lossUnit_price');
  lossRemarks = document.getElementById('lossRemarks');

}


function initTable() {
  var dtOpns = { //Funtion to display datatable
    data: [], //Sort array and set data
    scrollY: (document.querySelector(".content-list").offsetHeight - 200) + "px",
    autoWidth: false,
    columns: [{
      data: 'record_date',
      render: renderData,
    }, {
      data: 'fuel_code_id',
      render: renderData,
    }, {
      data: 'fuel_yard_id',
      render: renderData,
    }, {
      data: 'fuel_loss_qty',
      render: renderData,
    }, {
      data: 'fuel_loss_value',
      render: renderData,
    }],
    "columnDefs": [],
    "orderClasses": false,
    "language": Strings.DATA_TABLE_LANG,
    "order": [], //to display the array sorted
    "deferRender": true
  };

  if (clCommon.isMobile())
    delete dtOpns.scrollY;

  if (Object.keys(customDtOpns).length > 0) {
    for (var opn in customDtOpns) {
      dtOpns[opn] = customDtOpns[opn];
    }
  }
  lossTable = $('#tableHolder').DataTable(dtOpns);



  if (!clCommon.isMobile()) {
    resizeTable();

    window.onresize = function(e) {
      resizeTable();
    };
  }
}

function renderData(data, type, row, meta) {
  var dataDisplay;
  if (LossInterface && LossInterface.renderData)
    dataDisplay = LossInterface.renderData(data, type, row, meta);
  if (!dataDisplay || dataDisplay == null || dataDisplay == undefined) {
    dataDisplay = data;
  }

  var isFullCookie = clCommon.getCookie("bcsfuel_full_view");

  if (!clCommon.isMobile() && isFullCookie === "true" && meta.col === 0) {
    return '<a href="javascript:void(0);" class="open-full-view-link">' + dataDisplay + '</a>';
  }

  if (!clCommon.isMobile()) resizeTable();

  return dataDisplay;
}

//To set the size of the table dynamically.
function resizeTable() {
  //Dont resize when listview is hidden
  if (contentView.classList.contains("hide")) {
    return;
  }
  setTimeout(setTableHeightOnResize, 50);

}

function setTableHeightOnResize() {
  // Get the height of the content list element
  var contListOffHeight = document.querySelector('.content-list').offsetHeight;

  // Get the height of the list head
  var listHeadOffHeight = document.querySelector('.listHead').offsetHeight;

  // Calculate and set the height of the list holder by subtracting the list head height from the content list height
  var listHolder = document.querySelector(".list-holder");
  listHolder.style.height = contListOffHeight - listHeadOffHeight + "px";

  // Get the heights of various DataTable elements
  var dtScrHeadClientHeight = document.querySelector('.dataTables_scrollHead').clientHeight; // DataTable scroll head height
  var dtFiltOfHeight = document.querySelector('.dataTables_filter').offsetHeight; // DataTable filter height
  var dtPagenateHeight = document.querySelector('.dataTables_paginate').offsetHeight; // DataTable pagination height

  // Set an additional offset to prevent the table from being too close to the bottom of the screen
  var addlOffSet = 10;

  // Calculate and set the height of the DataTable scroll body by subtracting the heights of the scroll head, filter, and pagination elements
  var scrollBodyHeight = listHolder.offsetHeight - dtScrHeadClientHeight - dtPagenateHeight - dtFiltOfHeight - addlOffSet;
  document.querySelector('div.dataTables_scrollBody').style.height = scrollBodyHeight + "px";

  // Adjust the DataTable columns after resizing
  lossTable.columns.adjust();
}



function registerEventListeners() {

  filterLossBtn = document.getElementById('filterLossBtn');
  filterLossBtn.addEventListener('click', onFilterLossBtnClick);

  formClose.addEventListener('click', toggleFullview);

  cancelBtns = document.querySelectorAll('.cancel-form-btn');
  cancelBtns.forEach(function(btn) {
    btn.addEventListener('click', onFormBackBtnClick);
  });
  if (clCommon.isMobile()) {
    cancelBtns = document.querySelectorAll('.cancel-form-btn');
    cancelBtns.forEach(function(btn) {
      clCommon.hide(btn);
    });
  }

  filterActionsLossBtn = document.getElementById('filterActionsLossBtn');
  filterActionsLossBtn.addEventListener('click', onFilterLossBtnClick);

  createLossBtn = document.getElementById('createLossBtn');
  createLossBtn.addEventListener('click', onCreateLossBtnClick);

  editLossBtn = document.getElementById('updateLossBtn');
  editLossBtn.addEventListener('click', onUpdateLossBtnClick);

  addLossBtn = document.getElementById('addLossBtn');
  addLossBtn.addEventListener('click', onAddLossBtnClick);



  if (clCommon.isMobile()) {
    deleteLossBtn = document.getElementById('deleteLossMobBtn');
    clCommon.hide(document.getElementById('deleteLossBtn'));
  } else {
    deleteLossBtn = document.getElementById('deleteLossBtn');
  }
  deleteLossBtn.addEventListener('click', onDeleteLossBtnClick);





  fuelCodeFilter = document.getElementById('fuelCodeFilter');
  fuelCodeFilter.addEventListener('change', onChangeOfFilter);



  loadMore = document.getElementById("loadMore");
  loadMore.addEventListener('click', onToolBarBtnClick);

  loadAll = document.getElementById("loadAll");
  loadAll.addEventListener('click', onToolBarBtnClick);

  lossFuel_code_id.addEventListener('change', onFieldChange);
  lossFuel_code_id.addEventListener('focus', onFieldFocus);
  lossFuel_code_id.addEventListener('blur', onFieldChange);

  lossFuel_code_idZoom = document.getElementById('lossFuel_code_idZoom');
  lossFuel_code_idZoom.addEventListener('click', onToolBarBtnClick);


  fuel_code_idPnl = document.getElementById("fuel_code_idPnl");

  fuel_code_idAddBtn = document.getElementById('fuel_code_idAddBtn');
  fuel_code_idAddBtn.addEventListener('click', onLookupAddBtnClick);

  fuel_code_idMobBackBtn = document.getElementById('fuel_code_idMobBackBtn');
  fuel_code_idMobBackBtn.addEventListener('click', onFuel_code_idMobBackBtn);

  relateFuel_code_idBtn = document.getElementById('assignFuel_code_idBtn');
  relateFuel_code_idBtn.addEventListener('click', onRelateFuel_code_idBtn);

  cancelFuel_code_idBtn = document.getElementById('cancelFuel_code_idBtn');
  cancelFuel_code_idBtn.addEventListener('click', onCancelFuel_code_idBtn);

  searchFuel_code_idBox = document.getElementById('searchFuel_code_idBox');
  searchFuel_code_idBox.addEventListener('keyup', onSearchFuel_code_id);
  lossFuel_unit_id.addEventListener('change', onFieldChange);
  lossFuel_unit_id.addEventListener('focus', onFieldFocus);
  lossFuel_unit_id.addEventListener('blur', onFieldChange);

  lossFuel_unit_idZoom = document.getElementById('lossFuel_unit_idZoom');
  lossFuel_unit_idZoom.addEventListener('click', onToolBarBtnClick);


  fuel_unit_idPnl = document.getElementById("fuel_unit_idPnl");

  fuel_unit_idAddBtn = document.getElementById('fuel_unit_idAddBtn');
  fuel_unit_idAddBtn.addEventListener('click', onLookupAddBtnClick);

  fuel_unit_idMobBackBtn = document.getElementById('fuel_unit_idMobBackBtn');
  fuel_unit_idMobBackBtn.addEventListener('click', onFuel_unit_idMobBackBtn);

  relateFuel_unit_idBtn = document.getElementById('assignFuel_unit_idBtn');
  relateFuel_unit_idBtn.addEventListener('click', onRelateFuel_unit_idBtn);

  cancelFuel_unit_idBtn = document.getElementById('cancelFuel_unit_idBtn');
  cancelFuel_unit_idBtn.addEventListener('click', onCancelFuel_unit_idBtn);

  searchFuel_unit_idBox = document.getElementById('searchFuel_unit_idBox');
  searchFuel_unit_idBox.addEventListener('keyup', onSearchFuel_unit_id);
  lossFuel_yard_id.addEventListener('change', onFieldChange);
  lossFuel_yard_id.addEventListener('focus', onFieldFocus);
  lossFuel_yard_id.addEventListener('blur', onFieldChange);

  lossFuel_yard_idZoom = document.getElementById('lossFuel_yard_idZoom');
  lossFuel_yard_idZoom.addEventListener('click', onToolBarBtnClick);


  fuel_yard_idPnl = document.getElementById("fuel_yard_idPnl");

  fuel_yard_idAddBtn = document.getElementById('fuel_yard_idAddBtn');
  fuel_yard_idAddBtn.addEventListener('click', onLookupAddBtnClick);

  fuel_yard_idMobBackBtn = document.getElementById('fuel_yard_idMobBackBtn');
  fuel_yard_idMobBackBtn.addEventListener('click', onFuel_yard_idMobBackBtn);

  relateFuel_yard_idBtn = document.getElementById('assignFuel_yard_idBtn');
  relateFuel_yard_idBtn.addEventListener('click', onRelateFuel_yard_idBtn);

  cancelFuel_yard_idBtn = document.getElementById('cancelFuel_yard_idBtn');
  cancelFuel_yard_idBtn.addEventListener('click', onCancelFuel_yard_idBtn);

  searchFuel_yard_idBox = document.getElementById('searchFuel_yard_idBox');
  searchFuel_yard_idBox.addEventListener('keyup', onSearchFuel_yard_id);
  lossFuel_loss_qty.addEventListener('change', onFieldChange);
  lossFuel_loss_qty.addEventListener('focus', onFieldFocus);
  lossFuel_loss_qty.addEventListener('blur', onFieldChange);
  lossFuel_loss_percentage.addEventListener('change', onFieldChange);
  lossFuel_loss_percentage.addEventListener('focus', onFieldFocus);
  lossFuel_loss_percentage.addEventListener('blur', onFieldChange);
  lossFuel_loss_value.addEventListener('change', onFieldChange);
  lossFuel_loss_value.addEventListener('focus', onFieldFocus);
  lossFuel_loss_value.addEventListener('blur', onFieldChange);
  lossFuel_loss_gst_value.addEventListener('change', onFieldChange);
  lossFuel_loss_gst_value.addEventListener('focus', onFieldFocus);
  lossFuel_loss_gst_value.addEventListener('blur', onFieldChange);
  lossFuel_loss_total_value.addEventListener('change', onFieldChange);
  lossFuel_loss_total_value.addEventListener('focus', onFieldFocus);
  lossFuel_loss_total_value.addEventListener('blur', onFieldChange);
  lossUnit_price.addEventListener('change', onFieldChange);
  lossUnit_price.addEventListener('focus', onFieldFocus);
  lossUnit_price.addEventListener('blur', onFieldChange);
  lossRemarks.addEventListener('change', onFieldChange);
  lossRemarks.addEventListener('focus', onFieldFocus);
  lossRemarks.addEventListener('blur', onFieldChange);


  $('#tableHolder tbody').on('click', 'tr', onRowClick);
  $('#tableHolder tbody').on('click', '.open-full-view-link', onTableLinkClick);


  backBtn = document.getElementById('backBtn');
  backBtn.addEventListener('click', onFormBackBtnClick);

  if (clCommon.isMobile() && window.history && window.history.pushState) {
    window.addEventListener('popstate', function() {
      hideForm();
    });
  }

  if (clCommon.isMobile()) {
    clCommon.setCookie("bcsfuel_full_view", "", -1);
    formView.classList.remove('fullview');
  }


  common_util.setSelectTitleOnChange();
}

function onTableLinkClick(e) {
  e.preventDefault();
  e.stopPropagation();
  var tr = $(this).closest('tr');
  if (!tr.hasClass('selected')) {
    tr.trigger('click');
  }
  toggleFullview(true);
}

function toggleFullview(forceState) {
  var isCurrentlyFull = formView.classList.contains('fullview');
  var shouldBeFull;

  if (typeof forceState === 'boolean') {
    shouldBeFull = forceState;
  } else {
    shouldBeFull = !isCurrentlyFull;
  }

  if (shouldBeFull) {
    // ENTER Full View 
    contentView.classList.add('hide');
    formView.classList.remove('hide');

    if (!clCommon.isMobile()) {
      formView.classList.add('fullview');
    }

    if (cancelCreateBtn) clCommon.show(cancelCreateBtn);
    if (cancelUpdateBtn) clCommon.show(cancelUpdateBtn);

    clCommon.setCookie("bcsfuel_full_view", "true", 10);

    if (lossTable) {
      lossTable.rows().invalidate().draw(false);
      resizeTable();
    }
  } else {
    // EXIT Full View
    contentView.classList.remove('hide');
    formView.classList.remove('fullview');
    formView.classList.remove('hide');

    if (cancelCreateBtn) clCommon.hide(cancelCreateBtn);
    if (cancelUpdateBtn) clCommon.hide(cancelUpdateBtn);

    clCommon.setCookie("bcsfuel_full_view", "", -1);

    if (lossTable) {
      lossTable.rows().invalidate().draw(false);
      resizeTable();
    }
  }

  // Handle Title Visibility
  var formTitle = document.getElementById('formTitleHeader');
  if (formTitle) {
    if (formView.classList.contains('fullview')) {
      formTitle.classList.remove('hide');
    } else {
      formTitle.classList.add('hide');
    }
  }

  //Handle Dynamic Field Layout (data-expand-class & data-normal-class)
  var expandFields = formView.querySelectorAll('[field]');

  if (expandFields.length > 0) {
    expandFields.forEach(function(el) {
      var expandStr = el.getAttribute('data-expand-class');
      var normalStr = el.getAttribute('data-normal-class');

      var expandClasses = expandStr ? expandStr : [];
      var normalClasses = normalStr ? normalStr : [];

      if (shouldBeFull) {
        el.className = expandClasses;
      } else {
        el.className = normalClasses;
      }
    });
  }
}


function openLookupView(panelElement) {
  clCommon.hide(formView);
  clCommon.show(panelElement);

  if (!clCommon.isMobile() && formView.classList.contains('fullview')) {
    panelElement.classList.add('fullview');
    contentView.classList.add('hide');
  }
}

function closeLookupView(panelElement) {
  clCommon.hide(panelElement);
  panelElement.classList.remove('fullview');

  clCommon.show(formView);
}

function onOptionClick(opObj, containerId, changedElementId) {
  clCommon.show(selectFilters);
  clCommon.hide(document.getElementById(containerId));

  var id = opObj.getAttribute("optnId");
  document.getElementById(changedElementId).value = id;


}

function onFilterLossBtnClick(e) {
  clCommon.show(selectFilters);

  const elements = document.querySelectorAll('[id$="OptsTableContainer"]');

  const ids = Array.from(elements).map(el => el.id);

  for (var id in ids) {
    clCommon.hide(document.getElementById(ids[id]));
  }

  openFilterPopup(e);
}

function openFilterPopup(event) {
  var bodyEl = filterContent;

  var options = {
    onSearch: function() {}
  };

  var buttons = [{
      label: "Cancel",
      handler: function(onPrompt) {
        return function(e) {
          clCommon.hide(filterContent);

          this.setAttribute("pressed", "cancel"),
            onPrompt && onPrompt.call(this, null);
        };
      },
      attributes: {
        "data-bs-dismiss": "modal"
      }
    },
    {
      label: "Apply",
      handler: (searchHandler = options.onSearch,
        function(e) {
          clCommon.hide(filterContent);
          loadLossData();
        }),
      attributes: {
        "data-bs-dismiss": "modal"
      }
    }
  ];

  var searchPopup = s_dialog('searchPopup', "Options", bodyEl, buttons, options, dlgOptions);
  searchPopup.show();
  clCommon.show(filterContent);

  if (clCommon.isMobile()) {
    if (event.target.id === 'filterLossBtn') {
      activateTab('nav-filter', 'nav-action');
    } else if (event.target.id === 'filterActionsLossBtn') {
      activateTab('nav-action', 'nav-filter');
    }
  } else {
    // Desktop default (assuming you don't need the clCommon hide/show logic here based on your original code)
    document.getElementById('nav-filter-tab').click();
  }
}

function activateTab(activeId, inactiveId) {
  // Handle the "Active" Tab
  clCommon.show(document.getElementById(activeId + '-tab'));
  clCommon.show(document.getElementById(activeId));
  document.getElementById(activeId + '-tab').classList.add('active');
  document.getElementById(activeId).classList.add('active', 'show');

  // Handle the "Inactive" Tab
  clCommon.hide(document.getElementById(inactiveId + '-tab'));
  clCommon.hide(document.getElementById(inactiveId));
  document.getElementById(inactiveId + '-tab').classList.remove('active');
  document.getElementById(inactiveId).classList.remove('active', 'show');
}


/*
	Function is called during onload event
*/
function onUser(resp) {
  clCommon.hideLoader('svcProgress');

  if (resp.code !== 200)
    redirect("/");

  userObj = resp.user;

  document.getElementById('userName').innerHTML = (userObj.firstname ? userObj.firstname : userObj.username);
  clCommon.initLanguage(userObj.realm_lang, function() {
    dlgOptions.STR_OK = clCommon.getString("OK", "OK");
    dlgOptions.STR_CANCEL = clCommon.getString("CANCEL", "Cancel");
    dlgOptions.STR_YES = clCommon.getString("YES", "Yes");
    dlgOptions.STR_NO = clCommon.getString("NO", "No");

    if (typeof LossInterface === 'undefined')
      LossInterface = null;

    if (LossInterface && LossInterface.onLoad)
      LossInterface.onLoad();

    initControls();
    initTable();
    initSearchTable();

    initFuel_code_idTable();
    initFuel_unit_idTable();
    initFuel_yard_idTable();


    registerEventListeners();
    setActionsSelectOptions();

    scrypto = new SimpleCrypto(userObj.realm_name);

    var userLocale = userObj.realm_locale ? userObj.realm_locale : localeObj;

    localeCode = userLocale.code ? userLocale.code : "en-IN";
    currency = userLocale.currency ? userLocale.currency : "INR";

    numberFormat = new Intl.NumberFormat(localeCode, {
      style: "decimal"
    });
    currencyFormat = new Intl.NumberFormat(localeCode, {
      style: "currency",
      currency: (typeof slocale !== 'undefined') ? slocale.getLocaleInfo(localeCode).currency_code : currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    });


    clCommon.showLoader('svcProgress');

    var customAppName = clCommon.getCustomAppName();
    var url = customAppName ? ("/steps/hq/" + customAppName + "/common/appsvc?is_custom=true") : (isCustom ? "./common/appsvc?is_custom=true" : "./common/appsvc");

    //To handle the across app integration
    if (params && params.app) {
      // If the URL already has a "?" in it, append with "&", otherwise with "?"
      url += (url.includes("?") ? "&" : "?") + "app=" + params.app;
    }


    clCommon.getSvc(true, url, onAppUserInfo, onAppUserInfoError);
  });
}

function initSearchTable() {
  for (var p = 0; p < searchOptsTables.length; p++) {
    var tableVarName = searchOptsTables[p]; // "productFilterOptsTable"
    var tableId = "#" + tableVarName; // "#productFilterOptsTable"

    // Create datatable instance
    var dt = $(tableId).DataTable({
      paging: false,
      info: false,
      autoWidth: false,
      columns: [{
          data: 'radio'
        },
        {
          data: 'optionName'
        }
      ],
      columnDefs: [{
        width: "25px",
        targets: 0
      }]
    });

    dt.table().node().classList.remove('nowrap');

    // Assign instance to the correct global variable
    window[tableVarName] = dt;
  }
}

function setActionsSelectOptions() {
  if (!document.getElementById('actionsSelectTable'))
    return;

  var tableId = "#" + "actionsSelectTable";


  // Create datatable instance
  var actionsTable = $(tableId).DataTable({
    paging: false,
    info: false,
    autoWidth: false,
    columns: [{
        data: 'radio'
      },
      {
        data: 'optionName'
      }
    ],
    columnDefs: [{
      width: "25px",
      targets: 0
    }]
  });

  actionsTable.table().node().classList.remove('nowrap');

  var optionsArr = [];
  for (var d in actionsSelectOptionsArr) {
    var optObj = actionsSelectOptionsArr[d];
    var tObj = {
      "optionName": '<label for="' + optObj.idName + '">' + optObj.displayName + '</label>',
      "radio": '<input type="radio" ' +
        'id="' + optObj.idName + '" ' +
        'name="optionName" ' +
        'onclick="onChangeOfActionSelect(this)">'
    };
    optionsArr.push(tObj);
  }

  actionsTable.clear().draw();
  actionsTable.rows.add(optionsArr).draw();
}

function capitalizeAndUnderscore(str) {
  // Trim the string, replace spaces with underscores, and convert to uppercase
  return str.trim().replace(/s+/g, '_').toUpperCase();
}

function loadMasters() {
  getCode();
  getUnit();
  getYard();

  masterWs = 3;
  callOnLoadFunction();
}

function callOnLoadFunction() {
  if (msCheck == masterWs) {
    loadData();
    msCheck = 0;
    return;
  }
  setTimeout(() => {
    callOnLoadFunction();
  }, 300);
}

function findOnlyUniques(array) {
  var seen = {};
  var uniqueArr = [];

  // Step 1: Remove duplicates by _sid
  for (var i = 0; i < array.length; i++) {
    var item = array[i];
    if (!seen[item._sid]) {
      seen[item._sid] = true;
      uniqueArr.push(item);
    }
  }

  return uniqueArr;
}

function loadLimFunction(lim) {
  if (lim) {
    offset += limit;
    limit = lim;
  } else {
    offset = 0;
    limit = 0;
  }

  clCommon.setCookie("LossOffset", offset, 10);
  clCommon.setCookie("LossLimit", limit, 10);

  loadLossData();
}


/*
	Function is called during onload event
	This function invoked on error response
*/
function onUserError(resp) {
  clCommon.hideLoader('svcProgress');
  redirect("/sauth/login.html");
}


/*
Function is called to redirect to the url
*/
function redirect(url) {
  window.location.href = url + (language !== "EN" ? ("?l=" + language) : "");
}


function getCode(isFieldChange, changedField) {


  Service.getCode(function(isFldChange, changedFld) {
    return function(respObj) {

      if (respObj.code == 200) {
        codeArr = JSON.parse(respObj.data[0].master_data);
        msCheck++;


        if (!dataSources.getCode) {
          dataSources.getCode = codeArr;
        }




        if (LossInterface && LossInterface.onBeforeLoad)
          dataSources = LossInterface.onBeforeLoad(dataSources);
        if (dataSources == false) {
          return;
        }


        if (undefined && dataSources.getCode && dataSources.getCode.length > 1) {
          dataSources.getCode = clCommon.sort(dataSources.getCode, "code"); //Sort alphabetically
        }





        for (var t = 0; t < dataSources.getCode.length; t++) {
          try {
            //decrypt response data
            dataSources.getCode[t].code = scrypto.decrypt(dataSources.getCode[t].code);
          } catch (e) {
            //ignore old unencrypted data
            dataSources.getCode[t].code = dataSources.getCode[t].code;
          }




          fuelCodeFilter.innerHTML += '<option value="' + dataSources.getCode[t].id + '">' + dataSources.getCode[t].code + '</option>';
        }


        if (LossInterface && isFieldChange == true) {
          LossInterface.onFieldChange(changedFld, dataSources);
        }

      }
    };
  }(isFieldChange, changedField));
}

function getUnit(isFieldChange, changedField) {


  Service.getUnit(function(isFldChange, changedFld) {
    return function(respObj) {

      if (respObj.code == 200) {
        unitArr = JSON.parse(respObj.data[0].master_data);
        msCheck++;


        if (!dataSources.getUnit) {
          dataSources.getUnit = unitArr;
        }




        if (LossInterface && LossInterface.onBeforeLoad)
          dataSources = LossInterface.onBeforeLoad(dataSources);
        if (dataSources == false) {
          return;
        }


        if (undefined && dataSources.getUnit && dataSources.getUnit.length > 1) {
          dataSources.getUnit = clCommon.sort(dataSources.getUnit, "unit"); //Sort alphabetically
        }





        for (var t = 0; t < dataSources.getUnit.length; t++) {
          try {
            //decrypt response data
            dataSources.getUnit[t].unit = scrypto.decrypt(dataSources.getUnit[t].unit);
          } catch (e) {
            //ignore old unencrypted data
            dataSources.getUnit[t].unit = dataSources.getUnit[t].unit;
          }





        }


        if (LossInterface && isFieldChange == true) {
          LossInterface.onFieldChange(changedFld, dataSources);
        }

      }
    };
  }(isFieldChange, changedField));
}

function getYard(isFieldChange, changedField) {


  Service.getYard(function(isFldChange, changedFld) {
    return function(respObj) {

      if (respObj.code == 200) {
        yardArr = JSON.parse(respObj.data[0].master_data);
        msCheck++;


        if (!dataSources.getYard) {
          dataSources.getYard = yardArr;
        }




        if (LossInterface && LossInterface.onBeforeLoad)
          dataSources = LossInterface.onBeforeLoad(dataSources);
        if (dataSources == false) {
          return;
        }


        if (undefined && dataSources.getYard && dataSources.getYard.length > 1) {
          dataSources.getYard = clCommon.sort(dataSources.getYard, "yard_code"); //Sort alphabetically
        }





        for (var t = 0; t < dataSources.getYard.length; t++) {
          try {
            //decrypt response data
            dataSources.getYard[t].yard_code = scrypto.decrypt(dataSources.getYard[t].yard_code);
          } catch (e) {
            //ignore old unencrypted data
            dataSources.getYard[t].yard_code = dataSources.getYard[t].yard_code;
          }





        }


        if (LossInterface && isFieldChange == true) {
          LossInterface.onFieldChange(changedFld, dataSources);
        }

      }
    };
  }(isFieldChange, changedField));
}



/*
	Function is called during onload event on error response
*/
function onAppUserInfo(resp) {
  var noDataElem = document.getElementById("contentNoData");
  var dataElem = document.getElementById("contentData");

  clCommon.hideLoader('svcProgress');

  if (resp.code === 200) {
    if (resp.menuArr) {
      clCommon.show(dataElem);
      dataSources.menuArr = resp.menuArr;
      dataSources.roleArr = resp.roleArr;

      processMenu(resp.menuArr);

      clCommon.appendSystemRoles(document.getElementById('sideMenu'), userObj);



      loadMasters();
    } else {
      clCommon.show(noDataElem);
      clCommon.hide(dataElem);
    }
  } else {
    s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
  }
}


/*
	Function is called during onload event on error response
*/
function onAppUserInfoError(resp) {
  clCommon.hideLoader('svcProgress');
  s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
}

function showForm() {
  window.history.pushState('form', null, '#form');
  clCommon.hide(contentView);
  clCommon.show(formView);
}

function hideForm() {
  clCommon.show(contentView);
  clCommon.hide(formView);
  if (!clCommon.isMobile()) resizeTable();
}

function onFormBackBtnClick(e) {
  if (e) e.preventDefault();

  if (clCommon.isMobile()) {
    history.back();
    return;
  }

  var isFullCookie = clCommon.getCookie("bcsfuel_full_view");
  clearForm();

  if (isFullCookie === "true") {
    contentView.classList.remove('hide');
    formView.classList.add('hide');
    formView.classList.add('fullview');
    if (selectedRow) {
      $(selectedRow).removeClass('selected');
      selectedRow = null;
    }
    deleteLossBtn.classList.add('disabled');
  }

  if (!clCommon.isMobile()) resizeTable();
}




function loadData() {
  clCommon.showLoader('dataProgress');
  var beforeLoad = true;
  if (LossInterface && LossInterface.onBeforeLoad)
    beforeLoad = LossInterface.onBeforeLoad(dataSources);

  if (beforeLoad == false) {
    return
  }
  svcCount = 0;
  loadMainLossData();

  onAfterLoadFunction();
}

function loadMainLossData() {
  clCommon.showLoader('dataProgress');
  checkAndLoadData();
  hideLoaderFn();
}


function onAfterLoadFunction() {
  if (LossInterface && LossInterface.onAfterLoad)
    LossInterface.onAfterLoad(dataSources);
  clCommon.hideLoader('dataProgress');
  loadCheck = 0;
  return;
}


function hideLoaderFn() {
  clCommon.hideLoader('dataProgress');
  loadCheck = 0;
  return;
}

function checkAndLoadData() {
  var limitCookie = clCommon.getCookie("LossLimit");
  var offsetCookie = clCommon.getCookie("LossOffset");

  var limitVal = Number(limitCookie);
  var offsetVal = Number(offsetCookie);

  // Case 1: Load All - offset = 0 and limit = 0
  if (offsetVal === 0 && limitVal === 0 && limitCookie != "" && offsetCookie != "") {
    s_confirm(Strings.CONFIRM, Strings.CONFIRM_LOAD_ALL_PRT_1 + "?" + Strings.CONFIRM_LOAD_PRT_2, {
      STR_YES: dlgOptions.STR_YES,
      STR_NO: dlgOptions.STR_NO,
      onYes: function() {
        limCookieSet = 0;
        offCookieSet = 0;
        loadMore.classList.add('disabled');
        loadAll.classList.add('disabled');
        loadLossData();
      },
      onNo: function() {
        offCookieSet = 0;
        limCookieSet = 100;
        loadLossData();
      }
    });
    return;
  }

  // Case 2: Load 400 plus data threshold check
  if (offsetVal >= 400 && limitVal > 0) {
    s_confirm(Strings.CONFIRM, Strings.VALIDATION_COOKIE_LOAD_DATA + "?", {
      STR_YES: dlgOptions.STR_YES,
      STR_NO: dlgOptions.STR_NO,
      onYes: function() {
        offCookieSet = 0;
        limCookieSet = offsetVal + limitVal;
        loadLossData();
      },
      onNo: function() {
        offCookieSet = 0;
        limCookieSet = 100;
        loadLossData();
      }
    });
    return;
  } else if (limitCookie != "" && offsetCookie != "") {
    offCookieSet = 0;
    limCookieSet = offsetVal + limitVal;
  }

  // Default: load first 100
  loadLossData();
}

function loadLossData() {
  lossTable.clear().draw();
  clCommon.showLoader("listProgress");

  if (limCookieSet != null) {
    offset = offCookieSet;
    limit = limCookieSet;
  }

  var params = [dataSources.startDate, dataSources.endDate, fuelCodeFilter.value, offset, limit, ];

  var onBeforeData = true;
  if (LossInterface && LossInterface.onBeforeData)
    onBeforeData = LossInterface.onBeforeData(params, dataSources);


  if (onBeforeData) {
    params.push(function(resultObj) {
      clCommon.hideLoader("listProgress");
      var dataArr;
      var isSuccessful;
      if (resultObj.code == 200) { //On success response
        if (limCookieSet != null) {
          offset = limCookieSet == 0 ? 0 : (limCookieSet - 100);
          limit = 100;
          offCookieSet = null;
          limCookieSet = null;
        }
        dataArr = resultObj.data.concat(primaryArr);
        dataArr = findOnlyUniques(dataArr);
        isSuccessful = true;


        if (LossInterface && LossInterface.onAfterData)
          dataArr = LossInterface.onAfterData(isSuccessful, dataArr, dataSources);

        onLoadSuccessResponse(dataArr);


        // Check Cookie
        var isFullCookie = clCommon.getCookie("bcsfuel_full_view");
        // Only auto-select first row if NOT mobile AND cookie is NOT set
        if (!clCommon.isMobile() && isFullCookie !== "true" && dataArr.length > 0) {
          var firstRow = $('#tableHolder tbody tr:eq(0)');
          if (firstRow) {
            firstRow.click(); //by default select first row
          }
        }

        // If cookie IS set, we ensure the form is hidden to show the table list
        else if (isFullCookie === "true") {
          contentView.classList.remove('hide');
          formView.classList.add('hide');
          formView.classList.add('fullview'); // Maintain state class for later logic

          // Ensure buttons are reset if needed
          deleteLossBtn.classList.add('disabled');
        }
        dataSources.primary = dataArr;
        primaryArr = dataArr;
        if (resultObj.count) {
          if ((primaryArr.length == resultObj.count) || (resultObj.count == -1)) {
            loadMore.classList.add('disabled');
            loadAll.classList.add('disabled');
          }
        }

      } else { //On error response
        isSuccessful = false;

        if (LossInterface && LossInterface.onAfterData)
          dataArr = LossInterface.onAfterData(isSuccessful, dataArr, dataSources);

        s_error(Strings.ERROR, Strings.ERROR_LOAD_LOSS, dlgOptions);
      }
    });
    Service.getLossByFilter.apply(this, params);
  }
  if (clCommon.isMobile()) {
    hideForm();
  }
}


function onLoadSuccessResponse(dataArr) {
  if (!dataArr || dataArr.length == 0) {
    clearForm();


    deleteLossBtn.classList.add('disabled');
  }

  chunkSize = 30;
  currentIndex = 0;
  lossTable.clear().draw();
  loadChunk(dataArr);

  var isFullCookie = clCommon.getCookie("bcsfuel_full_view");

  if (!clCommon.isMobile() && isFullCookie === "true") {
    contentView.classList.remove('hide');
    formView.classList.add('hide');
    formView.classList.add('fullview');

    clCommon.show(cancelCreateBtn);
    clCommon.show(cancelUpdateBtn);
  }
}

function loadChunk(dataArr) {
  if (!dataArr || currentIndex >= dataArr.length) {
    return;
  }

  var chunk = dataArr.slice(currentIndex, currentIndex + chunkSize);
  for (var i = 0; i < chunk.length; i++) {



  }
  lossTable.rows.add(chunk).draw(); // 'false' to not reset paging each time
  currentIndex += chunkSize;

  setTimeout(() => loadChunk(dataArr), 10); // adjust timeout as needed
}

function onChangeOfFilter(e) {



  clCommon.setCookie("code_id", fuelCodeFilter.value, 10)

  offset = 0;
  limit = 100;

  clCommon.setCookie("LossOffset", offset, 10);
  clCommon.setCookie("LossLimit", limit, 10);

  primaryArr = [];
  loadMore.classList.remove('disabled');
  loadAll.classList.remove('disabled');

  const changedElement = e.target;
  const selectedType = changedElement.value;

  if (selectedType == 'search') {
    //TODO add logic for popup and setup options

    clCommon.hide(selectFilters);

    var optionsTbCont = changedElement.id + "OptsTableContainer";
    clCommon.show(document.getElementById(optionsTbCont));

    var title = "Search";

    const options = changedElement.querySelectorAll("option");
    var optnArr = [];
    options.forEach(opt => {
      const name = opt.textContent.trim();
      if (name !== "Search") {
        optnArr.push({
          id: opt.value,
          name: name
        });
      }
    });

    var optionsArr = [];
    for (var d in optnArr) {
      var optObj = optnArr[d];
      var tObj = {
        "optionName": '<label for="radio_' + optObj.id + '">' + optObj.name + '</label>',
        "radio": '<input type="radio" ' +
          'id="radio_' + optObj.id + '" ' +
          'name="optionName" ' +
          'optnId="' + optObj.id + '" ' +
          'onclick="onOptionClick(this, \'' + optionsTbCont + '\', \'' + e.target.id + '\')">'
      };
      optionsArr.push(tObj);
    }

    window[changedElement.id + "OptsTable"].clear().draw();
    window[changedElement.id + "OptsTable"].rows.add(optionsArr).draw();

    var onSearchCheck = true;
    if (LossInterface && LossInterface.onSearchChangeFilter) {
      onSearchCheck = LossInterface.onSearchChangeFilter(e);
    }

  } else {
    var onChangeCheck = true;
    if (LossInterface && LossInterface.onChangeFilter)
      onChangeCheck = LossInterface.onChangeFilter(e)
  }
}

function onChangeOfActionSelect(val) {
  var changedAction = val;
  var returnData = true;
  if (LossInterface && LossInterface.onChangeOfActionSelect)
    returnData = LossInterface.onChangeOfActionSelect(changedAction, dataSources);
  if (returnData == false) {
    return;
  }
}


function onCreateLossBtnClick(e) {
  e.preventDefault();

  var lossObj = {};

  lossObj.fuel_code_id = lossFuel_code_id.getAttribute('Fuel_code_id');
  lossObj.fuel_unit_id = lossFuel_unit_id.getAttribute('Fuel_unit_id');
  lossObj.fuel_yard_id = lossFuel_yard_id.getAttribute('Fuel_yard_id');
  if (lossFuel_loss_qty.getAttribute("val") != "") {
    lossObj.fuel_loss_qty = Number(lossFuel_loss_qty.getAttribute("val"));
  } else {
    lossObj.fuel_loss_qty = null;
  }
  if (lossFuel_loss_percentage.getAttribute("val") != "") {
    lossObj.fuel_loss_percentage = Number(lossFuel_loss_percentage.getAttribute("val"));
  } else {
    lossObj.fuel_loss_percentage = null;
  }
  if (lossFuel_loss_value.getAttribute("val") != "") {
    lossObj.fuel_loss_value = Number(lossFuel_loss_value.getAttribute("val"));
  } else {
    lossObj.fuel_loss_value = null;
  }
  if (lossFuel_loss_gst_value.getAttribute("val") != "") {
    lossObj.fuel_loss_gst_value = Number(lossFuel_loss_gst_value.getAttribute("val"));
  } else {
    lossObj.fuel_loss_gst_value = null;
  }
  if (lossFuel_loss_total_value.getAttribute("val") != "") {
    lossObj.fuel_loss_total_value = Number(lossFuel_loss_total_value.getAttribute("val"));
  } else {
    lossObj.fuel_loss_total_value = null;
  }
  if (lossUnit_price.getAttribute("val") != "") {
    lossObj.unit_price = Number(lossUnit_price.getAttribute("val"));
  } else {
    lossObj.unit_price = null;
  }
  if (lossRemarks.value != "") {
    lossObj.remarks = lossRemarks.value;
  } else {
    lossObj.remarks = null;
  }

  var date = new Date();
  lossObj.created_by = userObj.username;
  lossObj.created_on = date.getTime();
  lossObj.modified_on = date.getTime();
  lossObj.modified_by = userObj.username;

  //Validate the loss object
  var checkLoss = validate(lossObj);

  //In validation is successfull
  if (checkLoss == true) {





    if (LossInterface && LossInterface.onBeforeCreate)
      lossObj = LossInterface.onBeforeCreate(lossObj, dataSources);
    if (lossObj == false) {
      return;
    }


    clCommon.showLoader("createProgress");
    clCommon.disable(createLossBtn);


    Service.createLossData(lossObj, function(resultObj) {
      if (resultObj.code == 200) { //on success response
        clCommon.hideLoader("createProgress");
        clCommon.enable(createLossBtn);
        s_toast(Strings.CREATE_LOSS_TOAST_SUCCESS);
        var isSuccessful = true;


        if (LossInterface && LossInterface.onAfterCreate)
          lossObj = LossInterface.onAfterCreate(isSuccessful, resultObj.data, dataSources);

        if (lossObj == false) {
          return;
        }

        clCommon.setCookie("loss_id", resultObj.data._sid, 10);
        primaryArr.push(resultObj.data);

        addRow(resultObj.data);

      } else {
        var isSuccessful = false;


        if (LossInterface && LossInterface.onAfterCreate)
          lossObj = LossInterface.onAfterCreate(isSuccessful, resultObj.data, dataSources);

        if (lossObj == false) {
          return;
        }

        s_error(Strings.LOSS_ERROR_TITLE, Strings.CREATE_LOSS_ERROR, dlgOptions);
      }
    });
  }
}

// Function to add a new row at the top
function addRow(newData) {



  // Add row to table
  var rowNode = lossTable.row.add(newData).node();

  // Draw the table to render the new data (triggers renderData)
  lossTable.draw(false);

  // Handle sorting to bring new item to top (visual preference)
  var rows = lossTable.rows().data().toArray();
  // Check if the last item is our new item
  if (rows.length > 0 && rows[rows.length - 1]._sid === newData._sid) {
    rows.unshift(rows.pop());
    lossTable.clear().rows.add(rows).draw(false);
  }

  // 5. Select the row
  selectRowBySid(newData._sid);
}



function onRowClick(e) {

  var isFullCookie = clCommon.getCookie("bcsfuel_full_view");

  if (!selectedRow) { //executes when the row is clicked for the first time
    selectedRow = this;
    $(selectedRow).addClass('selected');

    deleteLossBtn.classList.remove('disabled');


    clCommon.hide(createBtn);
    clCommon.show(updateBtn);

    clCommon.focus(lossFuel_code_id);
    selectedRow = this;

    rowData = lossTable.row(selectedRow).data();


    lossFuel_code_id.setAttribute("Fuel_code_id", rowData.fuel_code_id ? rowData.fuel_code_id : "");

    selectedFuel_code_idId = rowData.fuel_code_id ? rowData.fuel_code_id : "";

    var codeArr = dataSources.getCode;
    for (var i = 0; i < codeArr.length; i++) {
      var obj = codeArr[i];
      if (rowData.fuel_code_id == obj.id) {
        lossFuel_code_id.value = obj.code ? obj.code : "";
        break;
      }
    }
    lossFuel_code_id.dispatchEvent(new Event('change'));

    lossFuel_unit_id.setAttribute("Fuel_unit_id", rowData.fuel_unit_id ? rowData.fuel_unit_id : "");

    selectedFuel_unit_idId = rowData.fuel_unit_id ? rowData.fuel_unit_id : "";

    var unitArr = dataSources.getUnit;
    for (var i = 0; i < unitArr.length; i++) {
      var obj = unitArr[i];
      if (rowData.fuel_unit_id == obj.id) {
        lossFuel_unit_id.value = obj.unit ? obj.unit : "";
        break;
      }
    }
    lossFuel_unit_id.dispatchEvent(new Event('change'));

    lossFuel_yard_id.setAttribute("Fuel_yard_id", rowData.fuel_yard_id ? rowData.fuel_yard_id : "");

    selectedFuel_yard_idId = rowData.fuel_yard_id ? rowData.fuel_yard_id : "";

    var yardArr = dataSources.getYard;
    for (var i = 0; i < yardArr.length; i++) {
      var obj = yardArr[i];
      if (rowData.fuel_yard_id == obj.id) {
        lossFuel_yard_id.value = obj.yard_code ? obj.yard_code : "";
        break;
      }
    }
    lossFuel_yard_id.dispatchEvent(new Event('change'));


    if (LossInterface && LossInterface.onRowItemClick)
      rowData = LossInterface.onRowItemClick(rowData);

    displayForm(rowData);
  } else {

    if (selectedRow === this && isFullCookie === "true" && !clCommon.isMobile()) {
      return;
    }

    if (clCommon.isMobile() || (selectedRow != this) || (selectedRow == this)) { //executed when another row is selected
      $(selectedRow).removeClass('selected');

      deleteLossBtn.classList.add('disabled');


      clearForm();

      selectedRow = this;
      $(selectedRow).addClass('selected');

      deleteLossBtn.classList.remove('disabled');


      clCommon.hide(createBtn);
      clCommon.show(updateBtn);
      clCommon.focus(lossFuel_code_id);
      selectedRow = this;
      rowData = lossTable.row(selectedRow).data();


      lossFuel_code_id.setAttribute("Fuel_code_id", rowData.fuel_code_id ? rowData.fuel_code_id : "");

      selectedFuel_code_idId = rowData.fuel_code_id ? rowData.fuel_code_id : "";

      var codeArr = dataSources.getCode;
      for (var i = 0; i < codeArr.length; i++) {
        var obj = codeArr[i];
        if (rowData.fuel_code_id == obj.id) {
          lossFuel_code_id.value = obj.code ? obj.code : "";
          break;
        }
      }
      lossFuel_code_id.dispatchEvent(new Event('change'));

      lossFuel_unit_id.setAttribute("Fuel_unit_id", rowData.fuel_unit_id ? rowData.fuel_unit_id : "");

      selectedFuel_unit_idId = rowData.fuel_unit_id ? rowData.fuel_unit_id : "";

      var unitArr = dataSources.getUnit;
      for (var i = 0; i < unitArr.length; i++) {
        var obj = unitArr[i];
        if (rowData.fuel_unit_id == obj.id) {
          lossFuel_unit_id.value = obj.unit ? obj.unit : "";
          break;
        }
      }
      lossFuel_unit_id.dispatchEvent(new Event('change'));

      lossFuel_yard_id.setAttribute("Fuel_yard_id", rowData.fuel_yard_id ? rowData.fuel_yard_id : "");

      selectedFuel_yard_idId = rowData.fuel_yard_id ? rowData.fuel_yard_id : "";

      var yardArr = dataSources.getYard;
      for (var i = 0; i < yardArr.length; i++) {
        var obj = yardArr[i];
        if (rowData.fuel_yard_id == obj.id) {
          lossFuel_yard_id.value = obj.yard_code ? obj.yard_code : "";
          break;
        }
      }
      lossFuel_yard_id.dispatchEvent(new Event('change'));


      if (LossInterface && LossInterface.onRowItemClick)
        rowData = LossInterface.onRowItemClick(rowData);

      displayForm(rowData);
    }
  }

  if (clCommon.isMobile()) {
    showForm();
  } else {
    if (isFullCookie === "true") {
      hideForm();
    }
  }
}


//This function displays all the data in corresponsing controls
function displayForm(rowData) {

  lossFuel_code_id.value = rowData.fuel_code_id;
  lossFuel_code_id.dispatchEvent(new Event("change"));
  lossFuel_unit_id.value = rowData.fuel_unit_id;
  lossFuel_unit_id.dispatchEvent(new Event("change"));
  lossFuel_yard_id.value = rowData.fuel_yard_id;
  lossFuel_yard_id.dispatchEvent(new Event("change"));
  lossFuel_loss_qty.setAttribute('val', rowData.fuel_loss_qty);
  lossFuel_loss_qty.value = rowData.fuel_loss_qty;
  lossFuel_loss_qty.dispatchEvent(new Event("change"));
  lossFuel_loss_percentage.setAttribute('val', rowData.fuel_loss_percentage);
  lossFuel_loss_percentage.value = rowData.fuel_loss_percentage;
  lossFuel_loss_percentage.dispatchEvent(new Event("change"));
  lossFuel_loss_value.setAttribute('val', rowData.fuel_loss_value);
  lossFuel_loss_value.value = rowData.fuel_loss_value;
  lossFuel_loss_value.dispatchEvent(new Event("change"));
  lossFuel_loss_gst_value.setAttribute('val', rowData.fuel_loss_gst_value);
  lossFuel_loss_gst_value.value = rowData.fuel_loss_gst_value;
  lossFuel_loss_gst_value.dispatchEvent(new Event("change"));
  lossFuel_loss_total_value.setAttribute('val', rowData.fuel_loss_total_value);
  lossFuel_loss_total_value.value = rowData.fuel_loss_total_value;
  lossFuel_loss_total_value.dispatchEvent(new Event("change"));
  lossUnit_price.setAttribute('val', rowData.unit_price);
  lossUnit_price.value = rowData.unit_price;
  lossUnit_price.dispatchEvent(new Event("change"));
  lossRemarks.value = rowData.remarks;



  if (LossInterface && LossInterface.onDisplayForm)
    rowData = LossInterface.onDisplayForm(rowData);

}


function onUpdateLossBtnClick(e) {
  e.preventDefault();

  var lossObj = {};

  lossObj.fuel_code_id = lossFuel_code_id.getAttribute('Fuel_code_id');
  lossObj.fuel_unit_id = lossFuel_unit_id.getAttribute('Fuel_unit_id');
  lossObj.fuel_yard_id = lossFuel_yard_id.getAttribute('Fuel_yard_id');
  if (lossFuel_loss_qty.getAttribute("val") != "") {
    lossObj.fuel_loss_qty = Number(lossFuel_loss_qty.getAttribute("val"));
  } else {
    lossObj.fuel_loss_qty = null;
  }
  if (lossFuel_loss_percentage.getAttribute("val") != "") {
    lossObj.fuel_loss_percentage = Number(lossFuel_loss_percentage.getAttribute("val"));
  } else {
    lossObj.fuel_loss_percentage = null;
  }
  if (lossFuel_loss_value.getAttribute("val") != "") {
    lossObj.fuel_loss_value = Number(lossFuel_loss_value.getAttribute("val"));
  } else {
    lossObj.fuel_loss_value = null;
  }
  if (lossFuel_loss_gst_value.getAttribute("val") != "") {
    lossObj.fuel_loss_gst_value = Number(lossFuel_loss_gst_value.getAttribute("val"));
  } else {
    lossObj.fuel_loss_gst_value = null;
  }
  if (lossFuel_loss_total_value.getAttribute("val") != "") {
    lossObj.fuel_loss_total_value = Number(lossFuel_loss_total_value.getAttribute("val"));
  } else {
    lossObj.fuel_loss_total_value = null;
  }
  if (lossUnit_price.getAttribute("val") != "") {
    lossObj.unit_price = Number(lossUnit_price.getAttribute("val"));
  } else {
    lossObj.unit_price = null;
  }
  if (lossRemarks.value != "") {
    lossObj.remarks = lossRemarks.value;
  } else {
    lossObj.remarks = null;
  }


  lossObj._sid = rowData._sid;
  var date = new Date();
  lossObj.modified_on = date.getTime();
  lossObj.modified_by = userObj.username;
  lossObj.created_by = rowData.created_by ? rowData.created_by : userObj.username;
  lossObj.created_on = rowData.created_on ? rowData.created_on : null;

  //Validate the loss object
  var checkLoss = validate(lossObj);

  //In validation is successfull
  if (checkLoss == true) {




    if (LossInterface && LossInterface.onBeforeUpdate)
      lossObj = LossInterface.onBeforeUpdate(lossObj, dataSources);
    if (lossObj == false) {
      return;
    }


    clCommon.showLoader("updateProgress");
    clCommon.disable(updateLossBtn);

    Service.updateLossData(lossObj, function(resultObj) {
      if (resultObj.code == 200) { //on success response
        clCommon.hideLoader("updateProgress");
        clCommon.enable(updateLossBtn);
        s_toast(Strings.UPDATE_LOSS_TOAST_SUCCESS);

        var isSuccessful = true;


        if (LossInterface && LossInterface.onAfterUpdate)
          lossObj = LossInterface.onAfterUpdate(isSuccessful, resultObj.data, dataSources);
        if (lossObj == false) {
          return;
        }


        clCommon.setCookie("loss_id", resultObj.data._sid, 10);

        var index = primaryArr.findIndex(obj => obj._sid === resultObj.data._sid);

        if (index !== -1) {
          // Insert at the index where _sid matches
          primaryArr.splice(index, 0, resultObj.data);
        } else {
          // If not found, optionally push to end
          primaryArr.push(resultObj.data);
        }

        updateRowBySid(resultObj.data._sid, resultObj.data);

      } else {
        var isSuccessful = false;


        if (LossInterface && LossInterface.onAfterUpdate)
          lossObj = LossInterface.onAfterUpdate(isSuccessful, resultObj.data, dataSources);
        if (lossObj == false) {
          return;
        }


        s_error(Strings.LOSS_ERROR_TITLE, Strings.UPDATE_LOSS_ERROR, dlgOptions);
      }
    });
  }
}

// Function to update a row by _sid
function updateRowBySid(sid, updatedData) {



  // Find the existing row index
  var rowIndexes = lossTable.rows().indexes().toArray();
  var foundIndex = -1;

  // Manual search to be precise
  for (var i = 0; i < rowIndexes.length; i++) {
    var d = lossTable.row(rowIndexes[i]).data();
    if (d && d._sid === sid) {
      foundIndex = rowIndexes[i];
      break;
    }
  }

  if (foundIndex !== -1) {
    // 1. Update the data in place (better than remove/add for maintaining state)
    lossTable.row(foundIndex).data(updatedData);

    // 2. Invalidate the row to force re-render (Runs renderData again)
    lossTable.row(foundIndex).invalidate().draw(false);

    // 3. Move to top (Optional, to match your previous logic)
    var rows = lossTable.rows().data().toArray();
    // Find our updated object in the array
    var internalIdx = rows.findIndex(function(r) {
      return r._sid === sid;
    });
    if (internalIdx > 0) {
      var item = rows.splice(internalIdx, 1)[0];
      rows.unshift(item);
      lossTable.clear().rows.add(rows).draw(false);
    }
  }

  selectRowBySid(sid);
}


// Function to select a row by _sid and trigger onRowClick
function selectRowBySid(sid) {
  if (sid == null) return;

  var table = lossTable;
  var pageLen = table.page.len();

  // Find the row by _sid
  var target = table.row(function(idx, data) {
    return data && data._sid === sid;
  });

  // Fallback: first row on current page if not found (and table not empty)
  if (!target.any()) {
    var first = table.row(':eq(0)', {
      page: 'current'
    });
    if (!first.any()) return; // empty table

    table.one('draw', function() {
      // Clear all current selections
      table.rows({
        page: 'current'
      }).every(function() {
        this.node().classList.remove('selected');
      });

      var firstNode = first.node();
      firstNode.classList.add('selected');

      // Trigger click
      firstNode.dispatchEvent(new Event('click', {
        bubbles: true
      }));
    });

    table.draw(false);
    return;
  }

  // Compute the display position (after search/order) to know the page number
  var rowIdx = target.index(); // DataTables internal index
  var displayIdxs = table.rows({
    search: 'applied',
    order: 'applied'
  }).indexes().toArray();
  var pos = displayIdxs.indexOf(rowIdx);
  var pageIndex = (pos > -1) ? Math.floor(pos / pageLen) : table.page();

  // After the table redraws to the right page, re-find & select the row, then click
  table.one('draw', function() {
    var r = table.row(function(i, d) {
      return d && d._sid === sid;
    });
    if (!r.any()) return;

    // Clear current selections
    table.rows({
      page: 'current'
    }).every(function() {
      this.node().classList.remove('selected');
    });

    var node = r.node();
    node.classList.add('selected');

    // Trigger click
    node.dispatchEvent(new Event('click', {
      bubbles: true
    }));
  });

  table.page(pageIndex).draw(false);


  var isFullCookie = clCommon.getCookie("bcsfuel_full_view");
  if (isFullCookie === "true") {
    //clCommon.show(contentView);
    //clCommon.hide(formView);
    hideForm();
    if (selectedRow) {
      $(selectedRow).removeClass('selected');
      selectedRow = null;
    }
    deleteLossBtn.classList.add('disabled');
  }
}




function onAddLossBtnClick(e) {
  e.preventDefault();
  clearForm();

  if (clCommon.isMobile()) {
    showForm();
  } else {
    var isFullCookie = clCommon.getCookie("bcsfuel_full_view");
    if (isFullCookie === "true") {
      toggleFullview(true);
    }
  }

  deleteLossBtn.classList.add('disabled');


}



function clearForm() {
  var defaultObj = {
    "fuel_code_id": "",
    "fuel_unit_id": "",
    "fuel_yard_id": "",
    "fuel_loss_qty": "",
    "fuel_loss_percentage": "",
    "fuel_loss_value": "",
    "fuel_loss_gst_value": "",
    "fuel_loss_total_value": "",
    "unit_price": "",
    "remarks": ""
  };


  clCommon.hide(fuel_code_idPnl);
  lossFuel_code_id.setAttribute("Fuel_code_id", "");
  selectedFuel_code_idId = defaultObj.fuel_code_id;

  clCommon.hide(fuel_unit_idPnl);
  lossFuel_unit_id.setAttribute("Fuel_unit_id", "");
  selectedFuel_unit_idId = defaultObj.fuel_unit_id;

  clCommon.hide(fuel_yard_idPnl);
  lossFuel_yard_id.setAttribute("Fuel_yard_id", "");
  selectedFuel_yard_idId = defaultObj.fuel_yard_id;



  lossFuel_loss_qty.setAttribute("val", "");

  lossFuel_loss_percentage.setAttribute("val", "");

  lossFuel_loss_value.setAttribute("val", "");

  lossFuel_loss_gst_value.setAttribute("val", "");

  lossFuel_loss_total_value.setAttribute("val", "");

  lossUnit_price.setAttribute("val", "");


  if (LossInterface && LossInterface.onClearForm) {
    var modDefaultObj = LossInterface.onClearForm(defaultObj, dataSources);
    for (var attr in modDefaultObj) {
      if (modDefaultObj.hasOwnProperty(attr)) {
        defaultObj[attr] = modDefaultObj[attr]; // Apply changes to defaultObj
      }
    }
  }
  if (!clCommon.isMobile()) {
    clCommon.show(formView);
  }

  displayForm(defaultObj);

  clCommon.hide(updateBtn);
  clCommon.show(createBtn);

  deleteLossBtn.classList.add('disabled');


  rowData = "";

  clCommon.focus(lossFuel_code_id);

  if (selectedRow) {
    $(selectedRow).removeClass('selected');
  }

  selectedRow = "";
}



function onDeleteLossBtnClick() {
  var clArr = deleteLossBtn.classList;
  if (clArr.contains('disabled') == false)
    s_confirm(Strings.CONFIRM, Strings.LOSS_DELETE_CONFIRM + " - " + rowData.fuel_code_name + Strings.DELETE_TITLE_LOSS + " ?", { //Confirmation with user
      STR_YES: dlgOptions.STR_YES,
      STR_NO: dlgOptions.STR_NO,
      onYes: function() { //on approval
        clCommon.showLoader("removeProgress");

        if (LossInterface && LossInterface.onBeforeDelete)
          rowData = LossInterface.onBeforeDelete(rowData, dataSources);
        if (rowData == false) {
          clCommon.hideLoader("removeProgress");
          return;
        }


        Service.deleteLossData(rowData._sid, function(resultObj) {
          if (resultObj.code == 200) { //on Success response
            clCommon.hideLoader("removeProgress");

            var isSuccessful = true;

            var afterDelete = true;
            if (LossInterface && LossInterface.onAfterDelete)
              afterDelete = LossInterface.onAfterDelete(isSuccessful, resultObj, dataSources);
            if (afterDelete == false) {
              return;
            }


            deleteLossBtn.classList.add('disabled');

            removeRowBySid(rowData._sid);

            var index = primaryArr.findIndex(item => item._sid === rowData._sid);

            if (index !== -1) {
              primaryArr.splice(index, 1);
            }

            s_toast(Strings.DELETE_LOSS_TOAST_SUCCESS);
          } else { //On Error response
            var isSuccessful = false;

            var afterDelete = true;
            if (LossInterface && LossInterface.onAfterDelete)
              afterDelete = LossInterface.onAfterDelete(isSuccessful, resultObj, dataSources);
            if (afterDelete == false) {
              return;
            }

            s_error(Strings.LOSS_ERROR_TITLE, Strings.DELETE_LOSS_ERROR, dlgOptions);
            clCommon.hideLoader("removeProgress");
          }
        });
      }
    });
}

// Function to remove a row by _sid
function removeRowBySid(sid) {
  // Remove the row that matches the provided sid
  lossTable.rows(function(idx, data, node) {
    return data._sid === sid; // Find row where _sid matches
  }).remove().draw(); // Remove and redraw the table

  if (lossTable.data().any()) {
    // Select the first row in the current page
    var firstRowNode = lossTable.row(':eq(0)', {
      page: 'current'
    }).node();
    if (firstRowNode) {


      clCommon.enable(deleteLossBtn);

      $(firstRowNode).addClass('selected');
      $(firstRowNode).trigger('click'); // Trigger the click event to simulate row selection
    }
  }
}



function onFieldFocus(e) {
  e.preventDefault();
  var focusedField = this;

  var currencyAttr = focusedField.getAttribute("currency");
  var isCurrencyField = currencyAttr && currencyAttr.trim().toLowerCase() === "true";

  var defaultVal = focusedField.getAttribute("default_val");
  var defaultDigits = Number.isFinite(parseInt(defaultVal)) ? parseInt(defaultVal) : (isCurrencyField ? "" : "");


  if (focusedField.id == "lossFuel_loss_qty") {
    var raw = focusedField.value.replace(/[^0-9.-]+/g, "");
    raw = (raw <= 0 || raw === "" || isNaN(raw)) ? defaultDigits : Number(raw);
    focusedField.value = raw;
  }

  if (focusedField.id == "lossFuel_loss_percentage") {
    var raw = focusedField.value.replace(/[^0-9.-]+/g, "");
    raw = (raw <= 0 || raw === "" || isNaN(raw)) ? defaultDigits : Number(raw);
    focusedField.value = raw;
  }

  if (focusedField.id == "lossFuel_loss_value") {
    var raw = focusedField.value.replace(/[^0-9.-]+/g, "");
    raw = (raw <= 0 || raw === "" || isNaN(raw)) ? defaultDigits : Number(raw);
    focusedField.value = raw;
  }

  if (focusedField.id == "lossFuel_loss_gst_value") {
    var raw = focusedField.value.replace(/[^0-9.-]+/g, "");
    raw = (raw <= 0 || raw === "" || isNaN(raw)) ? defaultDigits : Number(raw);
    focusedField.value = raw;
  }

  if (focusedField.id == "lossFuel_loss_total_value") {
    var raw = focusedField.value.replace(/[^0-9.-]+/g, "");
    raw = (raw <= 0 || raw === "" || isNaN(raw)) ? defaultDigits : Number(raw);
    focusedField.value = raw;
  }

  if (focusedField.id == "lossUnit_price") {
    var raw = focusedField.value.replace(/[^0-9.-]+/g, "");
    raw = (raw <= 0 || raw === "" || isNaN(raw)) ? defaultDigits : Number(raw);
    focusedField.value = raw;
  }



  if (LossInterface && LossInterface.onFieldFocus)
    var returnData = LossInterface.onFieldFocus(focusedField, dataSources);
}


function onFieldChange(e) {
  e.preventDefault();
  var changedField = this;


  if (changedField.id == "lossFuel_code_id") {
    var rawVal = lossFuel_code_id.getAttribute("Fuel_code_id");
    var sourceArr = dataSources.getCode;
    if (sourceArr) {
      var item = sourceArr.find(function(x) {
        return x.id == rawVal;
      });
      lossFuel_code_id.value = item ? item.code : "";
    }
  }

  if (changedField.id == "lossFuel_unit_id") {
    var rawVal = lossFuel_unit_id.getAttribute("Fuel_unit_id");
    var sourceArr = dataSources.getUnit;
    if (sourceArr) {
      var item = sourceArr.find(function(x) {
        return x.id == rawVal;
      });
      lossFuel_unit_id.value = item ? item.unit : "";
    }
  }

  if (changedField.id == "lossFuel_yard_id") {
    var rawVal = lossFuel_yard_id.getAttribute("Fuel_yard_id");
    var sourceArr = dataSources.getYard;
    if (sourceArr) {
      var item = sourceArr.find(function(x) {
        return x.id == rawVal;
      });
      lossFuel_yard_id.value = item ? item.yard_code : "";
    }
  }



  if (changedField.id == "lossFuel_loss_qty") {
    lossFuel_loss_qty = formattingNumberElements(changedField);
  }

  if (changedField.id == "lossFuel_loss_percentage") {
    lossFuel_loss_percentage = formattingNumberElements(changedField);
  }

  if (changedField.id == "lossFuel_loss_value") {
    lossFuel_loss_value = formattingNumberElements(changedField);
  }

  if (changedField.id == "lossFuel_loss_gst_value") {
    lossFuel_loss_gst_value = formattingNumberElements(changedField);
  }

  if (changedField.id == "lossFuel_loss_total_value") {
    lossFuel_loss_total_value = formattingNumberElements(changedField);
  }

  if (changedField.id == "lossUnit_price") {
    lossUnit_price = formattingNumberElements(changedField);
  }


  var dependentFieldArr = document.querySelectorAll(".form-holder [data-dependent=" + changedField.id + "]");
  if (dependentFieldArr.length > 0) {
    for (var idx = 0; idx < dependentFieldArr.length; idx++) {
      var dependentField = dependentFieldArr[idx];
      var dataSrcFunction = dependentField.getAttribute("data-srcFunc");
      if (dataSrcFunction) {
        delete window.dataSources[dataSrcFunction];
        var functionCall = window[dataSrcFunction].call(window, true, changedField);
      } else {
        if (LossInterface && LossInterface.onFieldChange)
          var returnData = LossInterface.onFieldChange(changedField, dataSources);
      }
    }
  } else {
    if (LossInterface && LossInterface.onFieldChange)
      var returnData = LossInterface.onFieldChange(changedField, dataSources);
  }

}

function formattingNumberElements(fieldEl) {
  var raw = fieldEl.value.replace(/[^0-9.-]+/g, "");
  raw = raw === "" || isNaN(raw) ? 0 : Number(raw);
  fieldEl.setAttribute("val", raw);

  var decimalAttr = fieldEl.getAttribute("decimal");
  var decimalDigits = Number.isFinite(parseInt(decimalAttr)) ? parseInt(decimalAttr) : null;


  var currencyAttr = fieldEl.getAttribute("currency");
  var isCurrencyField = currencyAttr && currencyAttr.trim().toLowerCase() === "true";

  var currencyCode = (typeof slocale !== "undefined") ? slocale.getLocaleInfo(localeCode).currency_code : currency;


  if (isCurrencyField) {
    var currencyFormatForAmount = decimalDigits !== null ? new Intl.NumberFormat(localeCode, {
      style: "currency",
      currency: currencyCode,
      minimumFractionDigits: decimalDigits,
      maximumFractionDigits: decimalDigits
    }) : currencyFormat;


    fieldEl.value = currencyFormatForAmount.format(raw);
  } else {
    var numberFormatForAmount = decimalDigits !== null ? new Intl.NumberFormat(localeCode, {
      style: "decimal",
      minimumFractionDigits: decimalDigits,
      maximumFractionDigits: decimalDigits
    }) : numberFormat;


    fieldEl.value = numberFormatForAmount.format(raw);
  }
  return fieldEl;
}


function validate(lossObj) {

  if (!lossObj.fuel_code_id) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_CODE_ID, dlgOptions);
    return false;
  }

  if (!lossObj.fuel_yard_id) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_YARD_ID, dlgOptions);
    return false;
  }

  if (!lossObj.fuel_loss_qty) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_LOSS_QTY, dlgOptions);
    return false;
  }

  if (lossObj.fuel_loss_qty && !onlyNumRegExp.test(lossObj.fuel_loss_qty)) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_LOSS_QTY, dlgOptions);
    return false;
  }

  if (!lossObj.fuel_loss_percentage) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_LOSS_PERCENTAGE, dlgOptions);
    return false;
  }

  if (lossObj.fuel_loss_percentage && !onlyNumRegExp.test(lossObj.fuel_loss_percentage)) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_LOSS_PERCENTAGE, dlgOptions);
    return false;
  }

  if (!lossObj.fuel_loss_value) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_LOSS_VALUE, dlgOptions);
    return false;
  }

  if (lossObj.fuel_loss_value && !onlyNumRegExp.test(lossObj.fuel_loss_value)) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_LOSS_VALUE, dlgOptions);
    return false;
  }

  if (lossObj.fuel_loss_gst_value && !onlyNumRegExp.test(lossObj.fuel_loss_gst_value)) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_LOSS_GST_VALUE, dlgOptions);
    return false;
  }

  if (lossObj.fuel_loss_total_value && !onlyNumRegExp.test(lossObj.fuel_loss_total_value)) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_FUEL_LOSS_TOTAL_VALUE, dlgOptions);
    return false;
  }

  if (lossObj.unit_price && !onlyNumRegExp.test(lossObj.unit_price)) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.LOSS_INVALID_UNIT_PRICE, dlgOptions);
    return false;
  }


  return true;
}


function containsOnlyLetters(str) {
  return /^[a-zA-Z\s]+$/.test(str);
}



function containsNumbers(str) {
  return /^[0-9.]+$/.test(str);
}




function onToolBarBtnClick(e) {
  e.preventDefault();
  var clickedBtn = this;
  var returnData = true;
  if (LossInterface && LossInterface.onToolBarBtnClick)
    returnData = LossInterface.onToolBarBtnClick(clickedBtn, dataSources);
  if (returnData === false) {
    return;
  } else {
    var clArr;
    switch (clickedBtn.id) {
      case "loadMore":
        clArr = loadMore.classList;
        if (clArr.contains('disabled') == false)
          loadLimFunction(limit);
        break;
      case "loadAll":
        clArr = loadAll.classList;
        if (clArr.contains('disabled') == false)
          s_confirm(Strings.CONFIRM, Strings.CONFIRM_LOAD_ALL_PRT_1 + "?" + Strings.CONFIRM_LOAD_PRT_2, { //Confirm with the user 
            STR_YES: dlgOptions.STR_YES,
            STR_NO: dlgOptions.STR_NO,
            onYes: function() { //On positive confirmation
              primaryArr = [];
              loadMore.classList.add('disabled');
              loadAll.classList.add('disabled');
              loadLimFunction(0);

            }
          });

        break;


      case "lossFuel_code_idZoom":
        onFuel_code_idZoomBtn();
        break;
      case "lossFuel_unit_idZoom":
        onFuel_unit_idZoomBtn();
        break;
      case "lossFuel_yard_idZoom":
        onFuel_yard_idZoomBtn();
        break;

    }
  }
}


function onLookupAddBtnClick(e) {
  e.preventDefault();
  var clickedBtn = this;
  var returnData = true;
  if (LossInterface && LossInterface.onLookupAddBtnClick)
    returnData = LossInterface.onLookupAddBtnClick(clickedBtn.getAttribute('data-lookup-add'), clickedBtn, dataSources);
  if (returnData === false) {
    return;
  }
}









function initFuel_code_idTable() {
  fuel_code_idTable = $('#fuel_code_idTable').DataTable({
    paging: false,
    info: false,
    autoWidth: false,
    columns: [{
        data: 'radio'
      },
      {
        data: 'fuel_code_idName'
      }
    ],
    columnDefs: [{
      "width": "25px",
      "targets": 0
    }]
  });
  fuel_code_idTable.table().node().classList.remove('nowrap');
}

function onFuel_code_idZoomBtn(e) {
  clCommon.hide(formView);
  clCommon.show(fuel_code_idPnl);
  openLookupView(fuel_code_idPnl);
  var pushState = (e !== false);
  var fuel_code_idArr = [];
  var objectiveIds = [];

  // Get current value(s) from attribute
  var rawVal = lossFuel_code_id.getAttribute("Fuel_code_id");

  if (rawVal) {
    // Handle both JSON Array string and single value
    try {
      if (rawVal.trim().startsWith('[')) {
        objectiveIds = JSON.parse(rawVal);
      } else {
        objectiveIds = [rawVal];
      }
    } catch (e) {
      objectiveIds = [rawVal];
    }
  }

  var check = true;
  if (LossInterface && LossInterface.onLookUpData) {
    check = LossInterface.onLookUpData("fuel_code_id", dataSources);
  }
  if (check == false) return;

  for (var item of dataSources.getCode) {
    var checked = "";

    // Check if item ID exists in our objectiveIds array (Handles both single and multi)
    // We compare loose equality to handle string/number mismatch
    if (objectiveIds.some(id => id == item.id)) {
      checked = "checked";
    } else if (rowData && rowData.fuel_code_id == item.id && objectiveIds.length === 0) {
      // Fallback to rowData if input is empty but row has data
      checked = "checked";
    }

    fuel_code_idArr.push({
      "fuel_code_idName": '<label for="' + item.id + '">' + item.code + '</label>',
      "radio": '<input type="radio" name="fuel_code_idName" fuel_code_idId="' + item._sid + '" fuel_code_idName="' + JSON.stringify(item).replaceAll('"', '$' + 'DQUOTE' + '$') + '" ' + checked + '>'
    });
  }

  fuel_code_idTable.clear().draw();
  fuel_code_idTable.rows.add(fuel_code_idArr).draw();

  if (clCommon.isMobile() && pushState) {
    window.history.pushState('fuel_code_idForm', null, '#fuel_code_idsForm');
    clCommon.hide(contentView);
  }
}

function onRelateFuel_code_idBtn(e) {
  // Select all checked inputs
  var selectedObjs = document.querySelectorAll('input[name="fuel_code_idName"]:checked');

  if (selectedObjs.length === 0) {
    s_info(Strings.LOSS_ALERT_TITLE, Strings.LOSS_INVALID_FUEL_CODE_ID, dlgOptions);
    return;
  }

  var selectedIds = [];
  var selectedNames = [];

  selectedObjs.forEach(function(el) {
    var objective = JSON.parse(el.getAttribute("fuel_code_idName").replaceAll('$DQUOTE$', '"'));
    var val = objective.id || "";
    var disp = objective.code || "";

    selectedIds.push(val);
    selectedNames.push(disp);
  });


  // Radio: Store single value in attribute (0 index)
  lossFuel_code_id.value = selectedNames[0];
  lossFuel_code_id.setAttribute("Fuel_code_id", selectedIds[0]);
  selectedFuel_code_idId = selectedIds[0];

  lossFuel_code_id.dispatchEvent(new Event('change'));
  clCommon.hide(fuel_code_idPnl);
  clCommon.show(formView);
  closeLookupView(fuel_code_idPnl);
}

function onSearchFuel_code_id() {
  const searchInput = document.getElementById('searchFuel_code_idBox');
  if (fuel_code_idTable && searchInput) {
    fuel_code_idTable.search(searchInput.value).draw();
  }
}

function onCancelFuel_code_idBtn(e) {
  clCommon.hide(fuel_code_idPnl);
  clCommon.show(formView);
  closeLookupView(fuel_code_idPnl);
}

function onFuel_code_idMobBackBtn(e) {
  history.back();
}

function initFuel_unit_idTable() {
  fuel_unit_idTable = $('#fuel_unit_idTable').DataTable({
    paging: false,
    info: false,
    autoWidth: false,
    columns: [{
        data: 'radio'
      },
      {
        data: 'fuel_unit_idName'
      }
    ],
    columnDefs: [{
      "width": "25px",
      "targets": 0
    }]
  });
  fuel_unit_idTable.table().node().classList.remove('nowrap');
}

function onFuel_unit_idZoomBtn(e) {
  clCommon.hide(formView);
  clCommon.show(fuel_unit_idPnl);
  openLookupView(fuel_unit_idPnl);
  var pushState = (e !== false);
  var fuel_unit_idArr = [];
  var objectiveIds = [];

  // Get current value(s) from attribute
  var rawVal = lossFuel_unit_id.getAttribute("Fuel_unit_id");

  if (rawVal) {
    // Handle both JSON Array string and single value
    try {
      if (rawVal.trim().startsWith('[')) {
        objectiveIds = JSON.parse(rawVal);
      } else {
        objectiveIds = [rawVal];
      }
    } catch (e) {
      objectiveIds = [rawVal];
    }
  }

  var check = true;
  if (LossInterface && LossInterface.onLookUpData) {
    check = LossInterface.onLookUpData("fuel_unit_id", dataSources);
  }
  if (check == false) return;

  for (var item of dataSources.getUnit) {
    var checked = "";

    // Check if item ID exists in our objectiveIds array (Handles both single and multi)
    // We compare loose equality to handle string/number mismatch
    if (objectiveIds.some(id => id == item.id)) {
      checked = "checked";
    } else if (rowData && rowData.fuel_unit_id == item.id && objectiveIds.length === 0) {
      // Fallback to rowData if input is empty but row has data
      checked = "checked";
    }

    fuel_unit_idArr.push({
      "fuel_unit_idName": '<label for="' + item.id + '">' + item.unit + '</label>',
      "radio": '<input type="radio" name="fuel_unit_idName" fuel_unit_idId="' + item._sid + '" fuel_unit_idName="' + JSON.stringify(item).replaceAll('"', '$' + 'DQUOTE' + '$') + '" ' + checked + '>'
    });
  }

  fuel_unit_idTable.clear().draw();
  fuel_unit_idTable.rows.add(fuel_unit_idArr).draw();

  if (clCommon.isMobile() && pushState) {
    window.history.pushState('fuel_unit_idForm', null, '#fuel_unit_idsForm');
    clCommon.hide(contentView);
  }
}

function onRelateFuel_unit_idBtn(e) {
  // Select all checked inputs
  var selectedObjs = document.querySelectorAll('input[name="fuel_unit_idName"]:checked');

  if (selectedObjs.length === 0) {
    s_info(Strings.LOSS_ALERT_TITLE, Strings.LOSS_INVALID_FUEL_UNIT_ID, dlgOptions);
    return;
  }

  var selectedIds = [];
  var selectedNames = [];

  selectedObjs.forEach(function(el) {
    var objective = JSON.parse(el.getAttribute("fuel_unit_idName").replaceAll('$DQUOTE$', '"'));
    var val = objective.id || "";
    var disp = objective.unit || "";

    selectedIds.push(val);
    selectedNames.push(disp);
  });


  // Radio: Store single value in attribute (0 index)
  lossFuel_unit_id.value = selectedNames[0];
  lossFuel_unit_id.setAttribute("Fuel_unit_id", selectedIds[0]);
  selectedFuel_unit_idId = selectedIds[0];

  lossFuel_unit_id.dispatchEvent(new Event('change'));
  clCommon.hide(fuel_unit_idPnl);
  clCommon.show(formView);
  closeLookupView(fuel_unit_idPnl);
}

function onSearchFuel_unit_id() {
  const searchInput = document.getElementById('searchFuel_unit_idBox');
  if (fuel_unit_idTable && searchInput) {
    fuel_unit_idTable.search(searchInput.value).draw();
  }
}

function onCancelFuel_unit_idBtn(e) {
  clCommon.hide(fuel_unit_idPnl);
  clCommon.show(formView);
  closeLookupView(fuel_unit_idPnl);
}

function onFuel_unit_idMobBackBtn(e) {
  history.back();
}

function initFuel_yard_idTable() {
  fuel_yard_idTable = $('#fuel_yard_idTable').DataTable({
    paging: false,
    info: false,
    autoWidth: false,
    columns: [{
        data: 'radio'
      },
      {
        data: 'fuel_yard_idName'
      }
    ],
    columnDefs: [{
      "width": "25px",
      "targets": 0
    }]
  });
  fuel_yard_idTable.table().node().classList.remove('nowrap');
}

function onFuel_yard_idZoomBtn(e) {
  clCommon.hide(formView);
  clCommon.show(fuel_yard_idPnl);
  openLookupView(fuel_yard_idPnl);
  var pushState = (e !== false);
  var fuel_yard_idArr = [];
  var objectiveIds = [];

  // Get current value(s) from attribute
  var rawVal = lossFuel_yard_id.getAttribute("Fuel_yard_id");

  if (rawVal) {
    // Handle both JSON Array string and single value
    try {
      if (rawVal.trim().startsWith('[')) {
        objectiveIds = JSON.parse(rawVal);
      } else {
        objectiveIds = [rawVal];
      }
    } catch (e) {
      objectiveIds = [rawVal];
    }
  }

  var check = true;
  if (LossInterface && LossInterface.onLookUpData) {
    check = LossInterface.onLookUpData("fuel_yard_id", dataSources);
  }
  if (check == false) return;

  for (var item of dataSources.getYard) {
    var checked = "";

    // Check if item ID exists in our objectiveIds array (Handles both single and multi)
    // We compare loose equality to handle string/number mismatch
    if (objectiveIds.some(id => id == item.id)) {
      checked = "checked";
    } else if (rowData && rowData.fuel_yard_id == item.id && objectiveIds.length === 0) {
      // Fallback to rowData if input is empty but row has data
      checked = "checked";
    }

    fuel_yard_idArr.push({
      "fuel_yard_idName": '<label for="' + item.id + '">' + item.yard_code + '</label>',
      "radio": '<input type="radio" name="fuel_yard_idName" fuel_yard_idId="' + item._sid + '" fuel_yard_idName="' + JSON.stringify(item).replaceAll('"', '$' + 'DQUOTE' + '$') + '" ' + checked + '>'
    });
  }

  fuel_yard_idTable.clear().draw();
  fuel_yard_idTable.rows.add(fuel_yard_idArr).draw();

  if (clCommon.isMobile() && pushState) {
    window.history.pushState('fuel_yard_idForm', null, '#fuel_yard_idsForm');
    clCommon.hide(contentView);
  }
}

function onRelateFuel_yard_idBtn(e) {
  // Select all checked inputs
  var selectedObjs = document.querySelectorAll('input[name="fuel_yard_idName"]:checked');

  if (selectedObjs.length === 0) {
    s_info(Strings.LOSS_ALERT_TITLE, Strings.LOSS_INVALID_FUEL_YARD_ID, dlgOptions);
    return;
  }

  var selectedIds = [];
  var selectedNames = [];

  selectedObjs.forEach(function(el) {
    var objective = JSON.parse(el.getAttribute("fuel_yard_idName").replaceAll('$DQUOTE$', '"'));
    var val = objective.id || "";
    var disp = objective.yard_code || "";

    selectedIds.push(val);
    selectedNames.push(disp);
  });


  // Radio: Store single value in attribute (0 index)
  lossFuel_yard_id.value = selectedNames[0];
  lossFuel_yard_id.setAttribute("Fuel_yard_id", selectedIds[0]);
  selectedFuel_yard_idId = selectedIds[0];

  lossFuel_yard_id.dispatchEvent(new Event('change'));
  clCommon.hide(fuel_yard_idPnl);
  clCommon.show(formView);
  closeLookupView(fuel_yard_idPnl);
}

function onSearchFuel_yard_id() {
  const searchInput = document.getElementById('searchFuel_yard_idBox');
  if (fuel_yard_idTable && searchInput) {
    fuel_yard_idTable.search(searchInput.value).draw();
  }
}

function onCancelFuel_yard_idBtn(e) {
  clCommon.hide(fuel_yard_idPnl);
  clCommon.show(formView);
  closeLookupView(fuel_yard_idPnl);
}

function onFuel_yard_idMobBackBtn(e) {
  history.back();
}