/*
    Generated BY    : Steps Code Generator
    Generated On    : Mon Jan 26 2026 17:13:31 GMT+0530 (India Standard Time)
    Description     : Service API for BCSFuel
    Version         : 2024.09

    WARNING         : DO NOT EDIT THIS FILE. This file is generated, any changes may be overwritten.
*/



var Service = {

	/*Generated By - cl_service.js - cmastergetws - getunit.json*/
	//Function to get Unit details
	"getUnit": function(onServiceCallback)
	{
		RemoteService.getUnit(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getunit.json*/


	/*Generated By - cl_service.js - cmastergetws - getcode.json*/
	//Function to get Code details
	"getCode": function(onServiceCallback)
	{
		RemoteService.getCode(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getcode.json*/


	/*Generated By - cl_service.js - cmastergetws - getvendor.json*/
	//Function to get Vendor details
	"getVendor": function(onServiceCallback)
	{
		RemoteService.getVendor(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getvendor.json*/


	/*Generated By - cl_service.js - cmastergetws - getutilizationpoint.json*/
	//Function to get UtilizationPoint details
	"getUtilizationPoint": function(onServiceCallback)
	{
		RemoteService.getUtilizationPoint(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getutilizationpoint.json*/


	/*Generated By - cl_service.js - cmastergetws - getyard.json*/
	//Function to get Yard details
	"getYard": function(onServiceCallback)
	{
		RemoteService.getYard(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getyard.json*/


	/*Generated By - cl_service.js - cmastersavews - saveunit.json*/
	//Function to Save Unit.
	"saveUnit": function(unitObj, onServiceCallback)
	{
		RemoteService.saveUnit(unitObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - saveunit.json*/


	/*Generated By - cl_service.js - cmastersavews - savecode.json*/
	//Function to Save Code.
	"saveCode": function(codeObj, onServiceCallback)
	{
		RemoteService.saveCode(codeObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - savecode.json*/


	/*Generated By - cl_service.js - cmastersavews - savevendor.json*/
	//Function to Save Vendor.
	"saveVendor": function(vendorObj, onServiceCallback)
	{
		RemoteService.saveVendor(vendorObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - savevendor.json*/


	/*Generated By - cl_service.js - cmastersavews - saveutilizationpoint.json*/
	//Function to Save UtilizationPoint.
	"saveUtilizationPoint": function(utilizationpointObj, onServiceCallback)
	{
		RemoteService.saveUtilizationPoint(utilizationpointObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - saveutilizationpoint.json*/


	/*Generated By - cl_service.js - cmastersavews - saveyard.json*/
	//Function to Save Yard.
	"saveYard": function(yardObj, onServiceCallback)
	{
		RemoteService.saveYard(yardObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - saveyard.json*/


	/*Generated By - cl_service.js - createws - createpurchasedata.json*/
	//Function to create Purchase.
	"createPurchaseData": function(purchaseObj, onServiceCallback)
	{
		RemoteService.createPurchaseData(purchaseObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - createws - createpurchasedata.json*/


	/*Generated By - cl_service.js - updatews - updatepurchase.json*/
	//Function to update UpdatePurchaseData.
	"updatePurchaseData": function(purchaseObj, onServiceCallback)
	{
		RemoteService.updatePurchaseData(purchaseObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - updatews - updatepurchase.json*/


	/*Generated By - cl_service.js - deletews - deletepurchase.json*/
	//Function to delete purchase.
	"deletePurchaseData": function(purchase_id, onServiceCallback)
	{
		RemoteService.deletePurchaseData(purchase_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - deletews - deletepurchase.json*/


	/*Generated By - cl_service.js - readws - getpurchase.json*/
	//Function to get GetPurchaseData.
	"getPurchaseData": function(purchase_id, onServiceCallback)
	{
		RemoteService.getPurchaseData(purchase_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - readws - getpurchase.json*/


	/*Generated By - cl_service.js - readallws - getallpurchase.json*/
	//Function to get all GetAllPurchaseData details
	"getAllPurchaseData": function(offset, limit, onServiceCallback)
	{
		RemoteService.getAllPurchaseData(offset, limit, function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - readallws - getallpurchase.json*/


	/*Generated By - cl_service.js - queryws - getpurchasebyfilter.json*/
	// Function to get all the purchase by Filter.
	"getPurchaseByFilter": function(start_date, end_date, fuel_code_id, offset, limit, onServiceCallback)
	{
		RemoteService.getPurchaseByFilter(start_date, end_date, fuel_code_id, offset, limit, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - queryws - getpurchasebyfilter.json*/


	/*Generated By - cl_service.js - createws - createconsumptiondata.json*/
	//Function to create Consumption.
	"createConsumptionData": function(consumptionObj, onServiceCallback)
	{
		RemoteService.createConsumptionData(consumptionObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - createws - createconsumptiondata.json*/


	/*Generated By - cl_service.js - readallws - getallconsumptiondata.json*/
	//Function to get all GetAllConsumptionData details
	"getAllConsumptionData": function(offset, limit, onServiceCallback)
	{
		RemoteService.getAllConsumptionData(offset, limit, function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - readallws - getallconsumptiondata.json*/


	/*Generated By - cl_service.js - readws - getconsumption.json*/
	//Function to get GetConsumption.
	"getConsumption": function(consumption_id, onServiceCallback)
	{
		RemoteService.getConsumption(consumption_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - readws - getconsumption.json*/


	/*Generated By - cl_service.js - updatews - updateconsumption.json*/
	//Function to update UpdateConsumptionData.
	"updateConsumptionData": function(consumptionObj, onServiceCallback)
	{
		RemoteService.updateConsumptionData(consumptionObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - updatews - updateconsumption.json*/


	/*Generated By - cl_service.js - deletews - deleteconsumptiondata.json*/
	//Function to delete consumption.
	"deleteConsumptionData": function(consumption_id, onServiceCallback)
	{
		RemoteService.deleteConsumptionData(consumption_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - deletews - deleteconsumptiondata.json*/


	/*Generated By - cl_service.js - queryws - getconsumptionbyfilter.json*/
	// Function to get all the consumption by Filter.
	"getConsumptionByFilter": function(start_date, end_date, fuel_code_id, offset, limit, onServiceCallback)
	{
		RemoteService.getConsumptionByFilter(start_date, end_date, fuel_code_id, offset, limit, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - queryws - getconsumptionbyfilter.json*/


	/*Generated By - cl_service.js - createws - createlossdata.json*/
	//Function to create Loss.
	"createLossData": function(lossObj, onServiceCallback)
	{
		RemoteService.createLossData(lossObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - createws - createlossdata.json*/


	/*Generated By - cl_service.js - readallws - getalllossdata.json*/
	//Function to get all GetAllLossData details
	"getAllLossData": function(offset, limit, onServiceCallback)
	{
		RemoteService.getAllLossData(offset, limit, function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - readallws - getalllossdata.json*/


	/*Generated By - cl_service.js - readws - getlossbyid.json*/
	//Function to get GetLoss.
	"getLoss": function(loss_id, onServiceCallback)
	{
		RemoteService.getLoss(loss_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - readws - getlossbyid.json*/


	/*Generated By - cl_service.js - updatews - updatelossdata.json*/
	//Function to update UpdateLossData.
	"updateLossData": function(lossObj, onServiceCallback)
	{
		RemoteService.updateLossData(lossObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - updatews - updatelossdata.json*/


	/*Generated By - cl_service.js - deletews - deletelossdata.json*/
	//Function to delete loss.
	"deleteLossData": function(loss_id, onServiceCallback)
	{
		RemoteService.deleteLossData(loss_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - deletews - deletelossdata.json*/


	/*Generated By - cl_service.js - queryws - getlossbyfilter.json*/
	// Function to get all the loss by Filter.
	"getLossByFilter": function(start_date, end_date, fuel_code_id, offset, limit, onServiceCallback)
	{
		RemoteService.getLossByFilter(start_date, end_date, fuel_code_id, offset, limit, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - queryws - getlossbyfilter.json*/


	/*Generated By - cl_service.js - externalws - getallbusinesspartnerwithoutlimit.json*/
	// Function to get all the businnespartner without any parameters.
	"getAllBusinessPartner": function(onServiceCallback)
	{
		RemoteService.getAllBusinessPartner(function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - externalws - getallbusinesspartnerwithoutlimit.json*/


	/*Generated By - cl_service.js - externalws - getallresourcewithoutlimit.json*/
	// Function to get all the resources without any parameters.
	"getAllResource": function(onServiceCallback)
	{
		RemoteService.getAllResource(function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - externalws - getallresourcewithoutlimit.json*/


	/*Generated By - cl_service.js - createws - createvendor.json*/
	//Function to create Vendor.
	"createVendor": function(vendorObj, onServiceCallback)
	{
		RemoteService.createVendor(vendorObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - createws - createvendor.json*/


	/*Generated By - cl_service.js - deletews - deletevendor.json*/
	//Function to delete vendor.
	"deleteVendor": function(vendor_id, onServiceCallback)
	{
		RemoteService.deleteVendor(vendor_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - deletews - deletevendor.json*/


	/*Generated By - cl_service.js - readws - getvendor.json*/
	//Function to get GetVendorMap.
	"getVendorMap": function(vendor_id, onServiceCallback)
	{
		RemoteService.getVendorMap(vendor_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - readws - getvendor.json*/


	/*Generated By - cl_service.js - readallws - getallvendor.json*/
	//Function to get all GetAllVendor details
	"getAllVendor": function(offset, limit, onServiceCallback)
	{
		RemoteService.getAllVendor(offset, limit, function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - readallws - getallvendor.json*/


	/*Generated By - cl_service.js - updatews - updatevendor.json*/
	//Function to update UpdateVendor.
	"updateVendor": function(vendorObj, onServiceCallback)
	{
		RemoteService.updateVendor(vendorObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - updatews - updatevendor.json*/


	/*Generated By - cl_service.js - createws - createutilizationpoint.json*/
	//Function to create UtilizationPoint.
	"createUtilizationPoint": function(utilizationPointObj, onServiceCallback)
	{
		RemoteService.createUtilizationPoint(utilizationPointObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - createws - createutilizationpoint.json*/


	/*Generated By - cl_service.js - deletews - deleteutilizationpoint.json*/
	//Function to delete utilizationPoint.
	"deleteUtilizationPoint": function(utilizationPoint_id, onServiceCallback)
	{
		RemoteService.deleteUtilizationPoint(utilizationPoint_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - deletews - deleteutilizationpoint.json*/


	/*Generated By - cl_service.js - readws - getutilizationpoint.json*/
	//Function to get GetUtilizationPointMap.
	"getUtilizationPointMap": function(utilizationPoint_id, onServiceCallback)
	{
		RemoteService.getUtilizationPointMap(utilizationPoint_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - readws - getutilizationpoint.json*/


	/*Generated By - cl_service.js - readallws - getallutilizationpoints.json*/
	//Function to get all GetAllUtilizationPoint details
	"getAllUtilizationPoint": function(offset, limit, onServiceCallback)
	{
		RemoteService.getAllUtilizationPoint(offset, limit, function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - readallws - getallutilizationpoints.json*/


	/*Generated By - cl_service.js - updatews - updateutilizationpoint.json*/
	//Function to update UpdateUtilizationPoint.
	"updateUtilizationPoint": function(utilizationPointObj, onServiceCallback)
	{
		RemoteService.updateUtilizationPoint(utilizationPointObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - updatews - updateutilizationpoint.json*/


	/*Generated By - cl_service.js - externalws - getallvendorswithoutlimit.json*/
	// Function to get all the vendor without any parameters.
	"getAllVendorsWithoutLimit": function(onServiceCallback)
	{
		RemoteService.getAllVendorsWithoutLimit(function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - externalws - getallvendorswithoutlimit.json*/


	/*Generated By - cl_service.js - externalws - getallutilizationwithoutlimit.json*/
	// Function to get all the utilizationPoint without any parameters.
	"getAllUtilizationWithoutLimit": function(onServiceCallback)
	{
		RemoteService.getAllUtilizationWithoutLimit(function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - externalws - getallutilizationwithoutlimit.json*/


	/*##APPEND MARKER - DO NOT REMOVE##*/

};