/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Feb 17 2026 10:46:24 GMT+0530 (India Standard Time)
	Description : Combine Master Ui Interface for utilizationPoint
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

var areMastersLoaded = false;

if (typeof TenantUtilizationPointInterface === 'undefined')
	TenantUtilizationPointInterface = {};

var UtilizationPointInterface = {
	onLoad: function() {

		document.querySelector("title").innerHTML = "BCS Fuel";
		document.querySelector("span").innerHTML = "BCS Fuel";

		if (TenantUtilizationPointInterface && TenantUtilizationPointInterface.onLoad)
			return TenantUtilizationPointInterface.onLoad();

	},

	onBeforeLoad: function() {
		//Custom code goes here
		if (areMastersLoaded) {
			return true;
		}
		clCommon.showLoader("listProgress");

		Promise.all([
			getAllCodePromise(),
			getAllUnitPromise(),
			getAllUtilizationPromise()
			//getAllResourcePromise()
		]).then(function() {
			areMastersLoaded = true;
			loadUtilizationPointData();
		}).catch(function(err) {
			s_error(Strings.ERROR_TITLE, Strings.ERROR_LOAD_UTILIZATIONPOINT, dlgOptions);
			clCommon.hideLoader("listProgress");
		});


		if (TenantUtilizationPointInterface && TenantUtilizationPointInterface.onBeforeLoad)
			return TenantUtilizationPointInterface.onBeforeLoad();
		return true;
	},

	onAfterLoad: function(isSuccessful, dataArr) {
		//custom code goes here

		var sheetData = editorSheet.getData();
		var predefinedCols = ["A", "B", "C", "D", "E"];
		var setCols = [2];

		for (var row = 0; row < sheetData.length; row++) {
			var newRow = row + 1;

			for (var idx = 0; idx < setCols.length; idx++) {
				var checkCol = setCols[idx];
				var cellName = predefinedCols[checkCol] + newRow; 
				var newCell = editorSheet.getCell(cellName);

				if (newCell) {
					newCell.classList.add("readonly");
					newCell.setAttribute("contenteditable", "false");
					newCell.style.backgroundColor = "#f2f2f2";
					newCell.style.color = "#718096";
				}
			}
		}

		if (TenantUtilizationPointInterface && TenantUtilizationPointInterface.onAfterLoad)
			return TenantUtilizationPointInterface.onAfterLoad(isSuccessful, dataArr);
		return dataArr;
	},

	onBeforeData: function(svcName, params) {
		//custom code goes here

		if (TenantUtilizationPointInterface && TenantUtilizationPointInterface.onBeforeData)
			return TenantUtilizationPointInterface.onBeforeData(svcName, params);
		return params;
	},

	onAfterData: function(svcName, dataSources) {
		//custom code goes here

		if (TenantUtilizationPointInterface && TenantUtilizationPointInterface.onAfterData)
			return TenantUtilizationPointInterface.onAfterData(svcName, dataSources);
		return dataSources;
	},

	onBeforeSave: function(dataObj) {
		//custom code here

		if (!customValidate()) {
			return false;
		}

		if(!checkIsactive(dataObj)){
			return false;
		}

		if (TenantUtilizationPointInterface && TenantUtilizationPointInterface.onBeforeSave)
			return TenantUtilizationPointInterface.onBeforeSave(dataObj);
		return dataObj;
	},

	onAfterSave: function(isSuccessful, dataObj) {
		//Custom code here
		if (isSuccessful && dataObj.master_data) {
			try {
				var savedRows = JSON.parse(dataObj.master_data);
				if (savedRows && savedRows.length > 0) {
					for (var i = 0; i < savedRows.length; i++) {
						var rowData = savedRows[i];
						var rowNum = i + 1;
						editorSheet.setValue('A' + rowNum, rowData.id, true);
					}
				}
			} catch (e) {
				//console.error("Error updating IDs after save:", e);
			}
		}

		// Reference validation error
		if (dataObj.err_code === 422 && dataObj.refFlag === true) {

			let alertText = '<p>' + Strings.FOREIGN_REFERENCE_EXIST_ON_UTILIZATION;

			let refLabels = [];

			if (dataObj.conflictSources && dataObj.conflictSources.consumption) {
				refLabels.push(Strings.REF_CONSUMPTION);
			}

			if (refLabels.length) {
				alertText += ' ' + refLabels.join(', ');
			}

			alertText += '</p>';
			alertText += '<p>such as:</p>';
			alertText += '<ol class="utilization_prompt_error">';

			dataObj.deletedWithRefArr.forEach(item => {
				const resource = dataSources.getAllResource.find(resource => resource._sid === item.utilization_point);
				alertText += '<li>' + resource.name + '</li>';
			});

			alertText += '</ol>';

			s_info(Strings.VALIDATION_ERROR_TITLE, alertText, dlgOptions);

			clearSheet();

			// Rewrite sheet with safe data
			for (var i = 0; i < dataObj.data.length; i++) {
				var rowId = i + 1;
				editorSheet.setValue('A' + rowId, dataObj.data[i].id, true);
				editorSheet.setValue('B' + rowId, dataObj.data[i].fuel_code_id, true);
				editorSheet.setValue('C' + rowId, dataObj.data[i].fuel_unit_id, true);
				editorSheet.setValue('D' + rowId, dataObj.data[i].utilization_point, true);
				editorSheet.setValue('E' + rowId, dataObj.data[i].description, true);
			}

			return false;
		}


		if (TenantUtilizationPointInterface && TenantUtilizationPointInterface.onAfterSave)
			return TenantUtilizationPointInterface.onAfterSave(isSuccessful, dataObj);
		return dataObj;
	},

	onSheetChanged: function(instance, cell, col, row, value) {
		//Custom code here

		if (col === 1 || col === "1") {
			updateUnitByCode(row, value);
		}

		//DESCRIPTION VALIDATION 
		if (col == 4 || col === "4") {
			if (value && value.length > 100) {
				UtilizationPointInterface._addErrColor(cell);
				cell.setAttribute("title", "Description cannot exceed 100 characters");
			}	else if (value && !/^[a-zA-Z0-9\s]*$/.test(value)) {
				UtilizationPointInterface._addErrColor(cell);
				cell.setAttribute("title","Special characters are not allowed");
			} else {
				UtilizationPointInterface._removeErrColor(cell);
				cell.removeAttribute("title");
			}
		}

		var sheetData = editorSheet.getData();
		var countMap = {};

		for (var r = 0; r < sheetData.length; r++) {
			var code = sheetData[r][1];
			var unit = sheetData[r][2];
			var point = sheetData[r][3];


			if (code && point && unit) {
				// Create a unique key for this combination
				var key = code + "###" + point + "###" + unit;

				if (!countMap[key]) {
					countMap[key] = 0;
				}
				countMap[key]++;
			}
		}

		//Color the cells based on the counts
		for (var r = 0; r < sheetData.length; r++) {
			var rowId = r + 1; 
			var code = sheetData[r][1];
			var unit = sheetData[r][2];
			var point = sheetData[r][3];


			var cellCode = instance.jspreadsheet.getCell('B' + rowId);
			var cellUnit = instance.jspreadsheet.getCell('C' + rowId);
			var cellPoint = instance.jspreadsheet.getCell('D' + rowId);

			if (code && point && unit) {
				var key = code + "###" + point + "###" + unit;

				if (countMap[key] > 1) {
					var errTitle = "This combination of Fuel Code, Utilization point, and Unit already exists";
					if (cellCode) { UtilizationPointInterface._addErrColor(cellCode); cellCode.setAttribute("title", errTitle); }
					if (cellPoint) { UtilizationPointInterface._addErrColor(cellPoint); cellPoint.setAttribute("title", errTitle); }
					if (cellUnit) { UtilizationPointInterface._addErrColor(cellUnit); cellUnit.setAttribute("title", errTitle); }
				}else {
					if (cellCode) { UtilizationPointInterface._removeErrColor(cellCode); cellCode.removeAttribute("title"); }
					if (cellPoint) { UtilizationPointInterface._removeErrColor(cellPoint); cellPoint.removeAttribute("title"); }
					if (cellUnit) { UtilizationPointInterface._removeErrColor(cellUnit); cellUnit.removeAttribute("title"); }
				}
			} else {
				if (cellCode) UtilizationPointInterface._removeErrColor(cellCode);
				if (cellPoint) UtilizationPointInterface._removeErrColor(cellPoint);
				if (cellUnit) UtilizationPointInterface._removeErrColor(cellUnit);
			}
		}



		if (TenantUtilizationPointInterface && TenantUtilizationPointInterface.onSheetChanged)
			return TenantUtilizationPointInterface.onSheetChanged(instance, cell, col, row, value);
		return true;
	},

	_addErrColor: function(cell){
		cell.classList.add("error_value");
	},

	_removeErrColor: function(cell){
		cell.classList.remove("error_value");
	},
};


function updateUnitByCode( row, codeId) {

	if (!codeId || !dataSources || !dataSources.getAllCode) {
		return;
	}

	// Find selected code
	var selectedCode = null;
	for (var i = 0; i < dataSources.getAllCode.length; i++) {
		if (dataSources.getAllCode[i].id === codeId) {
			selectedCode = dataSources.getAllCode[i];
			break;
		}
	}

	if (!selectedCode || !selectedCode.unit) {
		editorSheet.setValueFromCoords(2, row, "");
		editorSheet.options.columns[2].source = [];
		return;
	}

	// Find unit name
	var unitName = "";
	for (var j = 0; j < dataSources.unitName.length; j++) {
		if (dataSources.unitName[j].id === selectedCode.unit) {
			unitName = dataSources.unitName[j].name;
			break;
		}
	}

	// Update unit dropdown source
	editorSheet.options.columns[2].source = [{
		id: selectedCode.unit,
		name: unitName
	}];

	// Auto-fill unit cell
	editorSheet.setValue('C' + (Number(row)+1), selectedCode.unit, true);
}

function getAllCodePromise() {
	return new Promise((resolve, reject) => {
		Service.getCode(function (resultObj) {
			if (resultObj && resultObj.code === 200) {
				var codeArr = resultObj.data || [];
				dataSources = dataSources || {};
				dataSources.getAllCode = JSON.parse(codeArr[0].master_data);

				if (dataSources.getAllCode && dataSources.getAllCode.length > 1) {
					dataSources.getAllCode = clCommon.sort(dataSources.getAllCode, "code");
				}

				dataSources.codeName = [];
				for (var t = 0; t < dataSources.getAllCode.length; t++) {
					try {
						dataSources.getAllCode[t].code = scrypto.decrypt(dataSources.getAllCode[t].code);
					} catch (e) {}
					dataSources.codeName.push({
						"id": dataSources.getAllCode[t].id,
						"name": dataSources.getAllCode[t].code
					});
				}

				if(editorSheet && editorSheet.options && editorSheet.options.columns) {
					editorSheet.options.columns[1].source = dataSources.codeName;
				}
				resolve();
			} else {
				resolve();
			}
		});
	});
}


function getAllUnitPromise() {
	return new Promise((resolve, reject) => {
		Service.getUnit(function (resultObj) {
			if (resultObj && resultObj.code === 200) {
				var unitArr = resultObj.data || [];
				dataSources = dataSources || {};
				dataSources.getAllUnit = JSON.parse(unitArr[0].master_data);

				if (dataSources.getAllUnit && dataSources.getAllUnit.length > 1) {
					dataSources.getAllUnit = clCommon.sort(dataSources.getAllUnit, "unit");
				}

				dataSources.unitName = [];
				for (var t = 0; t < dataSources.getAllUnit.length; t++) {
					try {
						dataSources.getAllUnit[t].unit = scrypto.decrypt(dataSources.getAllUnit[t].unit);
					} catch (e) {}
					dataSources.unitName.push({
						"id": dataSources.getAllUnit[t].id,
						"name": dataSources.getAllUnit[t].unit
					});
				}

				if(editorSheet && editorSheet.options && editorSheet.options.columns) {
					editorSheet.options.columns[2].source = dataSources.unitName;
					//editorSheet.options.columns[3].readOnly = true;
				}
				resolve();
			} else {
				resolve();
			}
		});
	});
}


function getAllUtilizationPromise() {
	return new Promise((resolve, reject) => {
		Service.getAllUtilizationWithoutLimit(function (respObj) {
			if (respObj && respObj.code === 200) {
				var utilizationArr = respObj.data || [];
				dataSources = dataSources || {};

				// Store raw data
				dataSources.getAllUtilizationWithoutLimit = utilizationArr;

				if (dataSources.getAllUtilizationWithoutLimit.length > 1) {
					dataSources.getAllUtilizationWithoutLimit = clCommon.sort(dataSources.getAllUtilizationWithoutLimit, "resources_short_name");
				}

				dataSources.utilizationShortName = [];
				for (var t = 0; t < dataSources.getAllUtilizationWithoutLimit.length; t++) {

					if(dataSources.getAllUtilizationWithoutLimit[t].isactive == false){
						dataSources.getAllUtilizationWithoutLimit[t].resources_short_name += " - Inactive"
					}

					try {
						dataSources.getAllUtilizationWithoutLimit[t].resources_short_name = scrypto.decrypt(dataSources.getAllUtilizationWithoutLimit[t].resources_short_name);
					} catch (e) {
						dataSources.getAllUtilizationWithoutLimit[t].resources_short_name = dataSources.getAllUtilizationWithoutLimit[t].resources_short_name;
					}

					dataSources.utilizationShortName.push({
						"id": dataSources.getAllUtilizationWithoutLimit[t]._sid,
						"name": dataSources.getAllUtilizationWithoutLimit[t].resources_short_name,
						"isactive" : dataSources.getAllUtilizationWithoutLimit[t].isactive
					});
				}

				// Update JSpreadsheet Column
				if(editorSheet && editorSheet.options && editorSheet.options.columns) {
					editorSheet.options.columns[3].source = dataSources.utilizationShortName;
				}
				resolve();
			} else {
				resolve(); 
			}
		});
	});
}




function getAllResourcePromise() {
	return new Promise((resolve, reject) => {
		Service.getAllResource(function (respObj) {

			if (respObj && respObj.code === 200) {
				var resourcesArr = respObj.data || [];
				dataSources = dataSources || {};

				dataSources.getAllResource = resourcesArr;

				if (dataSources.getAllResource && dataSources.getAllResource.length > 1) {
					dataSources.getAllResource = clCommon.sort(dataSources.getAllResource,"name");
				}


				dataSources.resourceName = [];
				for (var t = 0; t < dataSources.getAllResource.length; t++) {
					try {
						dataSources.getAllResource[t].name = scrypto.decrypt(dataSources.getAllResource[t].name);
					} catch (e) {
						dataSources.getAllResource[t].name = dataSources.getAllResource[t].name;
					}
					dataSources.resourceName.push({
						"id": dataSources.getAllResource[t]._sid,
						"name": dataSources.getAllResource[t].name
					});

				}

				if(editorSheet && editorSheet.options && editorSheet.options.columns) {
					editorSheet.options.columns[3].source = dataSources.resourceName;
				}

				resolve();
			} else {
				resolve();
			}
		});
	});
}

function checkIsactive(dataObj) {
	var inactiveRows = [];
	var sheetData = editorSheet.getData();

	for (var row = 0; row < sheetData.length; row++) {
		var rawCodeId   = sheetData[row][1]; // Fuel Code
		var rawUnitId   = sheetData[row][2]; // Fuel Unit
		var rawUtilId = sheetData[row][3]; // Fuel Utilization point


		if (!rawCodeId || !rawUnitId || !rawUtilId) continue;

		for (var utilIdx = 0; utilIdx < dataSources.utilizationShortName.length; utilIdx++) {
			var utilPoint = dataSources.utilizationShortName[utilIdx];

			if (
				rawUtilId == utilPoint.id &&
				utilPoint.isactive === false
			) {
				inactiveRows.push(row + 1); // spreadsheet row number
				break;
			}
		}
	}

	if (inactiveRows.length === 0) {
		return true;
	}
	var msg = Strings.CONFIRM_INACTIVE_UTILIZATION_POINT +
		"<br>" +
		"Inactive Utilization point rows are:<br>" +
		"<ol><li>" +
		inactiveRows.map(r => "Row " + r).join("</li><li>") +
		"</li></ol>";


	s_confirm(Strings.CONFIRM, msg, {
		STR_YES: dlgOptions.STR_YES,
		STR_NO: dlgOptions.STR_NO,

		onYes: function () {
			dataObj.master_data = JSON.stringify(dataObj.master_data);
			clCommon.showLoader("listProgress");

			Service.saveUtilizationPoint(dataObj, function (resultObj) {
				clCommon.hideLoader("listProgress");

				if (resultObj.code === 200) {
					s_toast(Strings.SAVE_UTILIZATIONPOINT_TOAST_SUCCESS);
					return true;
				}
			});
		},

		onNo: function () {
			//return false;
		}
	});

	return false; // block execution until confirm decision

}

function customValidate() {

	var validateError = [];
	var duplicateMap = {};
	var sheetData = editorSheet.getData();

	// 1. Build duplicate map (Fuel Code + Utilization Point + Fuel Unit)
	for (var row = 0; row < sheetData.length; row++) {

		var fuelCode = sheetData[row][1];
		var fuelUnit = sheetData[row][2];
		var utilizationPoint = sheetData[row][3];


		// Skip incomplete rows (mandatory validation will handle)
		if (!fuelCode || !utilizationPoint || !fuelUnit) continue;

		var uniqueKey = [fuelCode, utilizationPoint, fuelUnit]
		.map(function (val) {
			return String(val).trim().toLowerCase().replace(/\s+/g, "");
		})
		.join("|");

		if (!duplicateMap[uniqueKey]) {
			duplicateMap[uniqueKey] = [row + 1];
		} else {
			duplicateMap[uniqueKey].push(row + 1);
		}
	}

	// 2. Row-wise validation
	for (var row = 0; row < sheetData.length; row++) {

		var errorStr = "";

		function addError(error) {
			errorStr += error + "<br>";
		}

		var id = sheetData[row][0];
		var fuelCode = (sheetData[row][1] || "").trim();
		var fuelUnit = (sheetData[row][2] || "").trim();
		var utilizationPoint = (sheetData[row][3] || "").trim();
		var description = (sheetData[row][4] || "").trim();

		// Skip completely empty rows
		if (!id && !fuelCode && !utilizationPoint && !fuelUnit && !description) {
			continue;
		}

		// Mandatory validations
		if (!fuelCode) {
			addError(Strings.FUEL_CODE_REQUIRED);
		}

		if (!utilizationPoint) {
			addError(Strings.FUEL_UTILIZATION_POINT_REQUIRED);
		}

		if (!fuelUnit) {
			addError(Strings.FUEL_UNIT_REQUIRED);
		}

		// Description validation (Alphanumeric / max 100 chars)
		if (description) {

			if (description.length > 100) {
				addError(Strings.DESCRIPTION_LENGTH_ERROR);
			}

			var alphaNumericRegex = /^[a-zA-Z0-9\s]+$/;
			if (!alphaNumericRegex.test(description)) {
				addError(Strings.DESCRIPTION_ALPHANUMERIC_ERROR);
			}
		}

		// Combination uniqueness validation
		if (fuelCode && utilizationPoint && fuelUnit) {

			var currentKey = [fuelCode, utilizationPoint, fuelUnit]
			.map(function (val) {
				return String(val).trim().toLowerCase().replace(/\s+/g, "");
			})
			.join("|");

			if (duplicateMap[currentKey] && duplicateMap[currentKey].length > 1) {
				addError(
					Strings.DUPLICATE_FUEL_UTILIZATION_MAPPING +
					" at rows " + duplicateMap[currentKey].join(", ")
				);
			}
		}

		if (errorStr !== "") {

			fuelCode = clCommon.getDataByAttribute(
				dataSources.getAllCode, "id", fuelCode, "code"
			);

			validateError.push({
				row: row + 1,
				code: fuelCode || "-",
				error: errorStr
			});
		}
	}

	// 3. Show validation popup
	if (validateError.length > 0) {

		var alertText = '<p>' + Strings.VALIDATE_FUEL_UTILIZATION_PROMPT + '</p>';
		alertText += '<ol class="fuel_prompt_error">';

		validateError.forEach(function (errorObj) {
			alertText +=
				'<li>' +
				Strings.FUEL_CODE + ': ' + errorObj.code +
				' (Row ' + errorObj.row + ')<br>' +
				Strings.VALIDATION_ERROR + ':<br>' +
				errorObj.error +
				'</li><br>';
		});

		alertText += '</ol>';

		s_info(Strings.VALIDATION_ERROR_TITLE, alertText, dlgOptions);
		return false;
	}

	return true;
}
