/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Feb 16 2026 11:40:28 GMT+0530 (India Standard Time)
	Description : Combine Master Ui for Vendor
	WARNING : DO NOT MODIFY THIS FILE
*/


var currAppName = 'BCSFuel';
var isCustom = false;

var contentView;
var saveVendorBtn;
var editorSheet;
var loadCheck = 0;
var svcCount = 0;
var msCheck = 0;

var language = "EN";
var dlgOptions = {
	"STR_OK": "OK",
	"STR_CANCEL": "Cancel",
	"STR_YES": "Yes",
	"STR_NO": "No"
};

var numberFormat, currencyFormat, onlyNumRegExp, localeCode = null,
	currency = null;
var localeObj = {};
onlyNumRegExp = new RegExp(/^[0-9]*.?[0-9]*$/);

var params;

var tourMsgs = [];

var dataSources = {};

$(document).ready(onApplicationReady);

function onApplicationReady() {
	var qStr = window.location.search;

	if (qStr) {
		params = clCommon.getParams(qStr.substring(1, qStr.length));
	}

	setMenu(document.getElementById('sideMenu'), 'bcsfuel_Vendor');


	clCommon.showLoader('svcProgress');
	var url = "/sauth/getuser";
	clCommon.getSvc(true, url, onUser, onUserError);
}


function initControls() {
	contentView = document.getElementById('contentView');
}


function initSheet() {
	var sheetEl = document.getElementById("editorsheet");
	var data = [
		['']
	];

	editorSheet = jspreadsheet(sheetEl, {
		data: data,
		columns: [{
			type: 'text',
			title: Strings.COL_LABEL_ID,
			width: 1,
			align: 'left',
			wordWrap: false,
			readOnly: true
		},
				  {
					  type: 'dropdown',
					  title: Strings.COL_LABEL_FUEL_CODE,
					  width: 200,
					  align: 'left',
					  wordWrap: true,
					  readOnly: false,
					  source: dataSources.codeName
				  },
				  {
					  type: 'dropdown',
					  title: Strings.COL_LABEL_FUEL_UNIT,
					  width: 150,
					  align: 'left',
					  wordWrap: true,
					  readOnly: false,
					  source: dataSources.unitName
				  },
				  {
					  type: 'dropdown',
					  title: Strings.COL_LABEL_FUEL_VENDOR,
					  width: 250,
					  align: 'left',
					  wordWrap: true,
					  readOnly: false,
					  source: dataSources.vendorName
				  },

				 ],
		text: Strings.JSPREADSHEET_LANG,
		//freezeColumns: 1,
		columnSorting: false,
		allowInsertColumn: false,
		allowRenameColumn: false,
		allowDeleteColumn: false,
		about: false,
		allowExport: false,
		tableOverflow: true,
		lazyLoading: true,
		tableWidth: '100%',
		tableHeight: sheetEl.offsetHeight + 'px',

		onchange: onSheetChangedListener,
		onafterchanges: onAfterSheetChangesListener,
		ondeleterow: onDeleteRowListener,
		onundo: onSheetUndoListener,
		onredo: onSheetRedoListener,
		//onselection: onStepSelect
	});

	var rowLen = 100;

	for (let r = 1; r < rowLen; r++) {
		editorSheet.insertRow();
	}

	var lastColWidth = sheetEl.offsetWidth - 1000 - 70;
	if (lastColWidth > parseInt(editorSheet.getWidth(1)))
		editorSheet.setWidth(1, lastColWidth, 200);
}


function registerEventListeners() {
	saveVendorBtn = document.getElementById('saveVendorBtn');
	saveVendorBtn.addEventListener('click', onSaveVendorBtnClick);
}


/*
	Function is called during onload event
*/
function onUser(resp) {
	clCommon.hideLoader('svcProgress');

	if (resp.code !== 200)
		redirect("/");

	userObj = resp.user;

	document.getElementById('userName').innerHTML = (userObj.firstname ? userObj.firstname : userObj.username);

	clCommon.initLanguage(userObj.realm_lang, function() {
		dlgOptions.STR_OK = clCommon.getString("OK", "OK");
		dlgOptions.STR_CANCEL = clCommon.getString("CANCEL", "Cancel");
		dlgOptions.STR_YES = clCommon.getString("YES", "Yes");
		dlgOptions.STR_NO = clCommon.getString("NO", "No");

		if (typeof VendorInterface === 'undefined')
			VendorInterface = null;

		if (VendorInterface && VendorInterface.onLoad)
			VendorInterface.onLoad();
		initControls();
		registerEventListeners();

		scrypto = new SimpleCrypto(userObj.realm_name);

		var userLocale = userObj.realm_locale ? userObj.realm_locale : localeObj;

		localeCode = userLocale.code ? userLocale.code : "en-IN";
		currency = userLocale.currency ? userLocale.currency : "INR";

		numberFormat = new Intl.NumberFormat(localeCode, {
			style: "decimal"
		});
		currencyFormat = new Intl.NumberFormat(localeCode, {
			style: "currency",
			currency: (typeof slocale !== 'undefined') ? slocale.getLocaleInfo(localeCode).currency_code : currency,
			minimumFractionDigits: 2,
			maximumFractionDigits: 2
		});

		clCommon.showLoader('svcProgress');
		var customAppName = clCommon.getCustomAppName();
		var url = customAppName ? ("/steps/hq/" + customAppName + "/common/appsvc?is_custom=true") : (isCustom ? "./common/appsvc?is_custom=true" : "./common/appsvc");

		//To handle the across app integration
		if (params && params.app) {
			// If the URL already has a "?" in it, append with "&", otherwise with "?"
			url += (url.includes("?") ? "&" : "?") + "app=" + params.app;
		}

		clCommon.getSvc(true, url, onAppUserInfo, onAppUserInfoError);

	});
}

function loadMasters() {

	masterWs = 0;
	callOnLoadFunction();
}

function callOnLoadFunction() {
	if (msCheck == masterWs) {
		initSheet();
		loadVendorData();
		msCheck = 0;
		return;
	}
	setTimeout(() => {
		callOnLoadFunction();
	}, 300);
}


/*
	Function is called during onload event
	This function invoked on error response
*/
function onUserError(resp) {
	clCommon.hideLoader('svcProgress');
	redirect("/sauth/login.html");
}


/*
Function is called to redirect to the url
*/
function redirect(url) {
	window.location.href = url + (language !== "EN" ? ("?l=" + language) : "");
}


/*
	Function is called during onload event on error response
*/
function onAppUserInfo(resp) {
	var noDataElem = document.getElementById("contentNoData");
	var dataElem = document.getElementById("contentData");

	clCommon.hideLoader('svcProgress');

	if (resp.code === 200) {
		if (resp.menuArr) {
			processMenu(resp.menuArr);
			clCommon.appendSystemRoles(document.getElementById('sideMenu'), userObj);
			loadMasters();

			clCommon.show(dataElem);
		} else {
			clCommon.show(noDataElem);
			clCommon.hide(dataElem);
		}
	} else {
		s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
	}
}


/*
	Function is called during onload event on error response
*/
function onAppUserInfoError(resp) {
	clCommon.hideLoader('svcProgress');
	s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
}



function loadVendorData() {
	clearSheet();
	clCommon.showLoader("listProgress");

	var beforeLoad = true;
	if (VendorInterface && VendorInterface.onBeforeLoad)
		beforeLoad = VendorInterface.onBeforeLoad();
	if (beforeLoad == false) {
		return;
	}

	Service.getVendor(function(resultObj) {
		clCommon.hideLoader("listProgress");
		if (resultObj.code == 200) { //On success response
			var dataArr = resultObj.data;

			var isSuccessful = true;

			var masterObj = dataArr[0];
			var masterDataArr = [];
			if (masterObj)
				masterDataArr = JSON.parse(masterObj.master_data);

			dataSources.primary = masterDataArr;
			onLoadSuccessResponse(masterDataArr);


			var dataArr = resultObj.data;
			if (VendorInterface && VendorInterface.onAfterLoad) {
				//Radio buttons are not setting properly, so explicitly handling them with this array
				var radioNodes = document.querySelectorAll('input[type=radio]:checked');
				for (var r = 0; r < radioNodes.length; r++) {
					radioNodes[r].click();
				}
				dataArr = VendorInterface.onAfterLoad(isSuccessful, resultObj.data);
			}


		} else {
			//On Error response
			var isSuccessful = false;

			var dataArr = resultObj.data;
			if (VendorInterface && VendorInterface.onAfterLoad) {
				//Radio buttons are not setting properly, so explicitly handling them with this array
				var radioNodes = document.querySelectorAll('input[type=radio]:checked');
				for (var r = 0; r < radioNodes.length; r++) {
					radioNodes[r].click();
				}
				dataArr = VendorInterface.onAfterLoad(isSuccessful, resultObj.data);
			}


			s_error(Strings.ERROR_TITLE, Strings.ERROR_LOAD_VENDOR, dlgOptions);
		}
	});

}


function onLoadSuccessResponse(dataArr) {
	if (dataArr.length > 0) {
		for (var i = 0; i < dataArr.length; i++) {
			var dataObj = dataArr[i];
			var rowId = i + 1;
			editorSheet.setValue('A' + rowId, dataObj.id, true);
			editorSheet.setValue('B' + rowId, dataObj.fuel_code_id, true);
			editorSheet.setValue('C' + rowId, dataObj.fuel_unit_id, true);
			editorSheet.setValue('D' + rowId, dataObj.fuel_vendor_id, true);

		}


	} else {
		clearSheet();
	}
}

function onSaveVendorBtnClick(e) {
	var masterObj = {
		"master_data": [],
		"edited_by": userObj.username,
		"edited_on": new Date().getTime()
	};
	var sheetData = editorSheet.getData();

	for (var row = 0; row < sheetData.length; row++) {
		var rowData = sheetData[row];
		if (rowData[1] && rowData[1].length > 0) {
			var checkStatus = validate(rowData);
			if (checkStatus == true) {
				var data = {}; // Placeholder for Data object

				data["id"] = rowData[0] || null;
				data["fuel_code_id"] = rowData[1] || null;
				data["fuel_unit_id"] = rowData[2] || null;
				data["fuel_vendor_id"] = rowData[3] || null;


				masterObj.master_data.push(data);
			} else {
				return;
			}
		}
	}


	var VendorObj = true;
	if (VendorInterface && VendorInterface.onBeforeSave)
		VendorObj = VendorInterface.onBeforeSave(masterObj);
	if (VendorObj == false) {
		return;
	}


	masterObj.master_data = JSON.stringify(masterObj.master_data);
	Service.saveVendor(masterObj, function(resultObj) {
		if (resultObj.code == 200) {
			var isSuccessful = true;

			var VendorObj = true;
			if (VendorInterface && VendorInterface.onAfterSave)
				VendorObj = VendorInterface.onAfterSave(isSuccessful, resultObj.data);

			if (VendorObj == false) {
				return;
			}


			//loadVendorData();
			s_toast(Strings.SAVE_VENDOR_TOAST_SUCCESS);
		} else {
			var isSuccessful = false;

			var VendorObj = true;
			if (VendorInterface && VendorInterface.onAfterSave)
				VendorObj = VendorInterface.onAfterSave(isSuccessful, resultObj.data);

			if (VendorObj == false) {
				return;
			}
			s_error(Strings.VENDOR_ERROR_TITLE, Strings.SAVE_VENDOR_ERROR, dlgOptions);
		}
	});
}


function clearSheet() {
	var dataArr = editorSheet.getData();

	for (var d = 0; d < dataArr.length; d++) {
		var dataRow = dataArr[d];
		for (var r in dataRow) {
			dataRow[r] = '';
		}
	}

	this.editorSheet.setData(dataArr);
}


function validate(rowData) {

	if (rowData[1] == null || rowData[1] === '') { //this is to validate fuel_code_id
		s_info(Strings.VALIDATION_ERROR_TITLE, Strings.VENDOR_INVALID_FUEL_CODE_ID, dlgOptions);
		return false;
	}

	return true;
}




function onSheetChangedListener(instance, cell, col, row, value) {

	var returnData = true;
	if (VendorInterface && VendorInterface.onSheetChanged)
		returnData = VendorInterface.onSheetChanged(instance, cell, col, row, value);
	if (returnData == false) {
		return;
	}

}


function onAfterSheetChangesListener(e) {}

function onDeleteRowListener(e) {}

function onSheetUndoListener(e) {}

function onSheetRedoListener(e) {}