/*
    Generated BY    : Steps Code Generator
    Generated On    : Mon Jan 26 2026 17:13:31 GMT+0530 (India Standard Time)
    Description     : Common Utilities Library for BCSFuel
    Version         : 2024.09

    WARNING         : DO NOT EDIT THIS FILE. This file is generated, any changes may be overwritten.
*/


var common_util = {
	"getFormattedDate": function(dtInMillis) {
		var dt = new Date(dtInMillis);
		return ((dt.getDate() < 10) ? "0" + dt.getDate() : dt.getDate()) + "-" + (((dt.getMonth() + 1) < 10) ? "0" + (dt.getMonth() + 1) : (dt.getMonth() + 1)) + "-" + dt.getFullYear();
	},

	/*
  	This function is called by load tasks & overdue tasks
  	parameter dataArr is sent by those functions
  	It sorts the data by duedate
  */
	"dueDateSorter": function(a, b) {
		return a.duedate - b.duedate;
	},

	"setSelectTitleOnChange": function() {
		var selectIpArr = document.querySelectorAll("select");
		for (var s = 0; s < selectIpArr.length; s++) {
			selectIpArr[s].setAttribute('title', selectIpArr[s].options[selectIpArr[s].selectedIndex].text);

			selectIpArr[s].addEventListener('change', function(e) {
				common_util.onSelectChange(this);
			});
		}
	},

	"onSelectChange": function(selectIp) {
		selectIp.setAttribute('title', selectIp.options[selectIp.selectedIndex].text);
	},

	"getParams": function(queryStr) {
		var paramsObj = {};

		if (queryStr.indexOf("=") == -1) {
			return paramsObj;
		}

		var params = queryStr.split("&");
		for (var paramIdx = 0; paramIdx < params.length; paramIdx++) {
			var param = params[paramIdx].split("=");
			param[1] = param[1].replace(new RegExp("\\+", "g"), ' ');
			paramsObj[param[0]] = unescape(param[1]);
		}
		return paramsObj;
	},

	"generateString": function(length) {
		const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
		let result = '';
		const charactersLength = characters.length;
		for (let i = 0; i < length; i++) {
			result += characters.charAt(Math.floor(Math.random() * charactersLength));
		}

		return result;
	},

	"generateShortCode": function() {
		return common_util.generateString(6);
	},

	"convertDatePickerTimeStampToLocaleStartDate": function(UTCmilliseconds) {
		//This fuction converts date picker time stamp in UTC to Locale time stamp of same hour.(Date picker always gives 0th hour of UTC)
		//Hence we add time zone off set
		return UTCmilliseconds + (new Date().getTimezoneOffset() * 60000);
	},

	"convertDatePickerTimeStampToLocaleEndDate": function(UTCmilliseconds) {
		//This fuction converts date picker time stamp in UTC to Locale time stamp of same hour.(Date picker always gives 0th hour of UTC)
		//Hence we add time zone off set
		return this.convertDatePickerTimeStampToLocaleStartDate(UTCmilliseconds) + (24 * 60 * 60000) - 1;
	},

	"convertUTCToLocaleStart": function(UTCmilliseconds) {
		var tmZnOffSet = new Date().getTimezoneOffset();
		return UTCmilliseconds - (tmZnOffSet * 60000);
	},

	"checkDuplicate": function (sheetData, editorSheet) {
		const valueMap = new Map();
		const duplicates = new Map();

		for (let row = 0; row < sheetData.length; row++) {

			const value = sheetData[row][1];//always row 1
			if (!value || value.trim() === "") continue;

			const normalizedValue = String(value).toLowerCase().replace(/\s+/g, ""); 

			if (!valueMap.has(normalizedValue)) {
				valueMap.set(normalizedValue, [row + 1]);
			} else {
				valueMap.get(normalizedValue).push(row + 1);
				duplicates.set(normalizedValue, valueMap.get(normalizedValue));
			}
		}

		return { valueMap, duplicates };
	},

	"setFuelCodeCookie": function() {
		var cookieVal = clCommon.getCookie("fuelCode");

		if (!cookieVal) return;

		try {
			var cObj = JSON.parse(cookieVal);
			var fuelCodeValue = cObj.fuelCode;


			fuelCodeFilter.value = fuelCodeValue;


		} catch (e) {
			console.error(e);
		}
	}
};