/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Mar 03 2026 11:55:21 GMT+0530 (India Standard Time)
	Description : Delete Service Interface for sfmp
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantDeleteSfmpInterface = app.getTenantWSInterface('BCSSteam', 'sfmp/delete');

if (typeof TenantDeleteSfmpInterface === 'undefined')
	TenantDeleteSfmpInterface = {};

module.exports = {
	onLoad: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};


		if (TenantDeleteSfmpInterface && TenantDeleteSfmpInterface.onLoad) {
			rObj = TenantDeleteSfmpInterface.onLoad(params);
		}
		return rObj;
	},

	beforeData: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};

		if (params && params.id) {
			try {
				params.id = JSON.parse(params.id);
			} catch(e) {
				params.id = params.id;
			}

			var refFlag = false;

			var conflictSources = {
				connectivity_status: false,
				sfm_link: false,
				utility: false
			};

			var checkRefQuery = {
				"cols": [
					"sfmp_code_id"
				],
				"filter":[{
					"col": "sfmp_code_id",
					"op": "=",
					"val": params.id
				}]
			};

			// 1. Check SFMP Connectivity Status Table
			var connStatusResp = dsclientUtil.execute(checkRefQuery, "BCSSteam", "BCSSteam_connectivity_status", "query");
			if (connStatusResp && connStatusResp.code === 200 && connStatusResp.data && connStatusResp.data.length > 0) {
				refFlag = true;
				conflictSources.connectivity_status = true;
			}

			// Check SFMP - SFM Link Table
			var sfmLinkResp = dsclientUtil.execute(checkRefQuery, "BCSSteam", "BCSSteam_sfm_link", "query");
			if (sfmLinkResp && sfmLinkResp.code === 200 && sfmLinkResp.data && sfmLinkResp.data.length > 0) {
				refFlag = true;
				conflictSources.sfm_link = true;
			}

			// Check  Utility Data Table 
			var utilityResp = dsclientUtil.execute(checkRefQuery, "BCSSteam", "BCSSteam_utility", "query");
			if (utilityResp && utilityResp.code === 200 && utilityResp.data && utilityResp.data.length > 0) {
				refFlag = true;
				conflictSources.utility = true;
			}

			if (refFlag) {
				rObj.override = true;
				rObj.resp = {
					"code" : 400,
					"msg" : Strings.FOREGIN_REFERENCE_FOUND || "Cannot delete SFMP. It is currently referenced.",
					"err_code" : 422,
					"refFlag": refFlag,
					"conflictSources": conflictSources
				};
			}
		}

		if (TenantDeleteSfmpInterface && TenantDeleteSfmpInterface.beforeData) {
			rObj = TenantDeleteSfmpInterface.beforeData(params);
		}
		return rObj;
	},

	beforeExecute: function(queryParams) {
		//custom code here

		if (TenantDeleteSfmpInterface && TenantDeleteSfmpInterface.beforeExecute) {
			queryParams = TenantDeleteSfmpInterface.beforeExecute(queryParams);
		}
		return queryParams;
	},

	afterData: function(respObj) {


		if (TenantDeleteSfmpInterface && TenantDeleteSfmpInterface.afterData) {
			deleteSfmpData = TenantDeleteSfmpInterface.afterData(deleteSfmpData);
		}
		return respObj;
	},

	onError: function(errorObj) {

		if (TenantDeleteSfmpInterface && TenantDeleteSfmpInterface.onError) {
			errorObj = TenantDeleteSfmpInterface.onError(errorObj);
		}
		return errorObj;
	}
};