/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Mar 03 2026 11:56:39 GMT+0530 (India Standard Time)
	Description : Get All Service Interface for sfmp
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetAllSfmpInterface = app.getTenantWSInterface('BCSSteam', 'sfmp/getall');

if (typeof TenantGetAllSfmpInterface === 'undefined')
  TenantGetAllSfmpInterface = {};

module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };

    if (TenantGetAllSfmpInterface && TenantGetAllSfmpInterface.onLoad) {
      rObj = TenantGetAllSfmpInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetAllSfmpInterface && TenantGetAllSfmpInterface.beforeData) {
      rObj = TenantGetAllSfmpInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams) {
    //custom code here

    if (TenantGetAllSfmpInterface && TenantGetAllSfmpInterface.beforeExecute) {
      queryParams = TenantGetAllSfmpInterface.beforeExecute(queryParams);
    }
    return queryParams;
  },

  afterData: function(getAllSfmpData) {

    if (TenantGetAllSfmpInterface && TenantGetAllSfmpInterface.afterData) {
      getAllSfmpData = TenantGetAllSfmpInterface.afterData(getAllSfmpData);
    }
    return getAllSfmpData;
  },

  onError: function(errorObj) {

    if (TenantGetAllSfmpInterface && TenantGetAllSfmpInterface.onError) {
      errorObj = TenantGetAllSfmpInterface.onError(errorObj);
    }
    return errorObj;
  }
};