/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Mar 03 2026 11:56:53 GMT+0530 (India Standard Time)
	Description : Get Service Interface for sfmp
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetSfmpInterface = app.getTenantWSInterface('BCSSteam', 'sfmp/get');

if (typeof TenantGetSfmpInterface === 'undefined')
  TenantGetSfmpInterface = {};

module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetSfmpInterface && TenantGetSfmpInterface.onLoad) {
      rObj = TenantGetSfmpInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetSfmpInterface && TenantGetSfmpInterface.beforeData) {
      rObj = TenantGetSfmpInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams) {
    //custom code here

    if (TenantGetSfmpInterface && TenantGetSfmpInterface.beforeExecute) {
      queryParams = TenantGetSfmpInterface.beforeExecute(queryParams);
    }
    return queryParams;
  },


  afterData: function(getSfmpData) {


    if (TenantGetSfmpInterface && TenantGetSfmpInterface.afterData) {
      getSfmpData = TenantGetSfmpInterface.afterData(getSfmpData);
    }
    return getSfmpData;
  },

  onError: function(errorObj) {


    if (TenantGetSfmpInterface && TenantGetSfmpInterface.onError) {
      errorObj = TenantGetSfmpInterface.onError(errorObj);
    }
    return errorObj;
  }
};