/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Mar 03 2026 11:59:01 GMT+0530 (India Standard Time)
	Description : Update Service for sfmp
	WARNING : DO NOT MODIFY THIS FILE
*/

//External library
var dsclientUtil = require('dsclient');


//Internal library
var Strings = require("../common/strings.js");
var appcommon = require("../common/common.js");
var updateSfmpInterface = require("updateinterface.js");

try {

  //Setting cache as null
  $g.response.headers["Cache-Control"] = "max-age=0";
  $g.response.headers["Cache-Control"] = "no-store";


  //Success response object
  var respObj = {
    code: 200,
    msg: Strings.UPDATE_BCSSTEAM_SFMP_SUCCESS
  };


  //Checking whether the request is in query or body
  var params = appcommon.processParams($g.request);
  var paramStr = JSON.stringify(params);

  //check for Language setup 
  if (params && params.l) {
    var filePath = "/common/lang/";
    appcommon.initLanguage(params.l, filePath);
  }


  // Call 'onLoad' method from the Interface with params as the argument
  var onLoadRes;
  if (updateSfmpInterface)
    onLoadRes = updateSfmpInterface.onLoad(params);

  // Check if 'onLoad' override is true
  if (updateSfmpInterface && onLoadRes && onLoadRes.override === true) {
    if (onLoadRes.resp) {
      if (onLoadRes.resp.code) {
        respObj = onLoadRes.resp;
      } else {
        respObj.code = 500;
        respObj.msg = Strings.SERVER_ERROR;
        if (updateSfmpInterface)
          respObj = updateSfmpInterface.onError(respObj);
        console.error("Unexpected server error when updating the sfmp - " + paramStr);
      }
    }
  } else {

    // Calling 'beforeData' method from Interface and passing params as argument
    var beforeDataRes;
    if (updateSfmpInterface)
      beforeDataRes = updateSfmpInterface.beforeData(params);

    // Check if 'override' is true
    if (updateSfmpInterface && beforeDataRes && beforeDataRes.override === true) {
      //Sending request to ds client
      if (beforeDataRes.resp) {
        if (beforeDataRes.resp.code) {
          respObj = beforeDataRes.resp;
        } else {
          respObj.code = 500;
          respObj.msg = Strings.SERVER_ERROR;
          if (updateSfmpInterface)
            respObj = updateSfmpInterface.onError(respObj);
        }
      }
    } else {
      if (updateSfmpInterface && beforeDataRes.params)
        params = beforeDataRes.params;

      //Only if params is there
      if (params && params.data) {


        if (updateSfmpInterface) {
          params = updateSfmpInterface.beforeExecute(params);
        }
        //Sending request to ds client
        respObj = dsclientUtil.execute(params, "BCSSteam", "BCSSteam_sfmp", "update");
      } else {
        respObj.code = 400;
        respObj.msg = Strings.UPDATE_BCSSTEAM_SFMP_ERROR;
      }
    }

    switch (respObj.code) {
      case 200:
        if (updateSfmpInterface)
          respObj.data = updateSfmpInterface.afterData(respObj.data);
        respObj.msg = Strings.UPDATE_BCSSTEAM_SFMP_SUCCESS;
        break;
      case 400:
        respObj.msg = Strings.UPDATE_BCSSTEAM_SFMP_ERROR;
        if (updateSfmpInterface)
          respObj = updateSfmpInterface.onError(respObj);
        console.error("Unable to update the sfmp - " + paramStr);
        break;
      case 403:
        respObj.msg = Strings.ACCESS_DENIED;
        if (updateSfmpInterface)
          respObj = updateSfmpInterface.onError(respObj);
        console.error("User access denied when updating the sfmp - " + paramStr);
        break;
      case 500:
        respObj.msg = Strings.SERVER_ERROR;
        if (updateSfmpInterface)
          respObj = updateSfmpInterface.onError(respObj);
        console.error("Unexpected server error when updating the sfmp - " + paramStr);
        break;
    }

  }


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = respObj.code;
  $g.response.body = JSON.stringify(respObj);

} catch (e) {

  //Error response object
  var errorRespObj = {
    status: 500,
    message: Strings.SERVER_ERROR + " - " + e.message,
    stack: e.stack
  };
  if (updateSfmpInterface)
    errorRespObj = updateSfmpInterface.onError(errorRespObj);
  console.error("Unexpected server error when updating the sfmp - " + paramStr + "-" + errorRespObj.message);


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = errorRespObj.status;
  $g.response.body = JSON.stringify(errorRespObj);

}