/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 05 2026 13:11:01 GMT+0530 (India Standard Time)
	Description : Get Service Interface for sfmReadingReasonCode 
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetSfmReadingReasonCodeInterface = app.getTenantWSInterface('BCSSteam', 'master/getsfmreadingreasoncode');

if (typeof TenantGetSfmReadingReasonCodeInterface === 'undefined')
  TenantGetSfmReadingReasonCodeInterface = {};


module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };

    if (TenantGetSfmReadingReasonCodeInterface && TenantGetSfmReadingReasonCodeInterface.onLoad) {
      rObj = TenantGetSfmReadingReasonCodeInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetSfmReadingReasonCodeInterface && TenantGetSfmReadingReasonCodeInterface.beforeData) {
      rObj = TenantGetSfmReadingReasonCodeInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams, qType) {
    //custom code here

    if (TenantGetSfmReadingReasonCodeInterface && TenantGetSfmReadingReasonCodeInterface.beforeExecute) {
      queryParams = TenantGetSfmReadingReasonCodeInterface.beforeExecute(queryParams, qType);
    }
    return queryParams;
  },

  afterData: function(getSfmReadingReasonCodeData) {


    if (TenantGetSfmReadingReasonCodeInterface && TenantGetSfmReadingReasonCodeInterface.afterData) {
      getSfmReadingReasonCodeData = TenantGetSfmReadingReasonCodeInterface.afterData(getSfmReadingReasonCodeData);
    }
    return getSfmReadingReasonCodeData;
  },

  onError: function(errorObj) {

    if (TenantGetSfmReadingReasonCodeInterface && TenantGetSfmReadingReasonCodeInterface.onError) {
      errorObj = TenantGetSfmReadingReasonCodeInterface.onError(errorObj);
    }
    return errorObj;
  }
};