/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Tue Jan 27 2026 15:04:03 GMT+0530 (India Standard Time)
	Description : Get All Service Interface for consumption
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetAllConsumptionDataInterface = app.getTenantWSInterface('BCSFuel', 'consumption/getAll');

if (typeof TenantGetAllConsumptionDataInterface === 'undefined')
  TenantGetAllConsumptionDataInterface = {};

module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };

    if (TenantGetAllConsumptionDataInterface && TenantGetAllConsumptionDataInterface.onLoad) {
      rObj = TenantGetAllConsumptionDataInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetAllConsumptionDataInterface && TenantGetAllConsumptionDataInterface.beforeData) {
      rObj = TenantGetAllConsumptionDataInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams) {
    //custom code here

    if (TenantGetAllConsumptionDataInterface && TenantGetAllConsumptionDataInterface.beforeExecute) {
      queryParams = TenantGetAllConsumptionDataInterface.beforeExecute(queryParams);
    }
    return queryParams;
  },

  afterData: function(getAllConsumptionDataData) {

    if (TenantGetAllConsumptionDataInterface && TenantGetAllConsumptionDataInterface.afterData) {
      getAllConsumptionDataData = TenantGetAllConsumptionDataInterface.afterData(getAllConsumptionDataData);
    }
    return getAllConsumptionDataData;
  },

  onError: function(errorObj) {

    if (TenantGetAllConsumptionDataInterface && TenantGetAllConsumptionDataInterface.onError) {
      errorObj = TenantGetAllConsumptionDataInterface.onError(errorObj);
    }
    return errorObj;
  }
};