/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 05 2026 10:41:48 GMT+0530 (India Standard Time)
	Description : App Service for BCSSteam
*/

//External library
var auth = require('auth');
var app = require('app');

//Internal library
var Strings = require('strings.js');
var appcommon = require("../common/common.js");

var respObj = {
  code: 200,
  msg: null
};

try {
  //Checking whether the request is in query or body
  var isCustom = false;
  var params = appcommon.processParams($g.request);
  var paramStr = JSON.stringify(params);

  var user = auth.getUser();
  var appName = 'BCSSteam';

  if (params && params.is_custom === 'true') {
    isCustom = true;
  }

  if (params && params.app) {
    appName = params.app;
  }


  var roleArr = app.getAppRolesByUserId(user.id, appName, null, isCustom);
  var menuArr = null;


  if (roleArr)
    menuArr = app.getMenuByRole(roleArr, appName, isCustom, user);

  if (user) {
    respObj.user = user;
    respObj.roleArr = roleArr;
    respObj.menuArr = menuArr;
  } else {
    respObj.code = 403;
    respObj.msg = Strings.ACCESS_DENIED;
  }

  $g.response.headers["content-type"] = "application/json";
  $g.response.status = respObj.code;
  $g.response.body = JSON.stringify(respObj);

} catch (e) {
  respObj = {
    code: 500,
    msg: Strings.SERVER_ERROR,
    stack: e.stack
  };

  $g.response.headers["content-type"] = "application/json";
  $g.response.status = respObj.code;
  $g.response.body = JSON.stringify(respObj);
}