/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Feb 09 2026 15:02:03 GMT+0530 (India Standard Time)
	Description : Combine Master Ui for size
	WARNING : DO NOT MODIFY THIS FILE
*/


var currAppName = 'BCSSteam';
var isCustom = false;

var contentView;
var saveSizeBtn;
var editorSheet;
var loadCheck = 0;
var svcCount = 0;
var msCheck = 0;

var language = "EN";
var dlgOptions = {
  "STR_OK": "OK",
  "STR_CANCEL": "Cancel",
  "STR_YES": "Yes",
  "STR_NO": "No"
};

var numberFormat, currencyFormat, onlyNumRegExp, localeCode = null,
  currency = null;
var localeObj = {};
onlyNumRegExp = new RegExp(/^[0-9]*.?[0-9]*$/);

var params;

var tourMsgs = [];

var dataSources = {};

$(document).ready(onApplicationReady);

function onApplicationReady() {
  var qStr = window.location.search;

  if (qStr) {
    params = clCommon.getParams(qStr.substring(1, qStr.length));
  }

  setMenu(document.getElementById('sideMenu'), 'bcssteam_size');


  clCommon.showLoader('svcProgress');
  var url = "/sauth/getuser";
  clCommon.getSvc(true, url, onUser, onUserError);
}


function initControls() {
  contentView = document.getElementById('contentView');
}


function initSheet() {
  var sheetEl = document.getElementById("editorsheet");
  var data = [
    ['']
  ];

  editorSheet = jspreadsheet(sheetEl, {
    data: data,
    columns: [{
        type: 'text',
        title: Strings.COL_LABEL_ID,
        width: 1,
        align: 'left',
        wordWrap: false,
        readOnly: true
      },
      {
        type: 'number',
        title: Strings.COL_LABEL_SIZE,
        width: 300,
        align: 'right',
        wordWrap: true,
        readOnly: false
      },

    ],
    text: Strings.JSPREADSHEET_LANG,
    //freezeColumns: 1,
    columnSorting: false,
    allowInsertColumn: false,
    allowRenameColumn: false,
    allowDeleteColumn: false,
    about: false,
    allowExport: false,
    tableOverflow: true,
    lazyLoading: true,
    tableWidth: '100%',
    tableHeight: sheetEl.offsetHeight + 'px',

    onchange: onSheetChangedListener,
    onafterchanges: onAfterSheetChangesListener,
    ondeleterow: onDeleteRowListener,
    onundo: onSheetUndoListener,
    onredo: onSheetRedoListener,
    //onselection: onStepSelect
  });

  var rowLen = 100;

  for (let r = 1; r < rowLen; r++) {
    editorSheet.insertRow();
  }

  var lastColWidth = sheetEl.offsetWidth - 1000 - 70;
  if (lastColWidth > parseInt(editorSheet.getWidth(1)))
    editorSheet.setWidth(1, lastColWidth, 200);
}


function registerEventListeners() {
  saveSizeBtn = document.getElementById('saveSizeBtn');
  saveSizeBtn.addEventListener('click', onSaveSizeBtnClick);
}


/*
	Function is called during onload event
*/
function onUser(resp) {
  clCommon.hideLoader('svcProgress');

  if (resp.code !== 200)
    redirect("/");

  userObj = resp.user;

  document.getElementById('userName').innerHTML = (userObj.firstname ? userObj.firstname : userObj.username);

  clCommon.initLanguage(userObj.realm_lang, function() {
    dlgOptions.STR_OK = clCommon.getString("OK", "OK");
    dlgOptions.STR_CANCEL = clCommon.getString("CANCEL", "Cancel");
    dlgOptions.STR_YES = clCommon.getString("YES", "Yes");
    dlgOptions.STR_NO = clCommon.getString("NO", "No");

    if (typeof SizeInterface === 'undefined')
      SizeInterface = null;

    if (SizeInterface && SizeInterface.onLoad)
      SizeInterface.onLoad();
    initControls();
    registerEventListeners();

    scrypto = new SimpleCrypto(userObj.realm_name);

    var userLocale = userObj.realm_locale ? userObj.realm_locale : localeObj;

    localeCode = userLocale.code ? userLocale.code : "en-IN";
    currency = userLocale.currency ? userLocale.currency : "INR";

    numberFormat = new Intl.NumberFormat(localeCode, {
      style: "decimal"
    });
    currencyFormat = new Intl.NumberFormat(localeCode, {
      style: "currency",
      currency: (typeof slocale !== 'undefined') ? slocale.getLocaleInfo(localeCode).currency_code : currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    });

    clCommon.showLoader('svcProgress');
    var customAppName = clCommon.getCustomAppName();
    var url = customAppName ? ("/steps/hq/" + customAppName + "/common/appsvc?is_custom=true") : (isCustom ? "./common/appsvc?is_custom=true" : "./common/appsvc");

    //To handle the across app integration
    if (params && params.app) {
      // If the URL already has a "?" in it, append with "&", otherwise with "?"
      url += (url.includes("?") ? "&" : "?") + "app=" + params.app;
    }

    clCommon.getSvc(true, url, onAppUserInfo, onAppUserInfoError);

  });
}

function loadMasters() {

  masterWs = 0;
  callOnLoadFunction();
}

function callOnLoadFunction() {
  if (msCheck == masterWs) {
    initSheet();
    loadSizeData();
    msCheck = 0;
    return;
  }
  setTimeout(() => {
    callOnLoadFunction();
  }, 300);
}


/*
	Function is called during onload event
	This function invoked on error response
*/
function onUserError(resp) {
  clCommon.hideLoader('svcProgress');
  redirect("/sauth/login.html");
}


/*
Function is called to redirect to the url
*/
function redirect(url) {
  window.location.href = url + (language !== "EN" ? ("?l=" + language) : "");
}


/*
	Function is called during onload event on error response
*/
function onAppUserInfo(resp) {
  var noDataElem = document.getElementById("contentNoData");
  var dataElem = document.getElementById("contentData");

  clCommon.hideLoader('svcProgress');

  if (resp.code === 200) {
    if (resp.menuArr) {
      processMenu(resp.menuArr);
      clCommon.appendSystemRoles(document.getElementById('sideMenu'), userObj);
      loadMasters();

      clCommon.show(dataElem);
    } else {
      clCommon.show(noDataElem);
      clCommon.hide(dataElem);
    }
  } else {
    s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
  }
}


/*
	Function is called during onload event on error response
*/
function onAppUserInfoError(resp) {
  clCommon.hideLoader('svcProgress');
  s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
}



function loadSizeData() {
  clearSheet();
  clCommon.showLoader("listProgress");

  var beforeLoad = true;
  if (SizeInterface && SizeInterface.onBeforeLoad)
    beforeLoad = SizeInterface.onBeforeLoad();
  if (beforeLoad == false) {
    return;
  }

  Service.getSize(function(resultObj) {
    clCommon.hideLoader("listProgress");
    if (resultObj.code == 200) { //On success response
      var dataArr = resultObj.data;

      var isSuccessful = true;

      var masterObj = dataArr[0];
      var masterDataArr = [];
      if (masterObj)
        masterDataArr = JSON.parse(masterObj.master_data);

      dataSources.primary = masterDataArr;
      onLoadSuccessResponse(masterDataArr);


      var dataArr = resultObj.data;
      if (SizeInterface && SizeInterface.onAfterLoad) {
        //Radio buttons are not setting properly, so explicitly handling them with this array
        var radioNodes = document.querySelectorAll('input[type=radio]:checked');
        for (var r = 0; r < radioNodes.length; r++) {
          radioNodes[r].click();
        }
        dataArr = SizeInterface.onAfterLoad(isSuccessful, resultObj.data);
      }


    } else {
      //On Error response
      var isSuccessful = false;

      var dataArr = resultObj.data;
      if (SizeInterface && SizeInterface.onAfterLoad) {
        //Radio buttons are not setting properly, so explicitly handling them with this array
        var radioNodes = document.querySelectorAll('input[type=radio]:checked');
        for (var r = 0; r < radioNodes.length; r++) {
          radioNodes[r].click();
        }
        dataArr = SizeInterface.onAfterLoad(isSuccessful, resultObj.data);
      }


      s_error(Strings.ERROR_TITLE, Strings.ERROR_LOAD_SIZE, dlgOptions);
    }
  });

}


function onLoadSuccessResponse(dataArr) {
  if (dataArr.length > 0) {
    for (var i = 0; i < dataArr.length; i++) {
      var dataObj = dataArr[i];
      var rowId = i + 1;
      editorSheet.setValue('A' + rowId, dataObj.id, true);
      editorSheet.setValue('B' + rowId, dataObj.size, true);

    }


  } else {
    clearSheet();
  }
}

function onSaveSizeBtnClick(e) {
  var masterObj = {
    "master_data": [],
    "edited_by": userObj.username,
    "edited_on": new Date().getTime()
  };
  var sheetData = editorSheet.getData();

  for (var row = 0; row < sheetData.length; row++) {
    var rowData = sheetData[row];
    if (rowData[1] && rowData[1].length > 0) {
      var checkStatus = validate(rowData);
      if (checkStatus == true) {
        var data = {}; // Placeholder for Data object

        data["id"] = rowData[0] || null;
        data["size"] = rowData[1] || null;


        masterObj.master_data.push(data);
      } else {
        return;
      }
    }
  }


  var sizeObj = true;
  if (SizeInterface && SizeInterface.onBeforeSave)
    sizeObj = SizeInterface.onBeforeSave(masterObj);
  if (sizeObj == false) {
    return;
  }


  masterObj.master_data = JSON.stringify(masterObj.master_data);
  Service.saveSize(masterObj, function(resultObj) {
    if (resultObj.code == 200) {
      var isSuccessful = true;

      var sizeObj = true;
      if (SizeInterface && SizeInterface.onAfterSave)
        sizeObj = SizeInterface.onAfterSave(isSuccessful, resultObj.data);

      if (sizeObj == false) {
        return;
      }


      //loadSizeData();
      s_toast(Strings.SAVE_SIZE_TOAST_SUCCESS);
    } else {
      s_error(Strings.SIZE_ERROR_TITLE, Strings.SAVE_SIZE_ERROR, dlgOptions);
    }
  });
}


function clearSheet() {
  var dataArr = editorSheet.getData();

  for (var d = 0; d < dataArr.length; d++) {
    var dataRow = dataArr[d];
    for (var r in dataRow) {
      dataRow[r] = '';
    }
  }

  this.editorSheet.setData(dataArr);
}


function validate(rowData) {

  if (rowData[1] == null || rowData[1] === '') { //this is to validate size
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.SIZE_INVALID_SIZE, dlgOptions);
    return false;
  }

  return true;
}




function onSheetChangedListener(instance, cell, col, row, value) {

  var returnData = true;
  if (SizeInterface && SizeInterface.onSheetChanged)
    returnData = SizeInterface.onSheetChanged(instance, cell, col, row, value);
  if (returnData == false) {
    return;
  }

}


function onAfterSheetChangesListener(e) {}

function onDeleteRowListener(e) {}

function onSheetUndoListener(e) {}

function onSheetRedoListener(e) {}