/*
    Generated BY    : Steps Code Generator
    Generated On    : Mon Jan 05 2026 10:41:48 GMT+0530 (India Standard Time)
    Description     : Service API for BCSSteam
    Version         : 2024.09

    WARNING         : DO NOT EDIT THIS FILE. This file is generated, any changes may be overwritten.
*/



var Service = {

	/*Generated By - cl_service.js - cmastergetws - getworkingprinciple.json*/
	//Function to get WorkingPrinciple details
	"getWorkingPrinciple": function(onServiceCallback)
	{
		RemoteService.getWorkingPrinciple(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getworkingprinciple.json*/


	/*Generated By - cl_service.js - cmastersavews - saveworkingprinciple.json*/
	//Function to Save WorkingPrinciple.
	"saveWorkingPrinciple": function(workingprincipleObj, onServiceCallback)
	{
		RemoteService.saveWorkingPrinciple(workingprincipleObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - saveworkingprinciple.json*/


	/*Generated By - cl_service.js - cmastergetws - getsize.json*/
	//Function to get Size details
	"getSize": function(onServiceCallback)
	{
		RemoteService.getSize(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getsize.json*/


	/*Generated By - cl_service.js - cmastersavews - savesize.json*/
	//Function to Save Size.
	"saveSize": function(sizeObj, onServiceCallback)
	{
		RemoteService.saveSize(sizeObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - savesize.json*/


	/*Generated By - cl_service.js - cmastergetws - getinputpower.json*/
	//Function to get InputPower details
	"getInputPower": function(onServiceCallback)
	{
		RemoteService.getInputPower(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getinputpower.json*/


	/*Generated By - cl_service.js - cmastersavews - saveinputpower.json*/
	//Function to Save InputPower.
	"saveInputPower": function(inputPowerObj, onServiceCallback)
	{
		RemoteService.saveInputPower(inputPowerObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - saveinputpower.json*/


	/*Generated By - cl_service.js - cmastergetws - getoutputsignal.json*/
	//Function to get OutputSignal details
	"getOutputSignal": function(onServiceCallback)
	{
		RemoteService.getOutputSignal(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getoutputsignal.json*/


	/*Generated By - cl_service.js - cmastersavews - saveoutputsignal.json*/
	//Function to Save OutputSignal.
	"saveOutputSignal": function(outputSignalObj, onServiceCallback)
	{
		RemoteService.saveOutputSignal(outputSignalObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - saveoutputsignal.json*/


	/*Generated By - cl_service.js - cmastergetws - getsfmreadingreasoncode.json*/
	//Function to get SfmReadingReasonCode details
	"getSfmReadingReasonCode": function(onServiceCallback)
	{
		RemoteService.getSfmReadingReasonCode(function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - cmastergetws - getsfmreadingreasoncode.json*/


	/*Generated By - cl_service.js - cmastersavews - savereadingreasoncode.json*/
	//Function to Save SfmReadingReasonCode.
	"saveSfmReadingReasonCode": function(sfmReadingReasonCodeObj, onServiceCallback)
	{
		RemoteService.saveSfmReadingReasonCode(sfmReadingReasonCodeObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - cmastersavews - savereadingreasoncode.json*/


	/*Generated By - cl_service.js - readallws - getallvendor.json*/
	//Function to get all GetAllVendor details
	"getAllVendor": function(offset, limit, onServiceCallback)
	{
		RemoteService.getAllVendor(offset, limit, function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - readallws - getallvendor.json*/


	/*Generated By - cl_service.js - readws - getvendor.json*/
	//Function to get GetVendor.
	"getVendor": function(vendor_id, onServiceCallback)
	{
		RemoteService.getVendor(vendor_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - readws - getvendor.json*/


	/*Generated By - cl_service.js - createws - createvendor.json*/
	//Function to create Vendor.
	"createVendor": function(vendorObj, onServiceCallback)
	{
		RemoteService.createVendor(vendorObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - createws - createvendor.json*/


	/*Generated By - cl_service.js - updatews - updatevendor.json*/
	//Function to update UpdateVendor.
	"updateVendor": function(vendorObj, onServiceCallback)
	{
		RemoteService.updateVendor(vendorObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - updatews - updatevendor.json*/


	/*Generated By - cl_service.js - deletews - deletevendor.json*/
	//Function to delete vendor.
	"deleteVendor": function(vendor_id, onServiceCallback)
	{
		RemoteService.deleteVendor(vendor_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - deletews - deletevendor.json*/


	/*Generated By - cl_service.js - readallws - getallsfm.json*/
	//Function to get all GetAllSfm details
	"getAllSfm": function(offset, limit, onServiceCallback)
	{
		RemoteService.getAllSfm(offset, limit, function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - readallws - getallsfm.json*/


	/*Generated By - cl_service.js - readws - getsfm.json*/
	//Function to get GetSfm.
	"getSfm": function(sfm_id, onServiceCallback)
	{
		RemoteService.getSfm(sfm_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - readws - getsfm.json*/


	/*Generated By - cl_service.js - createws - createsfm.json*/
	//Function to create Sfm.
	"createSfm": function(sfmObj, onServiceCallback)
	{
		RemoteService.createSfm(sfmObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - createws - createsfm.json*/


	/*Generated By - cl_service.js - updatews - updatesfm.json*/
	//Function to update UpdateSfm.
	"updateSfm": function(sfmObj, onServiceCallback)
	{
		RemoteService.updateSfm(sfmObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - updatews - updatesfm.json*/


	/*Generated By - cl_service.js - deletews - deletesfm.json*/
	//Function to delete sfm.
	"deleteSfm": function(sfm_id, onServiceCallback)
	{
		RemoteService.deleteSfm(sfm_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - deletews - deletesfm.json*/


	/*Generated By - cl_service.js - queryws - getsfmbyfilter.json*/
	// Function to get all the sfm by Filter.
	"getSfmByFilter": function(start_date, end_date, offset, limit, onServiceCallback)
	{
		RemoteService.getSfmByFilter(start_date, end_date, offset, limit, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - queryws - getsfmbyfilter.json*/


	/*Generated By - cl_service.js - readws - getutility.json*/
	//Function to get GetUtiliy.
	"getUtiliy": function(utility_id, onServiceCallback)
	{
		RemoteService.getUtiliy(utility_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - readws - getutility.json*/


	/*Generated By - cl_service.js - readallws - getallutility.json*/
	//Function to get all GetAllUtility details
	"getAllUtility": function(offset, limit, onServiceCallback)
	{
		RemoteService.getAllUtility(offset, limit, function(respObj)
		{
			onServiceCallback.call(this, respObj);
		});
	},
	/*Generated By - cl_service.js - readallws - getallutility.json*/


	/*Generated By - cl_service.js - createws - createutility.json*/
	//Function to create Utility.
	"createUtility": function(utilityObj, onServiceCallback)
	{
		RemoteService.createUtility(utilityObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - createws - createutility.json*/


	/*Generated By - cl_service.js - updatews - updateutility.json*/
	//Function to update UpdateUtility.
	"updateUtility": function(utilityObj, onServiceCallback)
	{
		RemoteService.updateUtility(utilityObj, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - updatews - updateutility.json*/


	/*Generated By - cl_service.js - deletews - deleteutility.json*/
	//Function to delete utility.
	"deleteUtility": function(utility_id, onServiceCallback)
	{
		RemoteService.deleteUtility(utility_id, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - deletews - deleteutility.json*/


	/*Generated By - cl_service.js - externalws - getallbusnesspartner.json*/
	// Function to get all the businnespartner without any parameters.
	"getAllBusinessPartner": function(onServiceCallback)
	{
		RemoteService.getAllBusinessPartner(function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - externalws - getallbusnesspartner.json*/


	/*Generated By - cl_service.js - externalws - getallvendorswithoutlimit.json*/
	// Function to get all the vendor without any parameters.
	"getAllVendorsWithoutLimit": function(onServiceCallback)
	{
		RemoteService.getAllVendorsWithoutLimit(function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - externalws - getallvendorswithoutlimit.json*/





	/*Generated By - cl_service.js - externalws - getallsfmwithoutlimit.json*/
	// Function to get all the stm without any parameters.
	"getAllSfmWithoutLimit": function(onServiceCallback)
	{
		RemoteService.getAllSfmWithoutLimit(function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - externalws - getallsfmwithoutlimit.json*/


	/*Generated By - cl_service.js - queryws - getutilitybyfilter.json*/
	// Function to get all the utility by Filter.
	"getUtilityByFilter": function(sfm_code_id, start_date, end_date, offset, limit, onServiceCallback)
	{
		RemoteService.getUtilityByFilter(sfm_code_id, start_date, end_date, offset, limit, function(resultObj)
		{
			onServiceCallback.call(this, resultObj);
		});
	},
	/*Generated By - cl_service.js - queryws - getutilitybyfilter.json*/


	/*##APPEND MARKER - DO NOT REMOVE##*/

};