/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Wed Mar 25 2026 11:30:03 GMT+0530 (India Standard Time)
	Description : Combine Master Ui for statusCode
	WARNING : DO NOT MODIFY THIS FILE
*/


var currAppName = 'BCSSteam';
var isCustom = false;
var isGlobal = false;

var contentView;
var saveStatusCodeBtn;
var editorSheet;
var loadCheck = 0;
var svcCount = 0;
var msCheck = 0;

var language = "EN";
var dlgOptions = {
  "STR_OK": "OK",
  "STR_CANCEL": "Cancel",
  "STR_YES": "Yes",
  "STR_NO": "No"
};

var numberFormat, currencyFormat, onlyNumRegExp, localeCode = null,
  currency = null;
var localeObj = {};
onlyNumRegExp = new RegExp(/^[0-9]*.?[0-9]*$/);

var params;

var tourMsgs = [];

var dataSources = {};

$(document).ready(onApplicationReady);

function onApplicationReady() {
  var qStr = window.location.search;

  if (qStr) {
    params = clCommon.getParams(qStr.substring(1, qStr.length));
  }

  setMenu(document.getElementById('sideMenu'), 'bcssteam_statusCode');


  clCommon.showLoader('svcProgress');
  var url = "/sauth/getuser";
  clCommon.getSvc(true, url, onUser, onUserError);
}


function initControls() {
  contentView = document.getElementById('contentView');
}


function initSheet() {
  var sheetEl = document.getElementById("editorsheet");
  var data = [
    ['']
  ];

  editorSheet = jspreadsheet(sheetEl, {
    data: data,
    columns: [{
        type: 'text',
        title: Strings.COL_LABEL_ID,
        width: 1,
        align: 'left',
        wordWrap: false,
        readOnly: true
      },
      {
        type: 'text',
        title: Strings.COL_LABEL_STATUS_CODE,
        width: 300,
        align: 'left',
        wordWrap: true,
        readOnly: false
      },

    ],
    text: Strings.JSPREADSHEET_LANG,
    //freezeColumns: 1,
    columnSorting: false,
    allowInsertColumn: false,
    allowRenameColumn: false,
    allowDeleteColumn: false,
    about: false,
    allowExport: false,
    tableOverflow: true,
    lazyLoading: true,
    tableWidth: '100%',
    tableHeight: sheetEl.offsetHeight + 'px',

    onchange: onSheetChangedListener,
    onafterchanges: onAfterSheetChangesListener,
    ondeleterow: onDeleteRowListener,
    onundo: onSheetUndoListener,
    onredo: onSheetRedoListener,
    //onselection: onStepSelect
  });

  var rowLen = 100;

  for (let r = 1; r < rowLen; r++) {
    editorSheet.insertRow();
  }

  var lastColWidth = sheetEl.offsetWidth - 1000 - 70;
  if (lastColWidth > parseInt(editorSheet.getWidth(1)))
    editorSheet.setWidth(1, lastColWidth, 200);
}


function registerEventListeners() {
  saveStatusCodeBtn = document.getElementById('saveStatusCodeBtn');
  saveStatusCodeBtn.addEventListener('click', onSaveStatusCodeBtnClick);
}


/*
	Function is called during onload event
*/
function onUser(resp) {
  clCommon.hideLoader('svcProgress');

  if (resp.code !== 200)
    redirect("/");

  userObj = resp.user;

  document.getElementById('userName').innerHTML = (userObj.firstname ? userObj.firstname : userObj.username);

  clCommon.initLanguage(userObj.realm_lang, function() {
    dlgOptions.STR_OK = clCommon.getString("OK", "OK");
    dlgOptions.STR_CANCEL = clCommon.getString("CANCEL", "Cancel");
    dlgOptions.STR_YES = clCommon.getString("YES", "Yes");
    dlgOptions.STR_NO = clCommon.getString("NO", "No");

    if (typeof StatusCodeInterface === 'undefined')
      StatusCodeInterface = null;

    if (StatusCodeInterface && StatusCodeInterface.onLoad)
      StatusCodeInterface.onLoad();
    initControls();
    registerEventListeners();

    scrypto = new SimpleCrypto(userObj.realm_name);

    var userLocale = userObj.realm_locale ? userObj.realm_locale : localeObj;

    localeCode = userLocale.code ? userLocale.code : "en-IN";
    currency = userLocale.currency ? userLocale.currency : "INR";

    numberFormat = new Intl.NumberFormat(localeCode, {
      style: "decimal"
    });
    currencyFormat = new Intl.NumberFormat(localeCode, {
      style: "currency",
      currency: (typeof slocale !== 'undefined') ? slocale.getLocaleInfo(localeCode).currency_code : currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    });

    clCommon.showLoader('svcProgress');
    var customAppName = clCommon.getCustomAppName();
    var url = customAppName ? ("/steps/hq/" + customAppName + "/common/appsvc?is_custom=true") : (isCustom ? "./common/appsvc?is_custom=true" : "./common/appsvc");
    url = isGlobal ? url : './common/appsvc';

    //To handle the across app integration
    if (params && params.app) {
      url += (url.includes("?") ? "&" : "?") + "app=" + params.app;
    }

    clCommon.getSvc(true, url, onAppUserInfo, onAppUserInfoError);

  });
}

function loadMasters() {

  masterWs = 0;
  callOnLoadFunction();
}

function callOnLoadFunction() {
  if (msCheck == masterWs) {
    initSheet();
    loadStatusCodeData();
    msCheck = 0;
    return;
  }
  setTimeout(() => {
    callOnLoadFunction();
  }, 300);
}


/*
	Function is called during onload event
	This function invoked on error response
*/
function onUserError(resp) {
  clCommon.hideLoader('svcProgress');
  redirect("/sauth/login.html");
}


/*
Function is called to redirect to the url
*/
function redirect(url) {
  window.location.href = url + (language !== "EN" ? ("?l=" + language) : "");
}


/*
	Function is called during onload event on error response
*/
function onAppUserInfo(resp) {
  var noDataElem = document.getElementById("contentNoData");
  var dataElem = document.getElementById("contentData");

  clCommon.hideLoader('svcProgress');

  if (resp.code === 200) {
    if (resp.menuArr) {
      processMenu(resp.menuArr);
      clCommon.appendSystemRoles(document.getElementById('sideMenu'), userObj);
      loadMasters();

      clCommon.show(dataElem);
    } else {
      clCommon.show(noDataElem);
      clCommon.hide(dataElem);
    }
  } else {
    s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
  }
}


/*
	Function is called during onload event on error response
*/
function onAppUserInfoError(resp) {
  clCommon.hideLoader('svcProgress');
  s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
}



function loadStatusCodeData() {
  clearSheet();
  clCommon.showLoader("listProgress");

  var beforeLoad = true;
  if (StatusCodeInterface && StatusCodeInterface.onBeforeLoad)
    beforeLoad = StatusCodeInterface.onBeforeLoad();
  if (beforeLoad == false) {
    return;
  }

  Service.getStatusCode(function(resultObj) {
    clCommon.hideLoader("listProgress");
    if (resultObj.code == 200) { //On success response
      var dataArr = resultObj.data;

      var isSuccessful = true;

      var masterObj = dataArr[0];
      var masterDataArr = [];
      if (masterObj)
        masterDataArr = JSON.parse(masterObj.master_data);

      dataSources.primary = masterDataArr;
      onLoadSuccessResponse(masterDataArr);


      var dataArr = resultObj.data;
      if (StatusCodeInterface && StatusCodeInterface.onAfterLoad) {
        //Radio buttons are not setting properly, so explicitly handling them with this array
        var radioNodes = document.querySelectorAll('input[type=radio]:checked');
        for (var r = 0; r < radioNodes.length; r++) {
          radioNodes[r].click();
        }
        dataArr = StatusCodeInterface.onAfterLoad(isSuccessful, resultObj.data);
      }


    } else {
      //On Error response
      var isSuccessful = false;

      var dataArr = resultObj.data;
      if (StatusCodeInterface && StatusCodeInterface.onAfterLoad) {
        //Radio buttons are not setting properly, so explicitly handling them with this array
        var radioNodes = document.querySelectorAll('input[type=radio]:checked');
        for (var r = 0; r < radioNodes.length; r++) {
          radioNodes[r].click();
        }
        dataArr = StatusCodeInterface.onAfterLoad(isSuccessful, resultObj.data);
      }


      s_error(Strings.ERROR_TITLE, Strings.ERROR_LOAD_STATUSCODE, dlgOptions);
    }
  });

}


function onLoadSuccessResponse(dataArr) {
  if (dataArr.length > 0) {
    for (var i = 0; i < dataArr.length; i++) {
      var dataObj = dataArr[i];
      var rowId = i + 1;
      editorSheet.setValue('A' + rowId, dataObj.id, true);
      editorSheet.setValue('B' + rowId, dataObj.status_code, true);

    }


  } else {
    clearSheet();
  }
}

function onSaveStatusCodeBtnClick(e) {
  var masterObj = {
    "master_data": [],
    "modified_by": userObj.username,
    "modified_on": new Date().getTime()
  };

  var sheetData = editorSheet.getData();
  var statusCodeArr = [];

  for (var row = 0; row < sheetData.length; row++) {
    var rowData = sheetData[row];

    if (rowData[1] && rowData[1].length > 0) {
      var data = {};
      var rowNum = row + 1;

      // Assign values
      data.id = rowData[0];
      data.status_code = rowData[1];


      // Add internal row number for error reporting
      data._rowNum = rowNum;

      statusCodeArr.push(data);
    }
  }

  var checkStatus = validate(statusCodeArr);

  if (!checkStatus) {
    return;
  }


  var statusCodeObj = true;
  if (StatusCodeInterface && StatusCodeInterface.onBeforeSave)
    statusCodeObj = StatusCodeInterface.onBeforeSave(masterObj);
  if (statusCodeObj == false) {
    return;
  }


  var finalData = [];
  statusCodeArr.forEach(function(item) {
    var cleanItem = Object.assign({}, item);
    delete cleanItem._rowNum;
    finalData.push(cleanItem);
  });

  masterObj.master_data = finalData;

  masterObj.master_data = JSON.stringify(finalData);

  clCommon.showLoader("listProgress");

  Service.saveStatusCode(masterObj, function(resultObj) {
    clCommon.hideLoader("listProgress");
    if (resultObj.code == 200) {
      var isSuccessful = true;

      var statusCodeObj = true;
      if (StatusCodeInterface && StatusCodeInterface.onAfterSave)
        statusCodeObj = StatusCodeInterface.onAfterSave(isSuccessful, resultObj.data);

      if (statusCodeObj == false) {
        return;
      }


      s_toast(Strings.SAVE_STATUSCODE_TOAST_SUCCESS);
      // Optional: Reload data
      // loadStatusCodeData(); 
    } else {
      var isSuccessful = false;

      var statusCodeObj = true;
      if (StatusCodeInterface && StatusCodeInterface.onAfterSave)
        statusCodeObj = StatusCodeInterface.onAfterSave(isSuccessful, resultObj.data);

      if (statusCodeObj == false) {
        return;
      }

      s_error(Strings.STATUSCODE_ERROR_TITLE, Strings.SAVE_STATUSCODE_ERROR, dlgOptions);
    }
  });
}


function clearSheet() {
  var dataArr = editorSheet.getData();

  for (var d = 0; d < dataArr.length; d++) {
    var dataRow = dataArr[d];
    for (var r in dataRow) {
      dataRow[r] = '';
    }
  }

  this.editorSheet.setData(dataArr);
}


function validate(dataArr) {
  var validateError = [];


  var compositeMap = {};
  dataArr.forEach(function(item) {
    var keyParts = [];
    keyParts.push(String(item.status_code || "").trim().toLowerCase());
    var key = keyParts.join("###");
    if (key.length > 0 && key !== "") {
      if (!compositeMap[key]) compositeMap[key] = [];
      compositeMap[key].push(item._rowNum);
    }
  });


  dataArr.forEach(function(statusCodeObj) {
    var errorStr = "";
    var rowNum = statusCodeObj._rowNum;

    function addError(error) {
      errorStr += error + "<br>";
    }

    var rowTitle = statusCodeObj.name || statusCodeObj.status_code || statusCodeObj.id || "-";

    if (StatusCodeInterface && StatusCodeInterface.getRowTitle) {
      var customTitle = StatusCodeInterface.getRowTitle(statusCodeObj, dataSources);
      if (customTitle) rowTitle = customTitle;
    }


    var compKeyParts = [];
    compKeyParts.push(String(statusCodeObj.status_code || "").trim().toLowerCase());
    var compKey = compKeyParts.join("###");
    if (compositeMap[compKey] && compositeMap[compKey].length > 1) {
      addError((Strings.DUPLICATE_COMBINATION || "Duplicate Combination") + " (Rows: " + compositeMap[compKey].join(", ") + ")");
    }


    //Field Level Validations

    if (statusCodeObj.status_code == null || statusCodeObj.status_code === '') {
      addError(Strings.STATUSCODE_INVALID_STATUS_CODE);
    }

    // C. External Interface Validation
    if (StatusCodeInterface && StatusCodeInterface.addValidation) {
      var extErr = StatusCodeInterface.addValidation(statusCodeObj, dataSources);
      if (extErr) errorStr += extErr;
    }

    // Collect Errors
    if (errorStr !== "") {
      validateError.push({
        row: rowNum,
        title: rowTitle,
        error: errorStr
      });
    }
  });

  if (validateError.length > 0) {
    // Use fallback if String is missing
    var promptTitle = (typeof Strings !== 'undefined' && Strings.VALIDATE_STATUSCODE_PROMPT) ? Strings.VALIDATE_STATUSCODE_PROMPT : "Validation Errors";
    var objTitle = (typeof Strings !== 'undefined' && Strings.STATUSCODE_TITLE) ? Strings.STATUSCODE_TITLE : "StatusCode";

    var alertText = '<p>' + promptTitle + '</p>';
    alertText += '<div><ol class="opp_prompt_error">';

    validateError.forEach(function(errorObj) {
      alertText +=
        '<li>' + objTitle + ': ' + errorObj.title +
        ' (Row ' + errorObj.row + ')<br>' +
        '<em><span>' + errorObj.error + '</span></em>' +
        '</li><br>';
    });

    alertText += '</ol></div>';

    s_info(Strings.VALIDATION_ERROR_TITLE || "Alert", alertText, dlgOptions);
    return false;
  }

  return true;
}




function onSheetChangedListener(instance, cell, col, row, value) {

  var returnData = true;
  if (StatusCodeInterface && StatusCodeInterface.onSheetChanged)
    returnData = StatusCodeInterface.onSheetChanged(instance, cell, col, row, value);
  if (returnData == false) {
    return;
  }

}


function onAfterSheetChangesListener(e) {}

function onDeleteRowListener(e) {}

function onSheetUndoListener(e) {}

function onSheetRedoListener(e) {}