/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Thu Mar 05 2026 10:20:53 GMT+0530 (India Standard Time)
	Description : Interface Logic for BCSSteam List Details.
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS.
	Custom code can be writter here.
	Use customDtOpns object to maniuplate data table.
*/
var alphanumericRegex = /^[a-zA-Z0-9 ]+$/;

if (typeof TenantSfmConnectivityOptionInterface === 'undefined')
	TenantSfmConnectivityOptionInterface = {};

var SfmConnectivityOptionInterface = {
	onLoad: function() {
		//Custom code goes here
		document.querySelector("title").innerHTML = "BCS Steam";
		document.querySelector("span").innerHTML = "BCS Steam";

		document.querySelector("span[data-string-key='CREATE_SFMCONNECTIVITYOPTION']").innerHTML = "Create Connectivity Option";
		document.querySelector("span[data-string-key='UPDATE_SFMCONNECTIVITYOPTION']").innerHTML = "Update Connectivity Option";

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onLoad)
			return TenantSfmConnectivityOptionInterface.onLoad();

		return true;
	},

	onBeforeLoad: function(dataSources) {


		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onBeforeLoad)
			return TenantSfmConnectivityOptionInterface.onBeforeLoad();

		return dataSources;
	},

	onAfterLoad: function(dataSources) {



		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onAfterLoad)
			return TenantSfmConnectivityOptionInterface.onAfterLoad(dataSources);

		return dataSources;
	},

	onBeforeData: function(params, dataSources) {

		//Custom code goes here
		clCommon.hide(filterSfmConnectivityOptionBtn);



		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onBeforeData)
			return TenantSfmConnectivityOptionInterface.onBeforeData(params, dataSources);

		return true;
	},

	onAfterData: function(isSuccessful, dataArr, dataSources) {
		//custom code goes here

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onAfterData)
			return TenantSfmConnectivityOptionInterface.onAfterData(isSuccessful, dataArr, dataSources);

		return dataArr;
	},

	renderData: function(value, type, dtObj, meta) {
		//custom code goes here

		var rVal;

		switch(meta.col){
			case 0:
				rVal = Strings.NA_STRING;
				if(value){
					rVal = value;
				}
			case 1:
				rVal = Strings.NA_STRING;
				if(value){
					rVal = value;
				}

				break;

			case 2:
				rVal = Strings.FALSE_STRING;

				if(dtObj.sfm_connectivity_active){
					rVal = Strings.TRUE_STRING;
				}
				break;
		}

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.renderData)
			return TenantSfmConnectivityOptionInterface.renderData(value, type, dtObj, meta);

		return rVal;
	},

	onBeforeCreate: function(dataObj, dataSources) {
		//custom code here

		if (dataObj && dataObj.sfm_connectivity_option) {
			var value = dataObj.sfm_connectivity_option;

			if (value.length > 15) {
				s_info(Strings.ERROR, Strings.INVALID_SFM_CONNECT_OPTION_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFM_CONNECT_OPTION_FORMAT, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfm_connectivity_description) {
			var value = dataObj.sfm_connectivity_description;

			if (value.length > 30) {
				s_info(Strings.ERROR, Strings.INVALID_SFM_CONNECT_OPTION_DESC_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFM_CONNECT_OPTION_DESC_FORMAT, dlgOptions);
				return false;
			}
		}



		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onBeforeCreate)
			return TenantSfmConnectivityOptionInterface.onBeforeCreate(dataObj, dataSources);

		return dataObj;
	},

	onAfterCreate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here

		if(dataObj.err_code === 409){
			clCommon.hideLoader("createProgress");
			clCommon.enable(createSfmConnectivityOptionBtn);
			s_info(Strings.ERROR, Strings.DUPLICATE_SFM_CONNECT_OPTION, dlgOptions);

			return false;
		}

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onAfterCreate)
			return TenantSfmConnectivityOptionInterface.onAfterCreate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeUpdate: function(dataObj, dataSources) {
		//custom code here
		if (dataObj && dataObj.sfm_connectivity_option) {
			var value = dataObj.sfm_connectivity_option;

			if (value.length > 15) {
				s_info(Strings.ERROR, Strings.INVALID_SFM_CONNECT_OPTION_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFM_CONNECT_OPTION_FORMAT, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfm_connectivity_description) {
			var value = dataObj.sfm_connectivity_description;

			if (value.length > 30) {
				s_info(Strings.ERROR, Strings.INVALID_SFM_CONNECT_OPTION_DESC_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFM_CONNECT_OPTION_DESC_FORMAT, dlgOptions);
				return false;
			}
		}



		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onBeforeUpdate)
			return TenantSfmConnectivityOptionInterface.onBeforeUpdate(dataObj, dataSources);

		return dataObj;
	},

	onAfterUpdate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here

		if(dataObj.err_code === 409){
			clCommon.hideLoader("updateProgress");
			clCommon.enable(editSfmConnectivityOptionBtn);
			s_info(Strings.ERROR, Strings.DUPLICATE_SFM_CONNECT_OPTION, dlgOptions);

			return false;
		}


		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onAfterUpdate)
			return TenantSfmConnectivityOptionInterface.onAfterUpdate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeDelete: function(dataObj, dataSources) {
		//custom code here


		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onBeforeDelete)
			return TenantSfmConnectivityOptionInterface.onBeforeDelete(dataObj, dataSources);

		return dataObj;
	},

	onAfterDelete: function(isSuccessful, resultObj, dataSources) {
		//Custom code here
		if(resultObj && resultObj.data && resultObj.data.err_code){
			resultObj = resultObj.data;
		}


		if (resultObj.err_code && resultObj.err_code === 422) {

			if (resultObj.refFlag === true) {

				let alertText = '<p>' + Strings.CONNECTIVITY_OPTION_REFERENCE_EXIST;
				let refLabels = [];

				if (resultObj.conflictSources) {

					if (resultObj.conflictSources.connectivity_status)
						refLabels.push(Strings.REF_CONNECTIVITY_STATUS);

				}

				if (refLabels.length) {
					alertText += ' ' + refLabels.join(', ');
				}

				alertText += '</p>';
				alertText += '<ol class="sfm_connect_option_prompt_error">';
				alertText += '</ol>';

				s_info(Strings.VALIDATION_ERROR_TITLE, alertText, dlgOptions);
				clCommon.hideLoader("removeProgress");

			}
			return false;
		}


		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onAfterDelete)
			return TenantSfmConnectivityOptionInterface.onAfterDelete(isSuccessful, resultObj, dataSources);

		return resultObj;
	},

	onChangeFilter: function(changedFilter) {
		//Custom code here

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onChangeFilter)
			return TenantSfmConnectivityOptionInterface.onChangeFilter(changedFilter);

		return true;
	},

	onSearchChangeFilter: function(searchedFilter) {

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onSearchChangeFilter)
			return TenantSfmConnectivityOptionInterface.onSearchChangeFilter(searchedFilter);

		return true;
	},

	onRowItemClick: function(rowData) {
		//Custom code here

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onRowItemClick)
			return TenantSfmConnectivityOptionInterface.onRowItemClick(rowData);

		return rowData;
	},

	onDisplayForm: function(rowData) {
		//Custom code here

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onDisplayForm)
			return TenantSfmConnectivityOptionInterface.onDisplayForm(rowData);

		return rowData;
	},

	onClearForm: function(defaultObj, dataSources) {
		//Custom code here
		defaultObj.sfm_connectivity_active = true;

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onClearForm)
			return TenantSfmConnectivityOptionInterface.onClearForm(defaultObj, dataSources);

		return defaultObj;
	},

	onFieldFocus: function(focusedField, dataSources) {

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onFieldFocus)
			return TenantSfmConnectivityOptionInterface.onFieldFocus(focusedField, dataSources);

	},


	onFieldChange: function(changedField, dataSources) {

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onFieldChange)
			return TenantSfmConnectivityOptionInterface.onFieldChange(changedField, dataSources);

	},

	onToolBarBtnClick: function(changedField, dataSources) {

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onToolBarBtnClick)
			return TenantSfmConnectivityOptionInterface.onToolBarBtnClick(changedField, dataSources);

	},

	onLookupAddBtnClick: function(attribute, changedField, dataSources) {

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onLookupAddBtnClick)
			return TenantSfmConnectivityOptionInterface.onLookupAddBtnClick(attribute, changedField, dataSources);

	},

	onLookUpData: function(attribute, dataSources) {

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onLookUpData)
			return TenantSfmConnectivityOptionInterface.onLookUpData(attribute, dataSources);

		return true;

	},

	onChangeOfActionSelect: function(changedAction, dataSources) {

		switch (changedAction.value) {}

		if (TenantSfmConnectivityOptionInterface && TenantSfmConnectivityOptionInterface.onChangeOfActionSelect)
			return TenantSfmConnectivityOptionInterface.onChangeOfActionSelect(changedAction, dataSources);

		return true;
	}

};