/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Fri Mar 06 2026 12:06:54 GMT+0530 (India Standard Time)
	Description : Interface Logic for BCSSteam List Details.
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS.
	Custom code can be writter here.
	Use customDtOpns object to maniuplate data table.
*/

var alphanumericRegex = /^[a-zA-Z0-9_-]+$/;
var alphanumericWithSpaceRegex = /^[a-zA-Z0-9 _-]+$/; //as per customer requirement added(-, _)

if (typeof TenantSfmpConnectivityStatusInterface === 'undefined')
	TenantSfmpConnectivityStatusInterface = {};

var SfmpConnectivityStatusInterface = {
	onLoad: function() {
		//Custom code goes here
		document.querySelector("title").innerHTML = "BCS Steam";
		document.querySelector("span").innerHTML = "BCS Steam";

		document.querySelector("span[data-string-key='CREATE_SFMPCONNECTIVITYSTATUS']").innerHTML = "Create Connectivity Status";
		document.querySelector("span[data-string-key='UPDATE_SFMPCONNECTIVITYSTATUS']").innerHTML = "Update Connectivity Status";

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onLoad)
			return TenantSfmpConnectivityStatusInterface.onLoad();

		return true;
	},

	onBeforeLoad: function(dataSources) {
		clCommon.disable(sfmpConnectivityStatusSfmp_description);


		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onBeforeLoad)
			return TenantSfmpConnectivityStatusInterface.onBeforeLoad();

		return dataSources;
	},

	onAfterLoad: function(dataSources) {
		clCommon.hide(sfmp_code_idAddBtn);
		clCommon.hide(sfm_connectivity_option_idAddBtn);

		if (dataSources.getAllSfmConnectOptionWithoutLimit) {
			var connectOptions = dataSources.getAllSfmConnectOptionWithoutLimit;
			for (var optIdx = 0; optIdx < connectOptions.length; optIdx++) {
				var option = connectOptions[optIdx];
				if (option.sfm_connectivity_active === false) {
					option.sfm_connectivity_option += " - Inactive";
				}

				option.name = option.sfm_connectivity_option;
			}
		}


		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onAfterLoad)
			return TenantSfmpConnectivityStatusInterface.onAfterLoad(dataSources);

		return dataSources;
	},

	onBeforeData: function(params, dataSources) {
		//Custom code goes here
		clCommon.hide(filterSfmpConnectivityStatusBtn);



		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onBeforeData)
			return TenantSfmpConnectivityStatusInterface.onBeforeData(params, dataSources);

		return true;
	},

	onAfterData: function(isSuccessful, dataArr, dataSources) {
		//custom code goes here

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onAfterData)
			return TenantSfmpConnectivityStatusInterface.onAfterData(isSuccessful, dataArr, dataSources);

		return dataArr;
	},

	renderData: function(value, type, dtObj, meta) {
		//custom code goes here

		var rVal;

		switch(meta.col){

			case 0 :
				rVal = this._getSfmpCodeName(value);
				break;

			case 1:
				rVal = Strings.NA_STRING;
				if(dtObj.sfmc_ref){
					rVal = dtObj.sfmc_ref;
				}
				break;

			case 2:
				rVal = Strings.NA_STRING;
				if(value){
					rVal = common_util.getFormattedDate(value);
				}
				break;

			case 3:
				rVal = Strings.NA_STRING;
				if(value){
					rVal = common_util.getFormattedDate(value);
				}
				break;

			case 4:
				rVal = Strings.FALSE_STRING;

				if(dtObj.sfmc_active){
					rVal = Strings.TRUE_STRING;
				}
				break;
		}


		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.renderData)
			return TenantSfmpConnectivityStatusInterface.renderData(value, type, dtObj, meta);

		return rVal;
	},

	onBeforeCreate: function(dataObj, dataSources) {
		//custom code here

		if (dataObj && dataObj.sfmc_ref) {
			var value = dataObj.sfmc_ref;

			if (value.length > 10) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_REF_ID_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_REF_ID_FORMAT, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfm_connectivity_option_id) {
			var value = dataObj.sfm_connectivity_option_id;

			if (value.endsWith(" - Inactive")) {
				s_info(Strings.ERROR, Strings.INACTIVE_CONNECTIVITY_OPTION, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfmc_end_date) {
			if (dataObj.sfmc_end_date < dataObj.sfmc_start_date) {
				s_info(Strings.ERROR, Strings.INVALID_ENDDATE, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.remarks) {
			var value = dataObj.remarks;

			if (value.length > 100) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_DESC_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericWithSpaceRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_DESC_FORMAT, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfmc_active == false && !dataObj.sfmc_end_date) {

			s_info(Strings.ERROR, Strings.INVALID_SFMC_END_DATE_REQUIRED, dlgOptions);
			return false;

		}

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onBeforeCreate)
			return TenantSfmpConnectivityStatusInterface.onBeforeCreate(dataObj, dataSources);

		return dataObj;
	},

	onAfterCreate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here

		if (dataObj && dataObj.err_code && dataObj.err_code == 422) {
			clCommon.hideLoader("createProgress");
			clCommon.enable(createSfmpConnectivityStatusBtn);
			s_info(Strings.ERROR, Strings.SFMC_DATE_CONFLICT, dlgOptions);
			return false;
		}


		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onAfterCreate)
			return TenantSfmpConnectivityStatusInterface.onAfterCreate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeUpdate: function(dataObj, dataSources) {
		//custom code here


		if (dataObj && dataObj.sfmc_ref) {
			var value = dataObj.sfmc_ref;

			if (value.length > 10) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_REF_ID_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_REF_ID_FORMAT, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfm_connectivity_option_id) {
			var value = dataObj.sfm_connectivity_option_id;

			for(var codeIdx = 0; codeIdx < dataSources.getAllSfmConnectOptionWithoutLimit.length; codeIdx++){
				var connectObj = dataSources.getAllSfmConnectOptionWithoutLimit[codeIdx];
				if(value == connectObj._sid){
					if (connectObj.sfm_connectivity_option && connectObj.sfm_connectivity_option.endsWith(" - Inactive")) {
						s_info(Strings.ERROR, Strings.INACTIVE_CONNECTIVITY_OPTION, dlgOptions);
						return false;
					}
				}
			}
		}

		if (dataObj && dataObj.sfmc_end_date) {
			if (dataObj.sfmc_end_date < dataObj.sfmc_start_date) {
				s_info(Strings.ERROR, Strings.INVALID_ENDDATE, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.remarks) {
			var value = dataObj.remarks;

			if (value.length > 100) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_DESC_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericWithSpaceRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_DESC_FORMAT, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfmc_active == false && !dataObj.sfmc_end_date) {

			s_info(Strings.ERROR, Strings.INVALID_SFMC_END_DATE_REQUIRED, dlgOptions);
			return false;

		}


		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onBeforeUpdate)
			return TenantSfmpConnectivityStatusInterface.onBeforeUpdate(dataObj, dataSources);

		return dataObj;
	},

	onAfterUpdate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here

		if (dataObj && dataObj.err_code && dataObj.err_code == 422) {
			clCommon.hideLoader("updateProgress");
			clCommon.enable(editSfmpConnectivityStatusBtn);
			s_info(Strings.ERROR, Strings.SFMC_DATE_CONFLICT, dlgOptions);
			return false;
		}


		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onAfterUpdate)
			return TenantSfmpConnectivityStatusInterface.onAfterUpdate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeDelete: function(dataObj, dataSources) {
		//custom code here


		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onBeforeDelete)
			return TenantSfmpConnectivityStatusInterface.onBeforeDelete(dataObj, dataSources);

		return dataObj;
	},

	onAfterDelete: function(isSuccessful, resultObj, dataSources) {
		//Custom code here


		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onAfterDelete)
			return TenantSfmpConnectivityStatusInterface.onAfterDelete(isSuccessful, resultObj, dataSources);

		return resultObj;
	},

	onChangeFilter: function(changedFilter) {
		//Custom code here

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onChangeFilter)
			return TenantSfmpConnectivityStatusInterface.onChangeFilter(changedFilter);

		return true;
	},

	onSearchChangeFilter: function(searchedFilter) {

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onSearchChangeFilter)
			return TenantSfmpConnectivityStatusInterface.onSearchChangeFilter(searchedFilter);

		return true;
	},

	onRowItemClick: function(rowData) {
		//Custom code here

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onRowItemClick)
			return TenantSfmpConnectivityStatusInterface.onRowItemClick(rowData);

		return rowData;
	},

	onDisplayForm: function(rowData) {
		//Custom code here

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onDisplayForm)
			return TenantSfmpConnectivityStatusInterface.onDisplayForm(rowData);

		return rowData;
	},

	onClearForm: function(defaultObj, dataSources) {
		//Custom code here
		defaultObj.sfmc_active = true;

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onClearForm)
			return TenantSfmpConnectivityStatusInterface.onClearForm(defaultObj, dataSources);

		return defaultObj;
	},

	onFieldFocus: function(focusedField, dataSources) {

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onFieldFocus)
			return TenantSfmpConnectivityStatusInterface.onFieldFocus(focusedField, dataSources);

	},


	onFieldChange: function(changedField, dataSources) {

		if (changedField.id === "sfmpConnectivityStatusSfmp_code_id") {


			var selectedCodeId = sfmpConnectivityStatusSfmp_code_id.getAttribute("sfmp_code_id");
			const sfmp = dataSources.getAllSfmpWithoutLimit.find(
				item => item._sid === selectedCodeId
			);

			if (sfmp) {
				sfmpConnectivityStatusSfmp_description.value = sfmp.sfmp_description || "";
			}
		}

		if (changedField.id === "sfmpConnectivityStatusSfmc_end_date" ){
			if(changedField.value) {
				sfmpConnectivityStatusSfmc_active.checked = false;
			}else{
				sfmpConnectivityStatusSfmc_active.checked = true;	
			}
		}

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onFieldChange)
			return TenantSfmpConnectivityStatusInterface.onFieldChange(changedField, dataSources);

	},

	onToolBarBtnClick: function(changedField, dataSources) {

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onToolBarBtnClick)
			return TenantSfmpConnectivityStatusInterface.onToolBarBtnClick(changedField, dataSources);

	},

	onLookupAddBtnClick: function(attribute, changedField, dataSources) {

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onLookupAddBtnClick)
			return TenantSfmpConnectivityStatusInterface.onLookupAddBtnClick(attribute, changedField, dataSources);

	},

	onLookUpData: function(attribute, dataSources) {


		switch (attribute) {
			case "sfm_connectivity_option_id":
				var optionArr = [];
				var optionFlg = false;
				var pushState = (typeof e !== 'undefined' && e !== false);

				var objective = {
					"_sid": sfmpConnectivityStatusSfm_connectivity_option_id.getAttribute("Sfm_connectivity_option_id")
				};

				var items = dataSources.getAllSfmConnectOptionWithoutLimit;

				for (var i = 0; i < items.length; i++) {
					var item = items[i];

					// Logic to check the radio button
					var checked = "";
					if (objective._sid && objective._sid == item._sid) {
						checked = "checked";
						optionFlg = true;
					} else if (rowData && rowData.sfm_connectivity_option_id == item._sid && !optionFlg) {
						checked = "checked";
					}

					if(rowData || (!rowData && !item.name.endsWith(" - Inactive") )){

						optionArr.push({
							"sfm_connectivity_option_idName": '<label for="' + item._sid + '">' + item.sfm_connectivity_option + '</label>',
							"radio": '<input type="radio" name="sfm_connectivity_option_idName" sfm_connectivity_option_idId="' + item._sid + '" sfm_connectivity_option_idName="' + JSON.stringify(item).replaceAll('"', '$' + 'DQUOTE' + '$') + '" ' + checked + '>'
						});
					}
				}

				sfm_connectivity_option_idTable.clear().draw();
				sfm_connectivity_option_idTable.rows.add(optionArr).draw();

				if (clCommon.isMobile() && pushState) {
					window.history.pushState('sfm_connectivity_option_idForm', null, '#sfm_connectivity_option_idsForm');
					clCommon.hide(contentView);
				}

				return false;
		}

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onLookUpData)
			return TenantSfmpConnectivityStatusInterface.onLookUpData(attribute, dataSources);

		return true;

	},

	onChangeOfActionSelect: function(changedAction, dataSources) {

		switch (changedAction.value) {}

		if (TenantSfmpConnectivityStatusInterface && TenantSfmpConnectivityStatusInterface.onChangeOfActionSelect)
			return TenantSfmpConnectivityStatusInterface.onChangeOfActionSelect(changedAction, dataSources);

		return true;
	},
	_getSfmpCodeName : function(value){
		for(var codeIdx = 0; codeIdx < dataSources.getAllSfmpWithoutLimit.length; codeIdx++){
			var sfmpObj = dataSources.getAllSfmpWithoutLimit[codeIdx];
			if(value == sfmpObj._sid){
				value = sfmpObj.sfmp_code;
				rVal = value
				break;
			}else{
				rVal = Strings.NA_STRING;

			}
		}
		return rVal;
	},

};