/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Mar 09 2026 10:53:49 GMT+0530 (India Standard Time)
	Description : Interface Logic for BCSSteam List Details.
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS.
	Custom code can be writter here.
	Use customDtOpns object to maniuplate data table.
*/

var alphanumericRegex = /^[a-zA-Z0-9 ]+$/;

if (typeof TenantSfmStatusInterface === 'undefined')
	TenantSfmStatusInterface = {};

var SfmStatusInterface = {
	onLoad: function() {
		//Custom code goes here

		document.querySelector("title").innerHTML = "BCS Steam";
		document.querySelector("span").innerHTML = "BCS Steam";

		document.querySelector("span[data-string-key='CREATE_SFMSTATUS']").innerHTML = "Create SFM Status";
		document.querySelector("span[data-string-key='UPDATE_SFMSTATUS']").innerHTML = "Update SFM Status";

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onLoad)
			return TenantSfmStatusInterface.onLoad();

		return true;
	},

	onBeforeLoad: function(dataSources) {
		clCommon.disable(sfmStatusSfm_description);


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onBeforeLoad)
			return TenantSfmStatusInterface.onBeforeLoad();

		return dataSources;
	},

	onAfterLoad: function(dataSources) {

		clCommon.hide(sfm_code_idAddBtn);
		clCommon.hide(sfm_status_code_idAddBtn);

		if (dataSources.getAllSfmWithoutLimit) {
			var sfmArr = dataSources.getAllSfmWithoutLimit;
			for (var sfmIdx = 0; sfmIdx < sfmArr.length; sfmIdx++) {
				var sfmObj = sfmArr[sfmIdx];
				if (sfmObj.isactive === false) {
					sfmObj.sfm_code += " - Inactive";
				}

				sfmObj.name = sfmObj.sfm_code ;
			}
		}

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onAfterLoad)
			return TenantSfmStatusInterface.onAfterLoad(dataSources);

		return dataSources;
	},

	onBeforeData: function(params, dataSources) {
		//Custom code goes here
		clCommon.hide(filterSfmStatusBtn);


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onBeforeData)
			return TenantSfmStatusInterface.onBeforeData(params, dataSources);

		return true;
	},

	onAfterData: function(isSuccessful, dataArr, dataSources) {
		//custom code goes here

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onAfterData)
			return TenantSfmStatusInterface.onAfterData(isSuccessful, dataArr, dataSources);

		return dataArr;
	},

	renderData: function(value, type, dtObj, meta) {
		//custom code goes here

		var rVal;

		switch(meta.col){

			case 0 :
				rVal = this._getSfmCodeName(value);
				break;

			case 1:
				rVal = this._getSfmStatusName(value);
				break;

			case 2:
				rVal = Strings.NA_STRING;
				if(value){
					rVal = common_util.getFormattedDate(value);
				}
				break;

			case 3:
				rVal = Strings.NA_STRING;
				if(value){
					rVal = common_util.getFormattedDate(value);
				}
				break;
		}


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.renderData)
			return TenantSfmStatusInterface.renderData(value, type, dtObj, meta);

		return rVal;
	},

	onBeforeCreate: function(dataObj, dataSources) {
		//custom code here

		if (dataObj && dataObj.remarks) {
			var value = dataObj.remarks;

			if (value.length > 100) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_DESC_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_DESC_FORMAT, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.sfms_end_date) {
			if (dataObj.sfms_end_date < dataObj.sfms_start_date) {
				s_info(Strings.ERROR, Strings.INVALID_ENDDATE, dlgOptions);
				return false;
			}
		}


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onBeforeCreate)
			return TenantSfmStatusInterface.onBeforeCreate(dataObj, dataSources);

		return dataObj;
	},

	onAfterCreate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here

		if (dataObj && dataObj.err_code && dataObj.err_code == 422) {
			clCommon.hideLoader("createProgress");
			clCommon.enable(createSfmStatusBtn);
			s_info(Strings.ERROR, Strings.SFMS_DATE_CONFLICT, dlgOptions);
			return false;
		}


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onAfterCreate)
			return TenantSfmStatusInterface.onAfterCreate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeUpdate: function(dataObj, dataSources) {
		//custom code here

		if (dataObj && dataObj.sfm_code_id) {
			var value = dataObj.sfm_code_id;

			for(var codeIdx = 0; codeIdx < dataSources.getAllSfmWithoutLimit.length; codeIdx++){
				var sfmObj = dataSources.getAllSfmWithoutLimit[codeIdx];
				if(value == sfmObj._sid){
					if (sfmObj.name && sfmObj.name.endsWith(" - Inactive")) {
						s_info(Strings.ERROR, Strings.INACTIVE_SFM_CODE, dlgOptions);
						return false;
					}
				}
			}
		}

		if (dataObj && dataObj.sfms_end_date) {
			if (dataObj.sfms_end_date < dataObj.sfms_start_date) {
				s_info(Strings.ERROR, Strings.INVALID_ENDDATE, dlgOptions);
				return false;
			}
		}

		if (dataObj && dataObj.remarks) {
			var value = dataObj.remarks;

			if (value.length > 100) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_DESC_LENGTH, dlgOptions);
				return false;
			}

			if (!alphanumericRegex.test(value)) {
				s_info(Strings.ERROR, Strings.INVALID_SFMP_CONNECT_STATUS_DESC_FORMAT, dlgOptions);
				return false;
			}
		}


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onBeforeUpdate)
			return TenantSfmStatusInterface.onBeforeUpdate(dataObj, dataSources);

		return dataObj;
	},

	onAfterUpdate: function(isSuccessful, dataObj, dataSources) {
		//Custom code here

		if (dataObj && dataObj.err_code && dataObj.err_code == 422) {
			clCommon.hideLoader("updateProgress");
			clCommon.enable(editSfmStatusBtn);
			s_info(Strings.ERROR, Strings.SFMS_DATE_CONFLICT, dlgOptions);
			return false;
		}


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onAfterUpdate)
			return TenantSfmStatusInterface.onAfterUpdate(isSuccessful, dataObj, dataSources);

		return dataObj;
	},

	onBeforeDelete: function(dataObj, dataSources) {
		//custom code here


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onBeforeDelete)
			return TenantSfmStatusInterface.onBeforeDelete(dataObj, dataSources);

		return dataObj;
	},

	onAfterDelete: function(isSuccessful, resultObj, dataSources) {
		//Custom code here


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onAfterDelete)
			return TenantSfmStatusInterface.onAfterDelete(isSuccessful, resultObj, dataSources);

		return resultObj;
	},

	onChangeFilter: function(changedFilter) {
		//Custom code here

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onChangeFilter)
			return TenantSfmStatusInterface.onChangeFilter(changedFilter);

		return true;
	},

	onSearchChangeFilter: function(searchedFilter) {

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onSearchChangeFilter)
			return TenantSfmStatusInterface.onSearchChangeFilter(searchedFilter);

		return true;
	},

	onRowItemClick: function(rowData) {
		//Custom code here

		if(rowData.sfm_code_id){
			for(var idx = 0; idx < dataSources.getAllSfmWithoutLimit.length; idx++){
				if(rowData.sfm_code_id == dataSources.getAllSfmWithoutLimit[idx]._sid){
					rowData.sfm_code_name = dataSources.getAllSfmWithoutLimit[idx].name;
					break;
				}
			}
		}


		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onRowItemClick)
			return TenantSfmStatusInterface.onRowItemClick(rowData);

		return rowData;
	},

	onDisplayForm: function(rowData) {
		//Custom code here

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onDisplayForm)
			return TenantSfmStatusInterface.onDisplayForm(rowData);

		return rowData;
	},

	onClearForm: function(defaultObj, dataSources) {
		//Custom code here

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onClearForm)
			return TenantSfmStatusInterface.onClearForm(defaultObj, dataSources);

		return defaultObj;
	},

	onFieldFocus: function(focusedField, dataSources) {

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onFieldFocus)
			return TenantSfmStatusInterface.onFieldFocus(focusedField, dataSources);

	},


	onFieldChange: function(changedField, dataSources) {

		if (changedField.id === "sfmStatusSfm_code_id") {


			var selectedCodeId = sfmStatusSfm_code_id.getAttribute("sfm_code_id");
			const sfm = dataSources.getAllSfmWithoutLimit.find(
				item => item._sid === selectedCodeId
			);

			if (sfm) {
				sfmStatusSfm_description.value = sfm.sfm_description || "";
			}
		}

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onFieldChange)
			return TenantSfmStatusInterface.onFieldChange(changedField, dataSources);

	},

	onToolBarBtnClick: function(changedField, dataSources) {

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onToolBarBtnClick)
			return TenantSfmStatusInterface.onToolBarBtnClick(changedField, dataSources);

	},

	onLookupAddBtnClick: function(attribute, changedField, dataSources) {

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onLookupAddBtnClick)
			return TenantSfmStatusInterface.onLookupAddBtnClick(attribute, changedField, dataSources);

	},

	onLookUpData: function(attribute, dataSources) {

		switch (attribute) {
			case "sfm_code_id":
				var optionArr = [];
				var optionFlg = false;
				var pushState = (typeof e !== 'undefined' && e !== false);

				var objective = {
					"_sid": sfmStatusSfm_code_id.getAttribute("Sfm_code_id")
				};

				var items = dataSources.getAllSfmWithoutLimit;

				for (var i = 0; i < items.length; i++) {
					var item = items[i];

					// Logic to check the radio button
					var checked = "";
					if (objective._sid && objective._sid == item._sid) {
						checked = "checked";
						optionFlg = true;
					} else if (rowData && rowData.sfm_code_id == item._sid && !optionFlg) {
						checked = "checked";
					}

					if (rowData || (!rowData && !item.name.endsWith(" - Inactive"))) {

						optionArr.push({
							"sfm_code_idName": '<label for="' + item._sid + '">' + item.sfm_code + '</label>',
							"radio": '<input type="radio" name="sfm_code_idName" sfm_code_idId="' + item._sid + '" sfm_code_idName="' + JSON.stringify(item).replaceAll('"', '$' + 'DQUOTE' + '$') + '" ' + checked + '>'
						});
					}
				}

				sfm_code_idTable.clear().draw();
				sfm_code_idTable.rows.add(optionArr).draw();

				if (clCommon.isMobile() && pushState) {
					window.history.pushState('sfm_code_idForm', null, '#sfm_code_idsForm');
					clCommon.hide(contentView);
				}

				return false;
		}

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onLookUpData)
			return TenantSfmStatusInterface.onLookUpData(attribute, dataSources);

		return true;

	},

	onChangeOfActionSelect: function(changedAction, dataSources) {

		switch (changedAction.value) {}

		if (TenantSfmStatusInterface && TenantSfmStatusInterface.onChangeOfActionSelect)
			return TenantSfmStatusInterface.onChangeOfActionSelect(changedAction, dataSources);

		return true;
	},

	_getSfmCodeName : function(value){
		for(var codeIdx = 0; codeIdx < dataSources.getAllSfmWithoutLimit.length; codeIdx++){
			var sfmpObj = dataSources.getAllSfmWithoutLimit[codeIdx];
			if(value == sfmpObj._sid){
				value = sfmpObj.sfm_code;
				rVal = value
				break;
			}else{
				rVal = Strings.NA_STRING;

			}
		}
		return rVal;
	},

	_getSfmStatusName : function(value){
		for(var codeIdx = 0; codeIdx < dataSources.getStatusCode.length; codeIdx++){
			var sfmpObj = dataSources.getStatusCode[codeIdx];
			if(value == sfmpObj.id){
				value = sfmpObj.status_code;
				rVal = value
				break;
			}else{
				rVal = Strings.NA_STRING;

			}
		}
		return rVal;
	},

};