/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Wed Mar 25 2026 11:32:13 GMT+0530 (India Standard Time)
	Description : Client Logic for BCSSteam ListDetails.
	Warning : DON"T TOUCH THE BASE CODE 
*/


var currAppName = 'BCSSteam';
var isCustom = false;
var isGlobal = false;
var msCheck = 0;
var loadCheck = 0;
var contentView, formView, formClose;
var steamFlowMeterPointTable;



var createSteamFlowMeterPointBtn, addSteamFlowMeterPointBtn, cancelBtns, duplicateSteamFlowMeterPointBtn, deleteSteamFlowMeterPointBtn, editSteamFlowMeterPointBtn, importSteamFlowMeterPointBtn, aiAssistantSteamFlowMeterPointBtn;
var cancelCreateBtn, cancelUpdateBtn;
var selectedRow;
var userObj;
var scrypto;
var params;
var rowData;
var backBtn;
var tourMsgs = [];
var primaryArr = [];
var chunkSize = 30;
var currentIndex = 0;
var offset = 0;
var limit = 100;
var limCookieSet = null;
var offCookieSet = null;
var loadMore, loadAll;
var actionsSelect;


var language = "EN";
var dlgOptions = {
  "STR_OK": "OK",
  "STR_CANCEL": "Cancel",
  "STR_YES": "Yes",
  "STR_NO": "No"
};

var filterSteamFlowMeterPointBtn, filterActionsSteamFlowMeterPointBtn;
var selectFilters;
var searchOptsTables = [];
var filterContent;

var numberFormat, currencyFormat, onlyNumRegExp, localeCode = null,
  currency = null;
var localeObj = {};
onlyNumRegExp = new RegExp(/^[0-9]*.?[0-9]*$/);

var actionsSelectOptionsArr = []
var steamFlowMeterPointSfmp_code, steamFlowMeterPointSfmp_description, steamFlowMeterPointSfmp_active;

var dataSources = {};
var customDtOpns = {};
$(document).ready(onApplicationReady);


function onApplicationReady() {
  var qStr = window.location.search;

  if (qStr) {
    params = clCommon.getParams(qStr.substring(1, qStr.length));
  }

  setMenu(document.getElementById('sideMenu'), 'bcssteam_steamFlowMeterPoint');


  clCommon.showLoader('svcProgress');
  var url = "/sauth/getuser";
  clCommon.getSvc(true, url, onUser, onUserError);
}


function initControls() {
  contentView = document.getElementById('contentView');
  formView = document.getElementById('steamFlowMeterPointDetailsPanel');
  formClose = document.getElementById('formClose');
  if (clCommon.isMobile()) {
    clCommon.hide(formClose);
    hideForm();
  } else {
    var formContent = document.querySelector('.form-content-holder');
    formContent.classList.add('expand');
  }

  cancelCreateBtn = document.getElementById('cancelCreateBtn');
  cancelUpdateBtn = document.getElementById('cancelUpdateBtn');

  filterContent = document.getElementById("filterContent");
  selectFilters = document.getElementById("selectFilters");

  // Set initial state of Cancel buttons based on Cookie
  var isFullCookie = clCommon.getCookie("bcssteam_full_view");
  if (isFullCookie === "true") {
    clCommon.show(cancelCreateBtn);
    clCommon.show(cancelUpdateBtn);
  } else {
    clCommon.hide(cancelCreateBtn);
    clCommon.hide(cancelUpdateBtn);
  }

  steamFlowMeterPointSfmp_code = document.getElementById('steamFlowMeterPointSfmp_code');
  steamFlowMeterPointSfmp_description = document.getElementById('steamFlowMeterPointSfmp_description');
  steamFlowMeterPointSfmp_active = document.getElementById('steamFlowMeterPointSfmp_active');

}


function initTable() {
  var dtOpns = { //Funtion to display datatable
    data: [], //Sort array and set data
    scrollY: (document.querySelector(".content-list").offsetHeight - 200) + "px",
    autoWidth: false,
    columns: [{
      data: 'sfmp_code',
      'bSortable': true,
      'type': 'sfmp_code',
      render: renderData,
    }, {
      data: 'sfmp_description',
      'bSortable': true,
      'type': 'sfmp_description',
      render: renderData,
    }, {
      data: 'sfmp_active',
      'bSortable': true,
      'type': 'sfmp_active',
      render: renderData,
    }],
    "columnDefs": [],
    "orderClasses": false,
    "language": Strings.DATA_TABLE_LANG,
    "order": [], //to display the array sorted
    "deferRender": true
  };

  if (clCommon.isMobile())
    delete dtOpns.scrollY;

  if (Object.keys(customDtOpns).length > 0) {
    for (var opn in customDtOpns) {
      dtOpns[opn] = customDtOpns[opn];
    }
  }
  steamFlowMeterPointTable = $('#tableHolder').DataTable(dtOpns);


  jQuery.fn.dataTableExt.oSort["sfmp_code-desc"] = function(x, y) {
    //return getRank(x) < getRank(y);
    var tElem = document.createElement('div');
    tElem.innerHTML = x + y;
    var sX = parseInt(tElem.firstChild.getAttribute("ddval"));
    var sY = parseInt(tElem.lastChild.getAttribute("ddval"));
    var rVal = (sX < sY) ? 1 : -1;
    if (sX === sY)
      rVal = 0;
    delete tElem;
    return rVal;
  };

  jQuery.fn.dataTableExt.oSort["sfmp_code-asc"] = function(x, y) {
    //return getRank(x) > getRank(y);
    var tElem = document.createElement('div');
    tElem.innerHTML = x + y;
    var sX = parseInt(tElem.firstChild.getAttribute("ddval"));
    var sY = parseInt(tElem.lastChild.getAttribute("ddval"));
    var rVal = (sX > sY) ? 1 : -1;
    if (sX === sY)
      rVal = 0;
    return rVal;
  }
  jQuery.fn.dataTableExt.oSort["sfmp_description-desc"] = function(x, y) {
    //return getRank(x) < getRank(y);
    var tElem = document.createElement('div');
    tElem.innerHTML = x + y;
    var sX = parseInt(tElem.firstChild.getAttribute("ddval"));
    var sY = parseInt(tElem.lastChild.getAttribute("ddval"));
    var rVal = (sX < sY) ? 1 : -1;
    if (sX === sY)
      rVal = 0;
    delete tElem;
    return rVal;
  };

  jQuery.fn.dataTableExt.oSort["sfmp_description-asc"] = function(x, y) {
    //return getRank(x) > getRank(y);
    var tElem = document.createElement('div');
    tElem.innerHTML = x + y;
    var sX = parseInt(tElem.firstChild.getAttribute("ddval"));
    var sY = parseInt(tElem.lastChild.getAttribute("ddval"));
    var rVal = (sX > sY) ? 1 : -1;
    if (sX === sY)
      rVal = 0;
    return rVal;
  }
  jQuery.fn.dataTableExt.oSort["sfmp_active-desc"] = function(x, y) {
    //return getRank(x) < getRank(y);
    var tElem = document.createElement('div');
    tElem.innerHTML = x + y;
    var sX = parseInt(tElem.firstChild.getAttribute("ddval"));
    var sY = parseInt(tElem.lastChild.getAttribute("ddval"));
    var rVal = (sX < sY) ? 1 : -1;
    if (sX === sY)
      rVal = 0;
    delete tElem;
    return rVal;
  };

  jQuery.fn.dataTableExt.oSort["sfmp_active-asc"] = function(x, y) {
    //return getRank(x) > getRank(y);
    var tElem = document.createElement('div');
    tElem.innerHTML = x + y;
    var sX = parseInt(tElem.firstChild.getAttribute("ddval"));
    var sY = parseInt(tElem.lastChild.getAttribute("ddval"));
    var rVal = (sX > sY) ? 1 : -1;
    if (sX === sY)
      rVal = 0;
    return rVal;
  }

  if (!clCommon.isMobile()) {
    resizeTable();

    window.onresize = function(e) {
      resizeTable();
    };
  }
}

function renderData(data, type, row, meta) {
  var dataDisplay;
  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.renderData)
    dataDisplay = SteamFlowMeterPointInterface.renderData(data, type, row, meta);
  if (!dataDisplay || dataDisplay == null || dataDisplay == undefined) {
    dataDisplay = data;
  }

  var isFullCookie = clCommon.getCookie("bcssteam_full_view");

  if (!clCommon.isMobile() && isFullCookie === "true" && meta.col === 0) {
    return '<a href="javascript:void(0);" class="open-full-view-link">' + dataDisplay + '</a>';
  }

  if (!clCommon.isMobile()) resizeTable();

  return dataDisplay;
}

//To set the size of the table dynamically.
function resizeTable() {
  //Dont resize when listview is hidden
  if (contentView.classList.contains("hide")) {
    return;
  }
  setTimeout(setTableHeightOnResize, 50);

}

function setTableHeightOnResize() {
  // Get the height of the content list element
  var contListOffHeight = document.querySelector('.content-list').offsetHeight;

  // Get the height of the list head
  var listHeadOffHeight = document.querySelector('.listHead').offsetHeight;

  // Calculate and set the height of the list holder by subtracting the list head height from the content list height
  var listHolder = document.querySelector(".list-holder");
  listHolder.style.height = contListOffHeight - listHeadOffHeight + "px";

  // Get the heights of various DataTable elements
  var dtScrHeadClientHeight = document.querySelector('.dataTables_scrollHead').clientHeight; // DataTable scroll head height
  var dtFiltOfHeight = document.querySelector('.dataTables_filter').offsetHeight; // DataTable filter height
  var dtPagenateHeight = document.querySelector('.dataTables_paginate').offsetHeight; // DataTable pagination height

  // Set an additional offset to prevent the table from being too close to the bottom of the screen
  var addlOffSet = 10;

  // Calculate and set the height of the DataTable scroll body by subtracting the heights of the scroll head, filter, and pagination elements
  var scrollBodyHeight = listHolder.offsetHeight - dtScrHeadClientHeight - dtPagenateHeight - dtFiltOfHeight - addlOffSet;
  document.querySelector('div.dataTables_scrollBody').style.height = scrollBodyHeight + "px";

  // Adjust the DataTable columns after resizing
  steamFlowMeterPointTable.columns.adjust();
}



function registerEventListeners() {

  filterSteamFlowMeterPointBtn = document.getElementById('filterSteamFlowMeterPointBtn');
  filterSteamFlowMeterPointBtn.addEventListener('click', onFilterSteamFlowMeterPointBtnClick);

  formClose.addEventListener('click', toggleFullview);

  cancelBtns = document.querySelectorAll('.cancel-form-btn');
  cancelBtns.forEach(function(btn) {
    btn.addEventListener('click', onFormBackBtnClick);
  });
  if (clCommon.isMobile()) {
    cancelBtns = document.querySelectorAll('.cancel-form-btn');
    cancelBtns.forEach(function(btn) {
      clCommon.hide(btn);
    });
  }

  filterActionsSteamFlowMeterPointBtn = document.getElementById('filterActionsSteamFlowMeterPointBtn');
  filterActionsSteamFlowMeterPointBtn.addEventListener('click', onFilterSteamFlowMeterPointBtnClick);

  createSteamFlowMeterPointBtn = document.getElementById('createSteamFlowMeterPointBtn');
  createSteamFlowMeterPointBtn.addEventListener('click', onCreateSteamFlowMeterPointBtnClick);

  editSteamFlowMeterPointBtn = document.getElementById('updateSteamFlowMeterPointBtn');
  editSteamFlowMeterPointBtn.addEventListener('click', onUpdateSteamFlowMeterPointBtnClick);

  addSteamFlowMeterPointBtn = document.getElementById('addSteamFlowMeterPointBtn');
  addSteamFlowMeterPointBtn.addEventListener('click', onAddSteamFlowMeterPointBtnClick);



  if (clCommon.isMobile()) {
    deleteSteamFlowMeterPointBtn = document.getElementById('deleteSteamFlowMeterPointMobBtn');
    clCommon.hide(document.getElementById('deleteSteamFlowMeterPointBtn'));
  } else {
    deleteSteamFlowMeterPointBtn = document.getElementById('deleteSteamFlowMeterPointBtn');
  }
  deleteSteamFlowMeterPointBtn.addEventListener('click', onDeleteSteamFlowMeterPointBtnClick);







  loadMore = document.getElementById("loadMore");
  loadMore.addEventListener('click', onToolBarBtnClick);

  loadAll = document.getElementById("loadAll");
  loadAll.addEventListener('click', onToolBarBtnClick);

  steamFlowMeterPointSfmp_code.addEventListener('change', onFieldChange);
  steamFlowMeterPointSfmp_code.addEventListener('focus', onFieldFocus);
  steamFlowMeterPointSfmp_code.addEventListener('blur', onFieldChange);
  steamFlowMeterPointSfmp_description.addEventListener('change', onFieldChange);
  steamFlowMeterPointSfmp_description.addEventListener('focus', onFieldFocus);
  steamFlowMeterPointSfmp_description.addEventListener('blur', onFieldChange);
  steamFlowMeterPointSfmp_active.addEventListener('change', onFieldChange);
  steamFlowMeterPointSfmp_active.addEventListener('focus', onFieldFocus);
  steamFlowMeterPointSfmp_active.addEventListener('blur', onFieldChange);


  $('#tableHolder tbody').on('click', 'tr', onRowClick);
  $('#tableHolder tbody').on('click', '.open-full-view-link', onTableLinkClick);


  backBtn = document.getElementById('backBtn');
  backBtn.addEventListener('click', onFormBackBtnClick);

  if (clCommon.isMobile() && window.history && window.history.pushState) {
    window.addEventListener('popstate', function() {
      hideForm();
    });
  }

  if (clCommon.isMobile()) {
    clCommon.setCookie("bcssteam_full_view", "", -1);
    formView.classList.remove('fullview');
  }


  common_util.setSelectTitleOnChange();
}

function onTableLinkClick(e) {
  e.preventDefault();
  e.stopPropagation();
  var tr = $(this).closest('tr');
  if (!tr.hasClass('selected')) {
    tr.trigger('click');
  }
  toggleFullview(true);
}

function toggleFullview(forceState) {
  var isCurrentlyFull = formView.classList.contains('fullview');
  var shouldBeFull;

  if (typeof forceState === 'boolean') {
    shouldBeFull = forceState;
  } else {
    shouldBeFull = !isCurrentlyFull;
  }

  if (shouldBeFull) {
    // ENTER Full View 
    contentView.classList.add('hide');
    formView.classList.remove('hide');

    if (!clCommon.isMobile()) {
      formView.classList.add('fullview');
    }

    if (cancelCreateBtn) clCommon.show(cancelCreateBtn);
    if (cancelUpdateBtn) clCommon.show(cancelUpdateBtn);

    clCommon.setCookie("bcssteam_full_view", "true", 10);

    if (steamFlowMeterPointTable) {
      steamFlowMeterPointTable.rows().invalidate().draw(false);
      resizeTable();
    }
  } else {
    // EXIT Full View
    contentView.classList.remove('hide');
    formView.classList.remove('fullview');
    formView.classList.remove('hide');

    if (cancelCreateBtn) clCommon.hide(cancelCreateBtn);
    if (cancelUpdateBtn) clCommon.hide(cancelUpdateBtn);

    clCommon.setCookie("bcssteam_full_view", "", -1);

    if (steamFlowMeterPointTable) {
      steamFlowMeterPointTable.rows().invalidate().draw(false);
      resizeTable();
    }
  }

  // Handle Title Visibility
  var formTitle = document.getElementById('formTitleHeader');
  if (formTitle) {
    if (formView.classList.contains('fullview')) {
      formTitle.classList.remove('hide');
    } else {
      formTitle.classList.add('hide');
    }
  }

  //Handle Dynamic Field Layout (data-expand-class & data-normal-class)
  var expandFields = formView.querySelectorAll('[field]');

  if (expandFields.length > 0) {
    expandFields.forEach(function(el) {
      var expandStr = el.getAttribute('data-expand-class');
      var normalStr = el.getAttribute('data-normal-class');

      var expandClasses = expandStr ? expandStr : [];
      var normalClasses = normalStr ? normalStr : [];

      if (shouldBeFull) {
        el.className = expandClasses;
      } else {
        el.className = normalClasses;
      }
    });
  }
}


function openLookupView(panelElement) {
  clCommon.hide(formView);
  clCommon.show(panelElement);

  if (!clCommon.isMobile() && formView.classList.contains('fullview')) {
    panelElement.classList.add('fullview');
    contentView.classList.add('hide');
  }
}

function closeLookupView(panelElement) {
  clCommon.hide(panelElement);
  panelElement.classList.remove('fullview');

  clCommon.show(formView);
}

function onOptionClick(opObj, containerId, changedElementId) {
  clCommon.show(selectFilters);
  clCommon.hide(document.getElementById(containerId));

  var id = opObj.getAttribute("optnId");
  document.getElementById(changedElementId).value = id;


}

function onFilterSteamFlowMeterPointBtnClick(e) {
  clCommon.show(selectFilters);

  const elements = document.querySelectorAll('[id$="OptsTableContainer"]');

  const ids = Array.from(elements).map(el => el.id);

  for (var id in ids) {
    clCommon.hide(document.getElementById(ids[id]));
  }

  openFilterPopup(e);
}

function openFilterPopup(event) {
  var bodyEl = filterContent;

  var options = {
    onSearch: function() {}
  };

  var buttons = [{
      label: "Cancel",
      handler: function(onPrompt) {
        return function(e) {
          clCommon.hide(filterContent);

          this.setAttribute("pressed", "cancel"),
            onPrompt && onPrompt.call(this, null);
        };
      },
      attributes: {
        "data-bs-dismiss": "modal"
      }
    },
    {
      label: "Apply",
      handler: (searchHandler = options.onSearch,
        function(e) {
          clCommon.hide(filterContent);
          loadSteamFlowMeterPointData();
        }),
      attributes: {
        "data-bs-dismiss": "modal"
      }
    }
  ];

  var searchPopup = s_dialog('searchPopup', "Options", bodyEl, buttons, options, dlgOptions);
  searchPopup.show();
  clCommon.show(filterContent);

  if (clCommon.isMobile()) {
    if (event.target.id === 'filterSteamFlowMeterPointBtn') {
      activateTab('nav-filter', 'nav-action');
    } else if (event.target.id === 'filterActionsSteamFlowMeterPointBtn') {
      activateTab('nav-action', 'nav-filter');
    }
  } else {
    // Desktop default (assuming you don't need the clCommon hide/show logic here based on your original code)
    document.getElementById('nav-filter-tab').click();
  }
}

function activateTab(activeId, inactiveId) {
  // Handle the "Active" Tab
  clCommon.show(document.getElementById(activeId + '-tab'));
  clCommon.show(document.getElementById(activeId));
  document.getElementById(activeId + '-tab').classList.add('active');
  document.getElementById(activeId).classList.add('active', 'show');

  // Handle the "Inactive" Tab
  clCommon.hide(document.getElementById(inactiveId + '-tab'));
  clCommon.hide(document.getElementById(inactiveId));
  document.getElementById(inactiveId + '-tab').classList.remove('active');
  document.getElementById(inactiveId).classList.remove('active', 'show');
}


/*
	Function is called during onload event
*/
function onUser(resp) {
  clCommon.hideLoader('svcProgress');

  if (resp.code !== 200)
    redirect("/");

  userObj = resp.user;

  document.getElementById('userName').innerHTML = (userObj.firstname ? userObj.firstname : userObj.username);
  clCommon.initLanguage(userObj.realm_lang, function() {
    dlgOptions.STR_OK = clCommon.getString("OK", "OK");
    dlgOptions.STR_CANCEL = clCommon.getString("CANCEL", "Cancel");
    dlgOptions.STR_YES = clCommon.getString("YES", "Yes");
    dlgOptions.STR_NO = clCommon.getString("NO", "No");

    if (typeof SteamFlowMeterPointInterface === 'undefined')
      SteamFlowMeterPointInterface = null;

    if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onLoad)
      SteamFlowMeterPointInterface.onLoad();

    initControls();
    initTable();
    initSearchTable();



    registerEventListeners();
    setActionsSelectOptions();

    scrypto = new SimpleCrypto(userObj.realm_name);

    var userLocale = userObj.realm_locale ? userObj.realm_locale : localeObj;

    localeCode = userLocale.code ? userLocale.code : "en-IN";
    currency = userLocale.currency ? userLocale.currency : "INR";

    numberFormat = new Intl.NumberFormat(localeCode, {
      style: "decimal"
    });
    currencyFormat = new Intl.NumberFormat(localeCode, {
      style: "currency",
      currency: (typeof slocale !== 'undefined') ? slocale.getLocaleInfo(localeCode).currency_code : currency,
      minimumFractionDigits: 2,
      maximumFractionDigits: 2
    });


    clCommon.showLoader('svcProgress');

    var customAppName = clCommon.getCustomAppName();
    var url = customAppName ? ("/steps/hq/" + customAppName + "/common/appsvc?is_custom=true") : (isCustom ? "./common/appsvc?is_custom=true" : "./common/appsvc");
    url = isGlobal ? url : './common/appsvc';

    //To handle the across app integration
    if (params && params.app) {
      // If the URL already has a "?" in it, append with "&", otherwise with "?"
      url += (url.includes("?") ? "&" : "?") + "app=" + params.app;
    }


    clCommon.getSvc(true, url, onAppUserInfo, onAppUserInfoError);
  });
}

function initSearchTable() {
  for (var p = 0; p < searchOptsTables.length; p++) {
    var tableVarName = searchOptsTables[p]; // "productFilterOptsTable"
    var tableId = "#" + tableVarName; // "#productFilterOptsTable"

    // Create datatable instance
    var dt = $(tableId).DataTable({
      paging: false,
      info: false,
      autoWidth: false,
      columns: [{
          data: 'radio'
        },
        {
          data: 'optionName'
        }
      ],
      columnDefs: [{
        width: "25px",
        targets: 0
      }]
    });

    dt.table().node().classList.remove('nowrap');

    // Assign instance to the correct global variable
    window[tableVarName] = dt;
  }
}

function setActionsSelectOptions() {
  if (!document.getElementById('actionsSelectTable'))
    return;

  var tableId = "#" + "actionsSelectTable";


  // Create datatable instance
  var actionsTable = $(tableId).DataTable({
    paging: false,
    info: false,
    autoWidth: false,
    columns: [{
        data: 'radio'
      },
      {
        data: 'optionName'
      }
    ],
    columnDefs: [{
      width: "25px",
      targets: 0
    }]
  });

  actionsTable.table().node().classList.remove('nowrap');

  var optionsArr = [];
  for (var d in actionsSelectOptionsArr) {
    var optObj = actionsSelectOptionsArr[d];
    var tObj = {
      "optionName": '<label for="' + optObj.idName + '">' + optObj.displayName + '</label>',
      "radio": '<input type="radio" ' +
        'id="' + optObj.idName + '" ' +
        'name="optionName" ' +
        'onclick="onChangeOfActionSelect(this)">'
    };
    optionsArr.push(tObj);
  }

  actionsTable.clear().draw();
  actionsTable.rows.add(optionsArr).draw();
}

function capitalizeAndUnderscore(str) {
  // Trim the string, replace spaces with underscores, and convert to uppercase
  return str.trim().replace(/s+/g, '_').toUpperCase();
}

function loadMasters() {

  masterWs = 0;
  callOnLoadFunction();
}

function callOnLoadFunction() {
  if (msCheck == masterWs) {
    loadData();
    msCheck = 0;
    return;
  }
  setTimeout(() => {
    callOnLoadFunction();
  }, 300);
}

function findOnlyUniques(array) {
  var seen = {};
  var uniqueArr = [];

  // Step 1: Remove duplicates by _sid
  for (var i = 0; i < array.length; i++) {
    var item = array[i];
    if (!seen[item._sid]) {
      seen[item._sid] = true;
      uniqueArr.push(item);
    }
  }

  return uniqueArr;
}

function loadLimFunction(lim) {
  if (lim) {
    offset += limit;
    limit = lim;
  } else {
    offset = 0;
    limit = 0;
  }

  clCommon.setCookie("SteamFlowMeterPointOffset", offset, 10);
  clCommon.setCookie("SteamFlowMeterPointLimit", limit, 10);

  loadSteamFlowMeterPointData();
}


/*
	Function is called during onload event
	This function invoked on error response
*/
function onUserError(resp) {
  clCommon.hideLoader('svcProgress');
  redirect("/sauth/login.html");
}


/*
Function is called to redirect to the url
*/
function redirect(url) {
  window.location.href = url + (language !== "EN" ? ("?l=" + language) : "");
}





/*
	Function is called during onload event on error response
*/
function onAppUserInfo(resp) {
  var noDataElem = document.getElementById("contentNoData");
  var dataElem = document.getElementById("contentData");

  clCommon.hideLoader('svcProgress');

  if (resp.code === 200) {
    if (resp.menuArr) {
      clCommon.show(dataElem);
      dataSources.menuArr = resp.menuArr;
      dataSources.roleArr = resp.roleArr;

      processMenu(resp.menuArr);

      clCommon.appendSystemRoles(document.getElementById('sideMenu'), userObj);



      loadMasters();
    } else {
      clCommon.show(noDataElem);
      clCommon.hide(dataElem);
    }
  } else {
    s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
  }
}


/*
	Function is called during onload event on error response
*/
function onAppUserInfoError(resp) {
  clCommon.hideLoader('svcProgress');
  s_error(Strings.GET_APP_USER_INFO_ERROR_TITLE, Strings.APP_USER_MENU_ERROR, dlgOptions);
}

function showForm() {
  window.history.pushState('form', null, '#form');
  clCommon.hide(contentView);
  clCommon.show(formView);
}

function hideForm() {
  clCommon.show(contentView);
  clCommon.hide(formView);
  if (!clCommon.isMobile()) resizeTable();
}

function onFormBackBtnClick(e) {
  if (e) e.preventDefault();

  if (clCommon.isMobile()) {
    history.back();
    return;
  }

  var isFullCookie = clCommon.getCookie("bcssteam_full_view");
  clearForm();

  if (isFullCookie === "true") {
    contentView.classList.remove('hide');
    formView.classList.add('hide');
    formView.classList.add('fullview');
    if (selectedRow) {
      $(selectedRow).removeClass('selected');
      selectedRow = null;
    }
    deleteSteamFlowMeterPointBtn.classList.add('disabled');
  }

  if (!clCommon.isMobile()) resizeTable();
}




function loadData() {
  clCommon.showLoader('dataProgress');
  var beforeLoad = true;
  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onBeforeLoad)
    beforeLoad = SteamFlowMeterPointInterface.onBeforeLoad(dataSources);

  if (beforeLoad == false) {
    return
  }
  svcCount = 0;
  loadMainSteamFlowMeterPointData();

  onAfterLoadFunction();
}

function loadMainSteamFlowMeterPointData() {
  clCommon.showLoader('dataProgress');
  checkAndLoadData();
  hideLoaderFn();
}


function onAfterLoadFunction() {
  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onAfterLoad)
    SteamFlowMeterPointInterface.onAfterLoad(dataSources);
  clCommon.hideLoader('dataProgress');
  loadCheck = 0;
  return;
}


function hideLoaderFn() {
  clCommon.hideLoader('dataProgress');
  loadCheck = 0;
  return;
}

function checkAndLoadData() {
  var limitCookie = clCommon.getCookie("SteamFlowMeterPointLimit");
  var offsetCookie = clCommon.getCookie("SteamFlowMeterPointOffset");

  var limitVal = Number(limitCookie);
  var offsetVal = Number(offsetCookie);

  // Case 1: Load All - offset = 0 and limit = 0
  if (offsetVal === 0 && limitVal === 0 && limitCookie != "" && offsetCookie != "") {
    s_confirm(Strings.CONFIRM, Strings.CONFIRM_LOAD_ALL_PRT_1 + "?" + Strings.CONFIRM_LOAD_PRT_2, {
      STR_YES: dlgOptions.STR_YES,
      STR_NO: dlgOptions.STR_NO,
      onYes: function() {
        limCookieSet = 0;
        offCookieSet = 0;
        loadMore.classList.add('disabled');
        loadAll.classList.add('disabled');
        loadSteamFlowMeterPointData();
      },
      onNo: function() {
        offCookieSet = 0;
        limCookieSet = 100;
        loadSteamFlowMeterPointData();
      }
    });
    return;
  }

  // Case 2: Load 400 plus data threshold check
  if (offsetVal >= 400 && limitVal > 0) {
    s_confirm(Strings.CONFIRM, Strings.VALIDATION_COOKIE_LOAD_DATA + "?", {
      STR_YES: dlgOptions.STR_YES,
      STR_NO: dlgOptions.STR_NO,
      onYes: function() {
        offCookieSet = 0;
        limCookieSet = offsetVal + limitVal;
        loadSteamFlowMeterPointData();
      },
      onNo: function() {
        offCookieSet = 0;
        limCookieSet = 100;
        loadSteamFlowMeterPointData();
      }
    });
    return;
  } else if (limitCookie != "" && offsetCookie != "") {
    offCookieSet = 0;
    limCookieSet = offsetVal + limitVal;
  }

  // Default: load first 100
  loadSteamFlowMeterPointData();
}

function loadSteamFlowMeterPointData() {
  steamFlowMeterPointTable.clear().draw();
  clCommon.showLoader("listProgress");

  if (limCookieSet != null) {
    offset = offCookieSet;
    limit = limCookieSet;
  }

  var params = [offset, limit, ];

  var onBeforeData = true;
  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onBeforeData)
    onBeforeData = SteamFlowMeterPointInterface.onBeforeData(params, dataSources);


  if (onBeforeData) {
    params.push(function(resultObj) {
      clCommon.hideLoader("listProgress");
      var dataArr;
      var isSuccessful;
      if (resultObj.code == 200) { //On success response
        if (limCookieSet != null) {
          offset = limCookieSet == 0 ? 0 : (limCookieSet - 100);
          limit = 100;
          offCookieSet = null;
          limCookieSet = null;
        }
        dataArr = resultObj.data.concat(primaryArr);
        dataArr = findOnlyUniques(dataArr);
        isSuccessful = true;


        if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onAfterData)
          dataArr = SteamFlowMeterPointInterface.onAfterData(isSuccessful, dataArr, dataSources);

        onLoadSuccessResponse(dataArr);


        // Check Cookie
        var isFullCookie = clCommon.getCookie("bcssteam_full_view");
        // Only auto-select first row if NOT mobile AND cookie is NOT set
        if (!clCommon.isMobile() && isFullCookie !== "true" && dataArr.length > 0) {
          var firstRow = $('#tableHolder tbody tr:eq(0)');
          if (firstRow) {
            firstRow.click(); //by default select first row
          }
        }

        // If cookie IS set, we ensure the form is hidden to show the table list
        else if (isFullCookie === "true") {
          contentView.classList.remove('hide');
          formView.classList.add('hide');
          formView.classList.add('fullview'); // Maintain state class for later logic

          // Ensure buttons are reset if needed
          deleteSteamFlowMeterPointBtn.classList.add('disabled');
        }
        dataSources.primary = dataArr;
        primaryArr = dataArr;
        if (resultObj.count) {
          if ((primaryArr.length == resultObj.count) || (resultObj.count == -1)) {
            loadMore.classList.add('disabled');
            loadAll.classList.add('disabled');
          }
        }

      } else { //On error response
        isSuccessful = false;

        if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onAfterData)
          dataArr = SteamFlowMeterPointInterface.onAfterData(isSuccessful, dataArr, dataSources);

        s_error(Strings.ERROR, Strings.ERROR_LOAD_STEAMFLOWMETERPOINT, dlgOptions);
      }
    });
    Service.getAllSfmp.apply(this, params);
  }
  if (clCommon.isMobile()) {
    hideForm();
  }
}


function onLoadSuccessResponse(dataArr) {
  if (!dataArr || dataArr.length == 0) {
    clearForm();


    deleteSteamFlowMeterPointBtn.classList.add('disabled');
  }

  chunkSize = 30;
  currentIndex = 0;
  steamFlowMeterPointTable.clear().draw();
  loadChunk(dataArr);

  var isFullCookie = clCommon.getCookie("bcssteam_full_view");

  if (!clCommon.isMobile() && isFullCookie === "true") {
    contentView.classList.remove('hide');
    formView.classList.add('hide');
    formView.classList.add('fullview');

    clCommon.show(cancelCreateBtn);
    clCommon.show(cancelUpdateBtn);
  }
}

function loadChunk(dataArr) {
  if (!dataArr || currentIndex >= dataArr.length) {
    return;
  }

  var chunk = dataArr.slice(currentIndex, currentIndex + chunkSize);
  for (var i = 0; i < chunk.length; i++) {



  }
  steamFlowMeterPointTable.rows.add(chunk).draw(); // 'false' to not reset paging each time
  currentIndex += chunkSize;

  setTimeout(() => loadChunk(dataArr), 10); // adjust timeout as needed
}

function onChangeOfFilter(e) {



  offset = 0;
  limit = 100;

  clCommon.setCookie("SteamFlowMeterPointOffset", offset, 10);
  clCommon.setCookie("SteamFlowMeterPointLimit", limit, 10);

  primaryArr = [];
  loadMore.classList.remove('disabled');
  loadAll.classList.remove('disabled');

  const changedElement = e.target;
  const selectedType = changedElement.value;

  if (selectedType == 'search') {
    //TODO add logic for popup and setup options

    clCommon.hide(selectFilters);

    var optionsTbCont = changedElement.id + "OptsTableContainer";
    clCommon.show(document.getElementById(optionsTbCont));

    var title = "Search";

    const options = changedElement.querySelectorAll("option");
    var optnArr = [];
    options.forEach(opt => {
      const name = opt.textContent.trim();
      if (name !== "Search") {
        optnArr.push({
          id: opt.value,
          name: name
        });
      }
    });

    var optionsArr = [];
    for (var d in optnArr) {
      var optObj = optnArr[d];
      var tObj = {
        "optionName": '<label for="radio_' + optObj.id + '">' + optObj.name + '</label>',
        "radio": '<input type="radio" ' +
          'id="radio_' + optObj.id + '" ' +
          'name="optionName" ' +
          'optnId="' + optObj.id + '" ' +
          'onclick="onOptionClick(this, \'' + optionsTbCont + '\', \'' + e.target.id + '\')">'
      };
      optionsArr.push(tObj);
    }

    window[changedElement.id + "OptsTable"].clear().draw();
    window[changedElement.id + "OptsTable"].rows.add(optionsArr).draw();

    var onSearchCheck = true;
    if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onSearchChangeFilter) {
      onSearchCheck = SteamFlowMeterPointInterface.onSearchChangeFilter(e);
    }

  } else {
    var onChangeCheck = true;
    if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onChangeFilter)
      onChangeCheck = SteamFlowMeterPointInterface.onChangeFilter(e)
  }
}

function onChangeOfActionSelect(val) {
  var changedAction = val;
  var returnData = true;
  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onChangeOfActionSelect)
    returnData = SteamFlowMeterPointInterface.onChangeOfActionSelect(changedAction, dataSources);
  if (returnData == false) {
    return;
  }
}


function onCreateSteamFlowMeterPointBtnClick(e) {
  e.preventDefault();

  var steamFlowMeterPointObj = {};

  if (steamFlowMeterPointSfmp_code.value != "") {
    steamFlowMeterPointObj.sfmp_code = steamFlowMeterPointSfmp_code.value;
  } else {
    steamFlowMeterPointObj.sfmp_code = null;
  }
  if (steamFlowMeterPointSfmp_description.value != "") {
    steamFlowMeterPointObj.sfmp_description = steamFlowMeterPointSfmp_description.value;
  } else {
    steamFlowMeterPointObj.sfmp_description = null;
  }
  steamFlowMeterPointObj.sfmp_active = steamFlowMeterPointSfmp_active.checked;
  var date = new Date();
  steamFlowMeterPointObj.created_by = userObj.username;
  steamFlowMeterPointObj.created_on = date.getTime();
  steamFlowMeterPointObj.modified_on = date.getTime();
  steamFlowMeterPointObj.modified_by = userObj.username;

  //Validate the steamFlowMeterPoint object
  var checkSteamFlowMeterPoint = validate(steamFlowMeterPointObj);

  //In validation is successfull
  if (checkSteamFlowMeterPoint == true) {





    if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onBeforeCreate)
      steamFlowMeterPointObj = SteamFlowMeterPointInterface.onBeforeCreate(steamFlowMeterPointObj, dataSources);
    if (steamFlowMeterPointObj == false) {
      return;
    }


    clCommon.showLoader("createProgress");
    clCommon.disable(createSteamFlowMeterPointBtn);


    Service.createSfmp(steamFlowMeterPointObj, function(resultObj) {
      if (resultObj.code == 200) { //on success response
        clCommon.hideLoader("createProgress");
        clCommon.enable(createSteamFlowMeterPointBtn);
        s_toast(Strings.CREATE_STEAMFLOWMETERPOINT_TOAST_SUCCESS);
        var isSuccessful = true;


        if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onAfterCreate)
          steamFlowMeterPointObj = SteamFlowMeterPointInterface.onAfterCreate(isSuccessful, resultObj.data, dataSources);

        if (steamFlowMeterPointObj == false) {
          return;
        }

        clCommon.setCookie("steamFlowMeterPoint_id", resultObj.data._sid, 10);
        primaryArr.push(resultObj.data);

        addRow(resultObj.data);

      } else {
        var isSuccessful = false;


        if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onAfterCreate)
          steamFlowMeterPointObj = SteamFlowMeterPointInterface.onAfterCreate(isSuccessful, resultObj.data, dataSources);

        if (steamFlowMeterPointObj == false) {
          return;
        }

        s_error(Strings.STEAMFLOWMETERPOINT_ERROR_TITLE, Strings.CREATE_STEAMFLOWMETERPOINT_ERROR, dlgOptions);
      }
    });
  }
}

// Function to add a new row at the top
function addRow(newData) {



  // Add row to table
  var rowNode = steamFlowMeterPointTable.row.add(newData).node();

  // Draw the table to render the new data (triggers renderData)
  steamFlowMeterPointTable.draw(false);

  // Handle sorting to bring new item to top (visual preference)
  var rows = steamFlowMeterPointTable.rows().data().toArray();
  // Check if the last item is our new item
  if (rows.length > 0 && rows[rows.length - 1]._sid === newData._sid) {
    rows.unshift(rows.pop());
    steamFlowMeterPointTable.clear().rows.add(rows).draw(false);
  }

  // 5. Select the row
  selectRowBySid(newData._sid);
}



function onRowClick(e) {

  var isFullCookie = clCommon.getCookie("bcssteam_full_view");

  if (!selectedRow) { //executes when the row is clicked for the first time
    selectedRow = this;
    $(selectedRow).addClass('selected');

    deleteSteamFlowMeterPointBtn.classList.remove('disabled');


    clCommon.hide(createBtn);
    clCommon.show(updateBtn);

    clCommon.focus(steamFlowMeterPointSfmp_code);
    selectedRow = this;

    rowData = steamFlowMeterPointTable.row(selectedRow).data();



    if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onRowItemClick)
      rowData = SteamFlowMeterPointInterface.onRowItemClick(rowData);

    displayForm(rowData);
  } else {

    if (selectedRow === this && isFullCookie === "true" && !clCommon.isMobile()) {
      return;
    }

    if (clCommon.isMobile() || (selectedRow != this) || (selectedRow == this)) { //executed when another row is selected
      $(selectedRow).removeClass('selected');

      deleteSteamFlowMeterPointBtn.classList.add('disabled');


      clearForm();

      selectedRow = this;
      $(selectedRow).addClass('selected');

      deleteSteamFlowMeterPointBtn.classList.remove('disabled');


      clCommon.hide(createBtn);
      clCommon.show(updateBtn);
      clCommon.focus(steamFlowMeterPointSfmp_code);
      selectedRow = this;
      rowData = steamFlowMeterPointTable.row(selectedRow).data();



      if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onRowItemClick)
        rowData = SteamFlowMeterPointInterface.onRowItemClick(rowData);

      displayForm(rowData);
    }
  }

  if (clCommon.isMobile()) {
    showForm();
  } else {
    if (isFullCookie === "true") {
      hideForm();
    }
  }
}


//This function displays all the data in corresponsing controls
function displayForm(rowData) {

  steamFlowMeterPointSfmp_code.value = rowData.sfmp_code;
  steamFlowMeterPointSfmp_description.value = rowData.sfmp_description;
  steamFlowMeterPointSfmp_active.checked = rowData.sfmp_active;



  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onDisplayForm)
    rowData = SteamFlowMeterPointInterface.onDisplayForm(rowData);

}


function onUpdateSteamFlowMeterPointBtnClick(e) {
  e.preventDefault();

  var steamFlowMeterPointObj = {};

  if (steamFlowMeterPointSfmp_code.value != "") {
    steamFlowMeterPointObj.sfmp_code = steamFlowMeterPointSfmp_code.value;
  } else {
    steamFlowMeterPointObj.sfmp_code = null;
  }
  if (steamFlowMeterPointSfmp_description.value != "") {
    steamFlowMeterPointObj.sfmp_description = steamFlowMeterPointSfmp_description.value;
  } else {
    steamFlowMeterPointObj.sfmp_description = null;
  }
  steamFlowMeterPointObj.sfmp_active = steamFlowMeterPointSfmp_active.checked;

  steamFlowMeterPointObj._sid = rowData._sid;
  var date = new Date();
  steamFlowMeterPointObj.modified_on = date.getTime();
  steamFlowMeterPointObj.modified_by = userObj.username;
  steamFlowMeterPointObj.created_by = rowData.created_by ? rowData.created_by : userObj.username;
  steamFlowMeterPointObj.created_on = rowData.created_on ? rowData.created_on : null;

  //Validate the steamFlowMeterPoint object
  var checkSteamFlowMeterPoint = validate(steamFlowMeterPointObj);

  //In validation is successfull
  if (checkSteamFlowMeterPoint == true) {




    if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onBeforeUpdate)
      steamFlowMeterPointObj = SteamFlowMeterPointInterface.onBeforeUpdate(steamFlowMeterPointObj, dataSources);
    if (steamFlowMeterPointObj == false) {
      return;
    }


    clCommon.showLoader("updateProgress");
    clCommon.disable(updateSteamFlowMeterPointBtn);

    Service.updateSfmp(steamFlowMeterPointObj, function(resultObj) {
      if (resultObj.code == 200) { //on success response
        clCommon.hideLoader("updateProgress");
        clCommon.enable(updateSteamFlowMeterPointBtn);
        s_toast(Strings.UPDATE_STEAMFLOWMETERPOINT_TOAST_SUCCESS);

        var isSuccessful = true;


        if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onAfterUpdate)
          steamFlowMeterPointObj = SteamFlowMeterPointInterface.onAfterUpdate(isSuccessful, resultObj.data, dataSources);
        if (steamFlowMeterPointObj == false) {
          return;
        }


        clCommon.setCookie("steamFlowMeterPoint_id", resultObj.data._sid, 10);

        var index = primaryArr.findIndex(obj => obj._sid === resultObj.data._sid);

        if (index !== -1) {
          // Insert at the index where _sid matches
          primaryArr.splice(index, 0, resultObj.data);
        } else {
          // If not found, optionally push to end
          primaryArr.push(resultObj.data);
        }

        updateRowBySid(resultObj.data._sid, resultObj.data);

      } else {
        var isSuccessful = false;


        if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onAfterUpdate)
          steamFlowMeterPointObj = SteamFlowMeterPointInterface.onAfterUpdate(isSuccessful, resultObj.data, dataSources);
        if (steamFlowMeterPointObj == false) {
          return;
        }


        s_error(Strings.STEAMFLOWMETERPOINT_ERROR_TITLE, Strings.UPDATE_STEAMFLOWMETERPOINT_ERROR, dlgOptions);
      }
    });
  }
}

// Function to update a row by _sid
function updateRowBySid(sid, updatedData) {



  // Find the existing row index
  var rowIndexes = steamFlowMeterPointTable.rows().indexes().toArray();
  var foundIndex = -1;

  // Manual search to be precise
  for (var i = 0; i < rowIndexes.length; i++) {
    var d = steamFlowMeterPointTable.row(rowIndexes[i]).data();
    if (d && d._sid === sid) {
      foundIndex = rowIndexes[i];
      break;
    }
  }

  if (foundIndex !== -1) {
    // 1. Update the data in place (better than remove/add for maintaining state)
    steamFlowMeterPointTable.row(foundIndex).data(updatedData);

    // 2. Invalidate the row to force re-render (Runs renderData again)
    steamFlowMeterPointTable.row(foundIndex).invalidate().draw(false);

    // 3. Move to top (Optional, to match your previous logic)
    var rows = steamFlowMeterPointTable.rows().data().toArray();
    // Find our updated object in the array
    var internalIdx = rows.findIndex(function(r) {
      return r._sid === sid;
    });
    if (internalIdx > 0) {
      var item = rows.splice(internalIdx, 1)[0];
      rows.unshift(item);
      steamFlowMeterPointTable.clear().rows.add(rows).draw(false);
    }
  }

  selectRowBySid(sid);
}


// Function to select a row by _sid and trigger onRowClick
function selectRowBySid(sid) {
  if (sid == null) return;

  var table = steamFlowMeterPointTable;
  var pageLen = table.page.len();

  // Find the row by _sid
  var target = table.row(function(idx, data) {
    return data && data._sid === sid;
  });

  // Fallback: first row on current page if not found (and table not empty)
  if (!target.any()) {
    var first = table.row(':eq(0)', {
      page: 'current'
    });
    if (!first.any()) return; // empty table

    table.one('draw', function() {
      // Clear all current selections
      table.rows({
        page: 'current'
      }).every(function() {
        this.node().classList.remove('selected');
      });

      var firstNode = first.node();
      firstNode.classList.add('selected');

      // Trigger click
      firstNode.dispatchEvent(new Event('click', {
        bubbles: true
      }));
    });

    table.draw(false);
    return;
  }

  // Compute the display position (after search/order) to know the page number
  var rowIdx = target.index(); // DataTables internal index
  var displayIdxs = table.rows({
    search: 'applied',
    order: 'applied'
  }).indexes().toArray();
  var pos = displayIdxs.indexOf(rowIdx);
  var pageIndex = (pos > -1) ? Math.floor(pos / pageLen) : table.page();

  // After the table redraws to the right page, re-find & select the row, then click
  table.one('draw', function() {
    var r = table.row(function(i, d) {
      return d && d._sid === sid;
    });
    if (!r.any()) return;

    // Clear current selections
    table.rows({
      page: 'current'
    }).every(function() {
      this.node().classList.remove('selected');
    });

    var node = r.node();
    node.classList.add('selected');

    // Trigger click
    node.dispatchEvent(new Event('click', {
      bubbles: true
    }));
  });

  table.page(pageIndex).draw(false);


  var isFullCookie = clCommon.getCookie("bcssteam_full_view");
  if (isFullCookie === "true") {
    //clCommon.show(contentView);
    //clCommon.hide(formView);
    hideForm();
    if (selectedRow) {
      $(selectedRow).removeClass('selected');
      selectedRow = null;
    }
    deleteSteamFlowMeterPointBtn.classList.add('disabled');
  }
}




function onAddSteamFlowMeterPointBtnClick(e) {
  e.preventDefault();
  clearForm();

  if (clCommon.isMobile()) {
    showForm();
  } else {
    var isFullCookie = clCommon.getCookie("bcssteam_full_view");
    if (isFullCookie === "true") {
      toggleFullview(true);
    }
  }

  deleteSteamFlowMeterPointBtn.classList.add('disabled');


}



function clearForm() {
  var defaultObj = {
    "sfmp_code": "",
    "sfmp_description": "",
    "sfmp_active": false
  };





  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onClearForm) {
    var modDefaultObj = SteamFlowMeterPointInterface.onClearForm(defaultObj, dataSources);
    for (var attr in modDefaultObj) {
      if (modDefaultObj.hasOwnProperty(attr)) {
        defaultObj[attr] = modDefaultObj[attr]; // Apply changes to defaultObj
      }
    }
  }
  if (!clCommon.isMobile()) {
    clCommon.show(formView);
  }

  displayForm(defaultObj);

  clCommon.hide(updateBtn);
  clCommon.show(createBtn);

  deleteSteamFlowMeterPointBtn.classList.add('disabled');


  rowData = "";

  clCommon.focus(steamFlowMeterPointSfmp_code);

  if (selectedRow) {
    $(selectedRow).removeClass('selected');
  }

  selectedRow = "";
}



function onDeleteSteamFlowMeterPointBtnClick() {
  var clArr = deleteSteamFlowMeterPointBtn.classList;
  if (clArr.contains('disabled') == false)
    s_confirm(Strings.CONFIRM, Strings.STEAMFLOWMETERPOINT_DELETE_CONFIRM + " - " + rowData.sfmp_code + Strings.DELETE_TITLE_STEAMFLOWMETERPOINT + " ?", { //Confirmation with user
      STR_YES: dlgOptions.STR_YES,
      STR_NO: dlgOptions.STR_NO,
      onYes: function() { //on approval
        clCommon.showLoader("removeProgress");

        if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onBeforeDelete)
          rowData = SteamFlowMeterPointInterface.onBeforeDelete(rowData, dataSources);
        if (rowData == false) {
          clCommon.hideLoader("removeProgress");
          return;
        }


        Service.deleteSfmp(rowData._sid, function(resultObj) {
          if (resultObj.code == 200) { //on Success response
            clCommon.hideLoader("removeProgress");

            var isSuccessful = true;

            var afterDelete = true;
            if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onAfterDelete)
              afterDelete = SteamFlowMeterPointInterface.onAfterDelete(isSuccessful, resultObj, dataSources);
            if (afterDelete == false) {
              return;
            }


            deleteSteamFlowMeterPointBtn.classList.add('disabled');

            removeRowBySid(rowData._sid);

            var index = primaryArr.findIndex(item => item._sid === rowData._sid);

            if (index !== -1) {
              primaryArr.splice(index, 1);
            }

            s_toast(Strings.DELETE_STEAMFLOWMETERPOINT_TOAST_SUCCESS);
          } else { //On Error response
            var isSuccessful = false;

            var afterDelete = true;
            if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onAfterDelete)
              afterDelete = SteamFlowMeterPointInterface.onAfterDelete(isSuccessful, resultObj, dataSources);
            if (afterDelete == false) {
              return;
            }

            s_error(Strings.STEAMFLOWMETERPOINT_ERROR_TITLE, Strings.DELETE_STEAMFLOWMETERPOINT_ERROR, dlgOptions);
            clCommon.hideLoader("removeProgress");
          }
        });
      }
    });
}

// Function to remove a row by _sid
function removeRowBySid(sid) {
  // Remove the row that matches the provided sid
  steamFlowMeterPointTable.rows(function(idx, data, node) {
    return data._sid === sid; // Find row where _sid matches
  }).remove().draw(); // Remove and redraw the table

  if (steamFlowMeterPointTable.data().any()) {
    // Select the first row in the current page
    var firstRowNode = steamFlowMeterPointTable.row(':eq(0)', {
      page: 'current'
    }).node();
    if (firstRowNode) {


      clCommon.enable(deleteSteamFlowMeterPointBtn);

      $(firstRowNode).addClass('selected');
      $(firstRowNode).trigger('click'); // Trigger the click event to simulate row selection
    }
  }
}



function onFieldFocus(e) {
  e.preventDefault();
  var focusedField = this;

  var currencyAttr = focusedField.getAttribute("currency");
  var isCurrencyField = currencyAttr && currencyAttr.trim().toLowerCase() === "true";

  var defaultVal = focusedField.getAttribute("default_val");
  var defaultDigits = Number.isFinite(parseInt(defaultVal)) ? parseInt(defaultVal) : (isCurrencyField ? "" : "");




  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onFieldFocus)
    var returnData = SteamFlowMeterPointInterface.onFieldFocus(focusedField, dataSources);
}


function onFieldChange(e) {
  e.preventDefault();
  var changedField = this;





  var dependentFieldArr = document.querySelectorAll(".form-holder [data-dependent=" + changedField.id + "]");
  if (dependentFieldArr.length > 0) {
    for (var idx = 0; idx < dependentFieldArr.length; idx++) {
      var dependentField = dependentFieldArr[idx];
      var dataSrcFunction = dependentField.getAttribute("data-srcFunc");
      if (dataSrcFunction) {
        delete window.dataSources[dataSrcFunction];
        var functionCall = window[dataSrcFunction].call(window, true, changedField);
      } else {
        if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onFieldChange)
          var returnData = SteamFlowMeterPointInterface.onFieldChange(changedField, dataSources);
      }
    }
  } else {
    if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onFieldChange)
      var returnData = SteamFlowMeterPointInterface.onFieldChange(changedField, dataSources);
  }

}

function formattingNumberElements(fieldEl) {
  var raw = fieldEl.value.replace(/[^0-9.-]+/g, "");
  raw = raw === "" || isNaN(raw) ? 0 : Number(raw);
  fieldEl.setAttribute("val", raw);

  var decimalAttr = fieldEl.getAttribute("decimal");
  var decimalDigits = Number.isFinite(parseInt(decimalAttr)) ? parseInt(decimalAttr) : null;


  var currencyAttr = fieldEl.getAttribute("currency");
  var isCurrencyField = currencyAttr && currencyAttr.trim().toLowerCase() === "true";

  var currencyCode = (typeof slocale !== "undefined") ? slocale.getLocaleInfo(localeCode).currency_code : currency;


  if (isCurrencyField) {
    var currencyFormatForAmount = decimalDigits !== null ? new Intl.NumberFormat(localeCode, {
      style: "currency",
      currency: currencyCode,
      minimumFractionDigits: decimalDigits,
      maximumFractionDigits: decimalDigits
    }) : currencyFormat;


    fieldEl.value = currencyFormatForAmount.format(raw);
  } else {
    var numberFormatForAmount = decimalDigits !== null ? new Intl.NumberFormat(localeCode, {
      style: "decimal",
      minimumFractionDigits: decimalDigits,
      maximumFractionDigits: decimalDigits
    }) : numberFormat;


    fieldEl.value = numberFormatForAmount.format(raw);
  }
  return fieldEl;
}


function validate(steamFlowMeterPointObj) {

  if (!steamFlowMeterPointObj.sfmp_code) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.STEAMFLOWMETERPOINT_INVALID_SFMP_CODE, dlgOptions);
    return false;
  }

  if (!steamFlowMeterPointObj.sfmp_description) {
    s_info(Strings.VALIDATION_ERROR_TITLE, Strings.STEAMFLOWMETERPOINT_INVALID_SFMP_DESCRIPTION, dlgOptions);
    return false;
  }


  return true;
}


function containsOnlyLetters(str) {
  return /^[a-zA-Z\s]+$/.test(str);
}



function containsNumbers(str) {
  return /^[0-9.]+$/.test(str);
}




function onToolBarBtnClick(e) {
  e.preventDefault();
  var clickedBtn = this;
  var returnData = true;
  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onToolBarBtnClick)
    returnData = SteamFlowMeterPointInterface.onToolBarBtnClick(clickedBtn, dataSources);
  if (returnData === false) {
    return;
  } else {
    var clArr;
    switch (clickedBtn.id) {
      case "loadMore":
        clArr = loadMore.classList;
        if (clArr.contains('disabled') == false)
          loadLimFunction(limit);
        break;
      case "loadAll":
        clArr = loadAll.classList;
        if (clArr.contains('disabled') == false)
          s_confirm(Strings.CONFIRM, Strings.CONFIRM_LOAD_ALL_PRT_1 + "?" + Strings.CONFIRM_LOAD_PRT_2, { //Confirm with the user 
            STR_YES: dlgOptions.STR_YES,
            STR_NO: dlgOptions.STR_NO,
            onYes: function() { //On positive confirmation
              primaryArr = [];
              loadMore.classList.add('disabled');
              loadAll.classList.add('disabled');
              loadLimFunction(0);

            }
          });

        break;



    }
  }
}


function onLookupAddBtnClick(e) {
  e.preventDefault();
  var clickedBtn = this;
  var returnData = true;
  if (SteamFlowMeterPointInterface && SteamFlowMeterPointInterface.onLookupAddBtnClick)
    returnData = SteamFlowMeterPointInterface.onLookupAddBtnClick(clickedBtn.getAttribute('data-lookup-add'), clickedBtn, dataSources);
  if (returnData === false) {
    return;
  }
}