/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Fri Mar 06 2026 12:20:20 GMT+0530 (India Standard Time)
	Description : Create Service for connectivityStatus
	WARNING : DO NOT MODIFY THIS FILE
*/

//External library
var dsclientUtil = require('dsclient');


//Internal library
var Strings = require("../common/strings.js");
var appcommon = require("../common/common.js");
var createConnectivityStatusInterface = require("createinterface.js");

try {

  //Setting cache as null
  $g.response.headers["Cache-Control"] = "max-age=0";
  $g.response.headers["Cache-Control"] = "no-store";


  //Success response object
  var respObj = {
    code: 200,
    msg: Strings.CREATE_BCSSTEAM_CONNECTIVITY_STATUS_SUCCESS
  };


  //Checking whether the request is in query or body
  var params = appcommon.processParams($g.request);
  var paramStr = JSON.stringify(params);

  //check for Language setup 
  if (params && params.l) {
    var filePath = "/common/lang/";
    appcommon.initLanguage(params.l, filePath);
  }


  // Call 'onLoad' method from the Interface with params as the argument
  var onLoadRes;
  if (createConnectivityStatusInterface) {
    onLoadRes = createConnectivityStatusInterface.onLoad(params);
  }
  // Check if 'onLoad' override is true
  if (createConnectivityStatusInterface && onLoadRes && onLoadRes.override === true) {
    if (onLoadRes.resp) {
      if (onLoadRes.resp.code) {
        respObj = onLoadRes.resp;
      } else {
        respObj.code = 500;
        respObj.msg = Strings.SERVER_ERROR;
        if (createConnectivityStatusInterface) {
          respObj = createConnectivityStatusInterface.onError(respObj);
        }
        console.error("Unexpected server error when creating the connectivityStatus - " + paramStr);
      }
    }
  } else {

    // Calling 'beforeData' method from Interface and passing params as argument
    var beforeDataRes;
    if (createConnectivityStatusInterface) {
      beforeDataRes = createConnectivityStatusInterface.beforeData(params);
    }

    // Check if 'override' is true
    if (createConnectivityStatusInterface && beforeDataRes && beforeDataRes.override === true) {
      //Sending request to ds client
      if (beforeDataRes.resp) {
        if (beforeDataRes.resp.code) {
          respObj = beforeDataRes.resp;
        } else {
          respObj.code = 500;
          respObj.msg = Strings.SERVER_ERROR;
          respObj = createConnectivityStatusInterface.onError(respObj);
        }
      }
    } else {
      if (createConnectivityStatusInterface && beforeDataRes.params)
        params = beforeDataRes.params;

      //Only if params is there
      if (params && params.data) {

        if (createConnectivityStatusInterface) {
          params = createConnectivityStatusInterface.beforeExecute(params);
        }
        //Sending request to ds client
        respObj = dsclientUtil.execute(params, "BCSSteam", "BCSSteam_connectivity_status", "insert");
      } else {
        respObj.code = 400;
        respObj.msg = Strings.CREATE_BCSSTEAM_CONNECTIVITY_STATUS_ERROR;
      }
    }

    switch (respObj.code) {
      case 200:
        if (createConnectivityStatusInterface) {
          respObj.data = createConnectivityStatusInterface.afterData(respObj.data);
        }
        respObj.msg = Strings.CREATE_BCSSTEAM_CONNECTIVITY_STATUS_SUCCESS;
        break;
      case 400:
        respObj.msg = Strings.CREATE_BCSSTEAM_CONNECTIVITY_STATUS_ERROR;
        if (createConnectivityStatusInterface) {
          respObj = createConnectivityStatusInterface.onError(respObj);
        }
        console.error("Unable to create the connectivityStatus - " + paramStr);
        break;
      case 403:
        respObj.msg = Strings.ACCESS_DENIED;
        if (createConnectivityStatusInterface) {
          respObj = createConnectivityStatusInterface.onError(respObj);
        }
        console.error("User access denied when creating the connectivityStatus - " + paramStr);
        break;
      case 500:
        respObj.msg = Strings.SERVER_ERROR;
        if (createConnectivityStatusInterface) {
          respObj = createConnectivityStatusInterface.onError(respObj);
        }
        console.error("Unexpected server error when creating the connectivityStatus - " + paramStr);
        break;
    }

  }


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = respObj.code;
  $g.response.body = JSON.stringify(respObj);

} catch (e) {

  //Error response object
  var errorRespObj = {
    status: 500,
    message: Strings.SERVER_ERROR + " - " + e.message,
    stack: e.stack
  };
  if (createConnectivityStatusInterface) {
    errorRespObj = createConnectivityStatusInterface.onError(errorRespObj);
  }
  console.error("Unexpected server error when creating the connectivityStatus - " + paramStr + "-" + errorRespObj.message);


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = errorRespObj.status;
  $g.response.body = JSON.stringify(errorRespObj);

}