/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Mar 09 2026 10:54:37 GMT+0530 (India Standard Time)
	Description : Create Service Interface for sfmStatus
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantCreateSfmStatusInterface = app.getTenantWSInterface('BCSSteam', 'sfmstatus/create');

if (typeof TenantCreateSfmStatusInterface === 'undefined')
	TenantCreateSfmStatusInterface = {};


module.exports = {
	onLoad: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};


		if (TenantCreateSfmStatusInterface && TenantCreateSfmStatusInterface.onLoad) {
			rObj = TenantCreateSfmStatusInterface.onLoad(params);
		}
		return rObj;
	},

	beforeData: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};

		var hasError;

		if (params && params.data){
			try{
				params.data = JSON.parse(params.data);
			}catch(e){
				params.data = params.data;
			}

			var getAllSfmStatusRespObj = dsclientUtil.execute({}, "BCSSteam", "BCSSteam_sfm_status", "getAll");

			if (getAllSfmStatusRespObj && getAllSfmStatusRespObj.code == 200) {

				if (getAllSfmStatusRespObj.data && getAllSfmStatusRespObj.data.length > 0) {

					var paramSfmId = params.data.sfm_code_id;
					var paramStartDate = params.data.sfms_start_date;

					for (var idx = 0; idx < getAllSfmStatusRespObj.data.length; idx++) {
						var record = getAllSfmStatusRespObj.data[idx];

						if (record.sfm_code_id === paramSfmId) {

							var recStartDate = record.sfms_start_date;
							var recEndDate;

							if (record.sfms_end_date) {
								recEndDate = record.sfms_end_date;
							} else {
								recEndDate = null;
							}

							hasError = false;

							if (recStartDate < paramStartDate) {
								if (!recEndDate || recEndDate >= paramStartDate) {
									hasError = true; 
								}
							} else {
								hasError = true;
							}

							if (hasError) {
								rObj.override = true;
								rObj.resp = {
									"code" : 400,
									"msg" : "Date range conflicts",
									"err_code" : 422
								};
								break; 
							}
						}
					}
				}
			} else {
				rObj.override = true;
				rObj.resp = {
					"code" : 400,
					"msg" : Strings.ERROR || "Error fetching existing records"
				};
			}

			params.data = JSON.stringify(params.data);
		}




		if (TenantCreateSfmStatusInterface && TenantCreateSfmStatusInterface.beforeData) {
			rObj = TenantCreateSfmStatusInterface.beforeData(params);
		}
		return rObj;
	},

	beforeExecute: function(queryParams) {
		//custom code here

		if (TenantCreateSfmStatusInterface && TenantCreateSfmStatusInterface.beforeExecute) {
			queryParams = TenantCreateSfmStatusInterface.beforeExecute(queryParams);
		}
		return queryParams;
	},


	afterData: function(createSfmStatusData) {


		if (TenantCreateSfmStatusInterface && TenantCreateSfmStatusInterface.afterData) {
			createSfmStatusData = TenantCreateSfmStatusInterface.afterData(createSfmStatusData);
		}
		return createSfmStatusData;
	},

	onError: function(errorObj) {


		if (TenantCreateSfmStatusInterface && TenantCreateSfmStatusInterface.onError) {
			errorObj = TenantCreateSfmStatusInterface.onError(errorObj);
		}
		return errorObj;
	}
};