/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Fri Feb 13 2026 12:05:18 GMT+0530 (India Standard Time)
	Description : Delete Service for utilizationPoint
	WARNING : DO NOT MODIFY THIS FILE
*/

//External library
var dsclientUtil = require('dsclient');


//Internal library
var Strings = require("../common/strings.js");
var appcommon = require("../common/common.js");
var deleteUtilizationPointInterface = require("deleteinterface.js");

try {

  //Setting cache as null
  $g.response.headers["Cache-Control"] = "max-age=0";
  $g.response.headers["Cache-Control"] = "no-store";


  //Success response object
  var respObj = {
    code: 200,
    msg: Strings.DELETE_BCSFUEL_UTILIZATION_POINT_SUCCESS
  };


  //Checking whether the request is in query or body
  var params = appcommon.processParams($g.request);
  var paramStr = JSON.stringify(params);

  //check for Language setup 
  if (params && params.l) {
    var filePath = "/common/lang/";
    appcommon.initLanguage(params.l, filePath);
  }


  // Call 'onLoad' method from the Interface with params as the argument
  var onLoadRes;
  if (deleteUtilizationPointInterface)
    onLoadRes = deleteUtilizationPointInterface.onLoad(params);

  // Check if 'onLoad' override is true
  if (deleteUtilizationPointInterface && onLoadRes && onLoadRes.override === true) {
    if (onLoadRes.resp) {
      if (onLoadRes.resp.code) {
        respObj = onLoadRes.resp;
      } else {
        respObj.code = 500;
        respObj.msg = Strings.SERVER_ERROR;
        if (deleteUtilizationPointInterface)
          respObj = deleteUtilizationPointInterface.onError(respObj);
        console.error("Unexpected server error when deleting the utilizationPoint - " + paramStr);
      }
    }
  } else {

    // Calling 'beforeData' method from Interface and passing params as argument
    var beforeDataRes;
    if (deleteUtilizationPointInterface)
      beforeDataRes = deleteUtilizationPointInterface.beforeData(params);

    // Check if 'override' is true
    if (deleteUtilizationPointInterface && beforeDataRes && beforeDataRes.override === true) {
      //Sending request to ds client
      if (beforeDataRes.resp) {
        if (beforeDataRes.resp.code) {
          respObj = beforeDataRes.resp;
        } else {
          respObj.code = 500;
          respObj.msg = Strings.SERVER_ERROR;
          respObj = deleteUtilizationPointInterface.onError(respObj);
        }
      }
    } else {
      if (deleteUtilizationPointInterface && beforeDataRes.params)
        params = beforeDataRes.params;

      //Only if params is there
      if (params && params.id) {


        if (deleteUtilizationPointInterface) {
          params = deleteUtilizationPointInterface.beforeExecute(params);
        }
        //Sending request to ds client
        respObj = dsclientUtil.execute(params, "BCSFuel", "bcsfuel_utilization_point", "delete");
      } else {
        respObj.code = 400;
        respObj.msg = Strings.DELETE_BCSFUEL_UTILIZATION_POINT_ERROR;
      }
    }

    switch (respObj.code) {
      case 200:
        if (deleteUtilizationPointInterface)
          respObj = deleteUtilizationPointInterface.afterData(respObj);
        respObj.msg = Strings.DELETE_BCSFUEL_UTILIZATION_POINT_SUCCESS;
        break;
      case 400:
        respObj.msg = Strings.DELETE_BCSFUEL_UTILIZATION_POINT_ERROR;
        if (deleteUtilizationPointInterface)
          respObj = deleteUtilizationPointInterface.onError(respObj);
        console.error("Unable to delete the utilizationPoint - " + paramStr);
        break;
      case 403:
        respObj.msg = Strings.ACCESS_DENIED;
        if (deleteUtilizationPointInterface)
          respObj = deleteUtilizationPointInterface.onError(respObj);
        console.error("User access denied when deleting the utilizationPoint - " + paramStr);
        break;
      case 500:
        respObj.msg = Strings.SERVER_ERROR;
        if (deleteUtilizationPointInterface)
          respObj = deleteUtilizationPointInterface.onError(respObj);
        console.error("Unexpected server error when deleting the utilizationPoint - " + paramStr);
        break;
    }

  }


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = respObj.code;
  $g.response.body = JSON.stringify(respObj);

} catch (e) {

  //Error response object
  var errorRespObj = {
    status: 500,
    message: Strings.SERVER_ERROR + " - " + e.message,
    stack: e.stack
  };
  if (deleteUtilizationPointInterface)
    errorRespObj = deleteUtilizationPointInterface.onError(errorRespObj);
  console.error("Unexpected server error when deleting the utilizationPoint - " + paramStr + "-" + errorRespObj.message);


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = errorRespObj.status;
  $g.response.body = JSON.stringify(errorRespObj);

}