/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Fri Feb 13 2026 15:31:00 GMT+0530 (India Standard Time)
	Description : Get Service for utilizationPoint
	WARNING : DO NOT MODIFY THIS FILE
*/

//External library
var dsclientUtil = require('dsclient');


//Internal library
var Strings = require("../common/strings.js");
var appcommon = require("../common/common.js");
var getUtilizationPointMapInterface = require("getinterface.js");

try {

  //Setting cache as null
  $g.response.headers["Cache-Control"] = "max-age=0";
  $g.response.headers["Cache-Control"] = "no-store";


  //Success response object
  var respObj = {
    code: 200,
    msg: Strings.READ_BCSFUEL_UTILIZATION_POINT_GETUTILIZATIONPOINTMAP_SUCCESS
  };


  //Checking whether the request is in query or body
  var params = appcommon.processParams($g.request);
  var paramStr = JSON.stringify(params);

  //check for Language setup 
  if (params && params.l) {
    var filePath = "/common/lang/";
    appcommon.initLanguage(params.l, filePath);
  }


  // Call 'onLoad' method from the Interface with params as the argument
  var onLoadRes = null;
  if (getUtilizationPointMapInterface)
    onLoadRes = getUtilizationPointMapInterface.onLoad(params);

  // Check if 'onLoad' override is true
  if (onLoadRes && onLoadRes.override === true) {
    if (onLoadRes.resp) {
      if (onLoadRes.resp.code) {
        respObj = onLoadRes.resp;
      } else {
        respObj.code = 500;
        respObj.msg = Strings.SERVER_ERROR;
        if (getUtilizationPointMapInterface)
          respObj = getUtilizationPointMapInterface.onError(respObj);
        console.error("Unexpected server error when retrieving the utilizationPoint - " + paramStr);
      }
    }
  } else {

    // Calling 'beforeData' method from Interface and passing params as argument
    var beforeDataRes = null;
    if (getUtilizationPointMapInterface)
      beforeDataRes = getUtilizationPointMapInterface.beforeData(params);

    // Check if 'override' is true
    if (beforeDataRes && beforeDataRes.override === true) {
      //Sending request to ds client
      if (beforeDataRes.resp) {
        if (beforeDataRes.resp.code) {
          respObj = beforeDataRes.resp;
        } else {
          respObj.code = 500;
          respObj.msg = Strings.SERVER_ERROR;
          if (getUtilizationPointMapInterface)
            respObj = getUtilizationPointMapInterface.onError(respObj);
        }
      }
    } else {
      if (beforeDataRes && beforeDataRes.params)
        params = beforeDataRes.params;

      //Only if params is there
      if (params && params.id) {

        //Query Params
        var getParams = {
          "id": params.id
        };


        if (getUtilizationPointMapInterface) {
          getParams = getUtilizationPointMapInterface.beforeExecute(getParams);
        }
        //Sending request to ds client
        respObj = dsclientUtil.execute(getParams, "BCSFuel", "bcsfuel_utilization_point", "get");
      } else {
        respObj.code = 400;
        respObj.msg = Strings.READ_BCSFUEL_UTILIZATION_POINT_ERROR;
      }
    }

    switch (respObj.code) {
      case 200:
        if (getUtilizationPointMapInterface)
          respObj.data = getUtilizationPointMapInterface.afterData(respObj.data);
        respObj.msg = Strings.READ_BCSFUEL_UTILIZATION_POINT_GETUTILIZATIONPOINTMAP_SUCCESS;
        break;
      case 400:
        respObj.msg = Strings.READ_BCSFUEL_UTILIZATION_POINT_GETUTILIZATIONPOINTMAP_ERROR;
        if (getUtilizationPointMapInterface)
          respObj = getUtilizationPointMapInterface.onError(respObj);
        console.error("Unable to retrieve the utilizationPoint - " + paramStr);
        break;
      case 403:
        respObj.msg = Strings.ACCESS_DENIED;
        if (getUtilizationPointMapInterface)
          respObj = getUtilizationPointMapInterface.onError(respObj);
        console.error("User access denied when retrieving the utilizationPoint - " + paramStr);
        break;
      case 500:
        respObj.msg = Strings.SERVER_ERROR;
        if (getUtilizationPointMapInterface)
          respObj = getUtilizationPointMapInterface.onError(respObj);
        console.error("Unexpected server error when retrieving the utilizationPoint - " + paramStr);
        break;
    }

  }


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = respObj.code;
  $g.response.body = JSON.stringify(respObj);

} catch (e) {

  //Error response object
  var errorRespObj = {
    status: 500,
    message: Strings.SERVER_ERROR + " - " + e.message,
    stack: e.stack
  };
  if (getUtilizationPointMapInterface)
    errorRespObj = getUtilizationPointMapInterface.onError(errorRespObj);
  console.error("Unexpected server error when retrieving the utilizationPoint - " + paramStr + "-" + errorRespObj.message);


  $g.response.headers["content-type"] = "application/json";
  $g.response.status = errorRespObj.status;
  $g.response.body = JSON.stringify(errorRespObj);

}