/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Fri Feb 13 2026 15:31:00 GMT+0530 (India Standard Time)
	Description : Get Service Interface for utilizationPoint
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetUtilizationPointMapInterface = app.getTenantWSInterface('BCSFuel', 'utilizationpoint/get');

if (typeof TenantGetUtilizationPointMapInterface === 'undefined')
  TenantGetUtilizationPointMapInterface = {};

module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetUtilizationPointMapInterface && TenantGetUtilizationPointMapInterface.onLoad) {
      rObj = TenantGetUtilizationPointMapInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetUtilizationPointMapInterface && TenantGetUtilizationPointMapInterface.beforeData) {
      rObj = TenantGetUtilizationPointMapInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams) {
    //custom code here

    if (TenantGetUtilizationPointMapInterface && TenantGetUtilizationPointMapInterface.beforeExecute) {
      queryParams = TenantGetUtilizationPointMapInterface.beforeExecute(queryParams);
    }
    return queryParams;
  },


  afterData: function(getUtilizationPointMapData) {


    if (TenantGetUtilizationPointMapInterface && TenantGetUtilizationPointMapInterface.afterData) {
      getUtilizationPointMapData = TenantGetUtilizationPointMapInterface.afterData(getUtilizationPointMapData);
    }
    return getUtilizationPointMapData;
  },

  onError: function(errorObj) {


    if (TenantGetUtilizationPointMapInterface && TenantGetUtilizationPointMapInterface.onError) {
      errorObj = TenantGetUtilizationPointMapInterface.onError(errorObj);
    }
    return errorObj;
  }
};