/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 05 2026 12:35:01 GMT+0530 (India Standard Time)
	Description : Get Service Interface for size 
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetSizeInterface = app.getTenantWSInterface('BCSSteam', 'master/getsize');

if (typeof TenantGetSizeInterface === 'undefined')
  TenantGetSizeInterface = {};


module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };

    if (TenantGetSizeInterface && TenantGetSizeInterface.onLoad) {
      rObj = TenantGetSizeInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetSizeInterface && TenantGetSizeInterface.beforeData) {
      rObj = TenantGetSizeInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams, qType) {
    //custom code here

    if (TenantGetSizeInterface && TenantGetSizeInterface.beforeExecute) {
      queryParams = TenantGetSizeInterface.beforeExecute(queryParams, qType);
    }
    return queryParams;
  },

  afterData: function(getSizeData) {


    if (TenantGetSizeInterface && TenantGetSizeInterface.afterData) {
      getSizeData = TenantGetSizeInterface.afterData(getSizeData);
    }
    return getSizeData;
  },

  onError: function(errorObj) {

    if (TenantGetSizeInterface && TenantGetSizeInterface.onError) {
      errorObj = TenantGetSizeInterface.onError(errorObj);
    }
    return errorObj;
  }
};