/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 05 2026 13:12:50 GMT+0530 (India Standard Time)
	Description : CombineMaster Save Service Interface for sfmReadingReasonCode
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantSaveSfmReadingReasonCodeInterface = app.getTenantWSInterface('BCSSteam', 'master/savesfmreadingreasoncode');

if (typeof TenantSaveSfmReadingReasonCodeInterface === 'undefined')
	TenantSaveSfmReadingReasonCodeInterface = {};

module.exports = {
	onLoad: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};


		if (TenantSaveSfmReadingReasonCodeInterface && TenantSaveSfmReadingReasonCodeInterface.onLoad) {
			rObj = TenantSaveSfmReadingReasonCodeInterface.onLoad(params);
		}

		return rObj;
	},

	
	beforeData: function(params) {
		var rObj = {
			"override": false,
			"params": params,
		};

		var refFlag = false;
		var deletedDup = false;
		var rcDataArr;
		var deletedObjectsArr = [];
		var paramData = JSON.parse(params.data);
		var paramArr = JSON.parse(paramData.master_data);
		var deletedWithRefArr = [];

		var MASTER_TABLE = "bcssteam_sfmReadingReasonCode";
		var queryParams = {
			"cols": ["master_name", "master_data", "edited_by", "edited_on"],
			"filter": [{
				"col": "master_name",
				"op": "=",
				"val": MASTER_TABLE
			}]
		};

		var masterRespObj = dsclientUtil.execute(queryParams, "BCSSteam", "BCSSteam_combined_master", "query");

		if (masterRespObj && masterRespObj.code == 200 && masterRespObj.data && masterRespObj.data.length > 0) {

			rcDataArr = JSON.parse(masterRespObj.data[0].master_data);

			//taking deleted obj
			for (var j = 0; j < rcDataArr.length; j++) {
				var found = false;
				var singleObj = rcDataArr[j];

				for (var i = 0; i < paramArr.length; i++) {
					if (singleObj.id === paramArr[i].id) {
						found = true;
						break;
					}
				}
				if (!found) {
					deletedObjectsArr.push(singleObj);
				}
			}

			if (deletedObjectsArr.length > 0) {
				var deletedIdsOnly = [];
						//deleted and added same name adding id to new data
				for(var paramIdx = 0; paramIdx < paramArr.length; paramIdx++){
					for(var dataIdx = 0; dataIdx < deletedObjectsArr.length; dataIdx++){
						if(paramArr[paramIdx].id == null && normalize( paramArr[paramIdx].reading_reason_code) == normalize(deletedObjectsArr[dataIdx].reading_reason_code)){
							paramArr[paramIdx].id = deletedObjectsArr[dataIdx].id
							deletedObjectsArr.splice(dataIdx, 1); 
							deletedDup = true;
							break;
						}
					}
				}
				for (var delIdx = 0; delIdx < deletedObjectsArr.length; delIdx++) {
					deletedIdsOnly.push(deletedObjectsArr[delIdx].id);
				}

				var formatedDeletedIds = _formatArrForInQuery(deletedIdsOnly);
				var getUtilityByRc = {
					"cols": ["reason"],
					"filter": [{
						"col": "reason",
						"op": "IN",
						"val": formatedDeletedIds
					}]
				};

				var utilityRespObj = dsclientUtil.execute(getUtilityByRc, "BCSSteam", "BCSSteam_utility", "query");
				var utilityObjArr = utilityRespObj.data;

				if (utilityRespObj.code === 200 && utilityObjArr && utilityObjArr.length > 0) {

					for (var idx = 0; idx < deletedObjectsArr.length; idx++) {
						for (var jdx = 0; jdx < utilityObjArr.length; jdx++) {
							if (deletedObjectsArr[idx].id == utilityObjArr[jdx].reason) {
								deletedWithRefArr.push(deletedObjectsArr[idx]);
								refFlag = true;
								break;
							}
						}
					}
				}

				// If references found, block the deletion
				if (deletedWithRefArr.length > 0 || deletedDup === true) {
					var finalDataToSave = paramArr.concat(deletedWithRefArr);

					var masterObj = {
						"master_name": MASTER_TABLE,
						"master_data": JSON.stringify(finalDataToSave),
						"edited_by": paramData.edited_by,
						"edited_on": paramData.edited_on,
						"_sid":masterRespObj.data[0]._sid
					};

					var respObj = dsclientUtil.execute({ data: JSON.stringify(masterObj) }, "BCSSteam", "BCSSteam_combined_master", "update");

					if (respObj && respObj.code == 200) {
						rObj.override = true;
						rObj.resp = {
							"code": 400,
							"msg": Strings.FOREGIN_REFERENCE_FOUND,
							"err_code": 422,
							"data": JSON.parse(respObj.data.master_data),
							"deletedWithRefArr":deletedWithRefArr,
							"refFlag":refFlag,
							"deletedDup":deletedDup
						};

					}else{
						rObj.override = true;
						rObj.resp = {
							"code": 400,
							"msg": Strings.FOREGIN_REFERENCE_FOUND,
							"err_code": 400,
							"respObj":respObj,
						};
					}
				}
			}
		}



		if (TenantSaveSfmReadingReasonCodeInterface && TenantSaveSfmReadingReasonCodeInterface.beforeData) {
			rObj = TenantSaveSfmReadingReasonCodeInterface.beforeData(params);
		}

		return rObj;
	},

	beforeExecute: function(queryParams, qType) {
		//custom code here

		if (TenantSaveSfmReadingReasonCodeInterface && TenantSaveSfmReadingReasonCodeInterface.beforeExecute) {
			queryParams = TenantSaveSfmReadingReasonCodeInterface.beforeExecute(queryParams, qType);
		}
		return queryParams;
	},

	afterData: function(saveSfmReadingReasonCodeData) {


		if (TenantSaveSfmReadingReasonCodeInterface && TenantSaveSfmReadingReasonCodeInterface.afterData) {
			saveSfmReadingReasonCodeData = TenantSaveSfmReadingReasonCodeInterface.afterData(saveSfmReadingReasonCodeData);
		}
		return saveSfmReadingReasonCodeData;
	},

	onError: function(errorObj) {

		if (TenantSaveSfmReadingReasonCodeInterface && TenantSaveSfmReadingReasonCodeInterface.onError) {
			errorObj = TenantSaveSfmReadingReasonCodeInterface.onError(errorObj);
		}
		return errorObj;
	}
};

function _formatArrForInQuery(arr) {
	var result = [];
	for (var i = 0; i < arr.length; i++) {
		var item = arr[i];
		var idValue = "";

		if (item !== null && typeof item === 'object' && item.id) {
			idValue = item.id;
		} else {
			idValue = item;
		}

		result.push("'" + idValue + "'");
	}
	return "(" + result.join(", ") + ")";
}



function normalize(val) {
	if (typeof val !== "string") return "";
	return val
		.toLowerCase()
		.replace(/\s+/g, "");        // remove all spaces
	//.replace(/[^a-z0-9]/g, ""); // remove special characters
}
