/*
	Generated By : Steps Code Generator.
	Version : 2024
	Generated On : Mon Jan 05 2026 13:00:35 GMT+0530 (India Standard Time)
	Description : Get Service Interface for outputSignal 
	WARNING : DO NOT MODIFY THE GENERATED INTERFACE METHOD NAME OR ARGUMENTS
*/

//Use the following global objects as required.
//dsclientUtil - For data service related actions.
//Strings - For Strings dictionary. refer ../common/strings.js
//appcommon - For common help utils. refer ../common/common.js

var app = require('app');

var TenantGetOutputSignalInterface = app.getTenantWSInterface('BCSSteam', 'master/getoutputsignal');

if (typeof TenantGetOutputSignalInterface === 'undefined')
  TenantGetOutputSignalInterface = {};


module.exports = {
  onLoad: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };

    if (TenantGetOutputSignalInterface && TenantGetOutputSignalInterface.onLoad) {
      rObj = TenantGetOutputSignalInterface.onLoad(params);
    }
    return rObj;
  },

  beforeData: function(params) {
    var rObj = {
      "override": false,
      "params": params,
    };


    if (TenantGetOutputSignalInterface && TenantGetOutputSignalInterface.beforeData) {
      rObj = TenantGetOutputSignalInterface.beforeData(params);
    }
    return rObj;
  },

  beforeExecute: function(queryParams, qType) {
    //custom code here

    if (TenantGetOutputSignalInterface && TenantGetOutputSignalInterface.beforeExecute) {
      queryParams = TenantGetOutputSignalInterface.beforeExecute(queryParams, qType);
    }
    return queryParams;
  },

  afterData: function(getOutputSignalData) {


    if (TenantGetOutputSignalInterface && TenantGetOutputSignalInterface.afterData) {
      getOutputSignalData = TenantGetOutputSignalInterface.afterData(getOutputSignalData);
    }
    return getOutputSignalData;
  },

  onError: function(errorObj) {

    if (TenantGetOutputSignalInterface && TenantGetOutputSignalInterface.onError) {
      errorObj = TenantGetOutputSignalInterface.onError(errorObj);
    }
    return errorObj;
  }
};